// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: msc_management/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { InitiateCallRequest, InitiateCallResponse } from "../../bsc/v1/service";
import { Empty } from "../../google/protobuf/empty";

export const protobufPackage = "msc_management.v1";

/** Active MSC call identifiers. */
export interface CallList {
  /** MSC call/session IDs currently tracked by call control. */
  callIds: string[];
}

/**
 * Submits a mobile-terminated SMS. Exactly one of `destination_number` or
 * `destination_imsi` must be set:
 *   * `destination_number` resolves the target via HLR and addresses by phone
 *     number (subscriber-only path).
 *   * `destination_imsi` sends to the given IMSI directly without an HLR
 *     lookup; used for non-subscriber mobiles seen on the air.
 */
export interface SendSmsRequest {
  originatingNumber: string;
  text: string;
  timeoutMs?: number | undefined;
  destinationNumber?: string | undefined;
  destinationImsi?: string | undefined;
}

export interface SendSmsResponse {
  accepted: boolean;
  message: string;
}

function createBaseCallList(): CallList {
  return { callIds: [] };
}

export const CallList: MessageFns<CallList> = {
  encode(message: CallList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.callIds) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallList {
    return {
      callIds: globalThis.Array.isArray(object?.callIds)
        ? object.callIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.call_ids)
        ? object.call_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: CallList): unknown {
    const obj: any = {};
    if (message.callIds?.length) {
      obj.callIds = message.callIds;
    }
    return obj;
  },

  create(base?: DeepPartial<CallList>): CallList {
    return CallList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CallList>): CallList {
    const message = createBaseCallList();
    message.callIds = object.callIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseSendSmsRequest(): SendSmsRequest {
  return {
    originatingNumber: "",
    text: "",
    timeoutMs: undefined,
    destinationNumber: undefined,
    destinationImsi: undefined,
  };
}

export const SendSmsRequest: MessageFns<SendSmsRequest> = {
  encode(message: SendSmsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.originatingNumber !== "") {
      writer.uint32(10).string(message.originatingNumber);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.timeoutMs !== undefined) {
      writer.uint32(24).uint64(message.timeoutMs);
    }
    if (message.destinationNumber !== undefined) {
      writer.uint32(34).string(message.destinationNumber);
    }
    if (message.destinationImsi !== undefined) {
      writer.uint32(42).string(message.destinationImsi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendSmsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendSmsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.originatingNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timeoutMs = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.destinationNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.destinationImsi = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendSmsRequest {
    return {
      originatingNumber: isSet(object.originatingNumber)
        ? globalThis.String(object.originatingNumber)
        : isSet(object.originating_number)
        ? globalThis.String(object.originating_number)
        : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      timeoutMs: isSet(object.timeoutMs)
        ? globalThis.Number(object.timeoutMs)
        : isSet(object.timeout_ms)
        ? globalThis.Number(object.timeout_ms)
        : undefined,
      destinationNumber: isSet(object.destinationNumber)
        ? globalThis.String(object.destinationNumber)
        : isSet(object.destination_number)
        ? globalThis.String(object.destination_number)
        : undefined,
      destinationImsi: isSet(object.destinationImsi)
        ? globalThis.String(object.destinationImsi)
        : isSet(object.destination_imsi)
        ? globalThis.String(object.destination_imsi)
        : undefined,
    };
  },

  toJSON(message: SendSmsRequest): unknown {
    const obj: any = {};
    if (message.originatingNumber !== "") {
      obj.originatingNumber = message.originatingNumber;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.timeoutMs !== undefined) {
      obj.timeoutMs = Math.round(message.timeoutMs);
    }
    if (message.destinationNumber !== undefined) {
      obj.destinationNumber = message.destinationNumber;
    }
    if (message.destinationImsi !== undefined) {
      obj.destinationImsi = message.destinationImsi;
    }
    return obj;
  },

  create(base?: DeepPartial<SendSmsRequest>): SendSmsRequest {
    return SendSmsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SendSmsRequest>): SendSmsRequest {
    const message = createBaseSendSmsRequest();
    message.originatingNumber = object.originatingNumber ?? "";
    message.text = object.text ?? "";
    message.timeoutMs = object.timeoutMs ?? undefined;
    message.destinationNumber = object.destinationNumber ?? undefined;
    message.destinationImsi = object.destinationImsi ?? undefined;
    return message;
  },
};

function createBaseSendSmsResponse(): SendSmsResponse {
  return { accepted: false, message: "" };
}

export const SendSmsResponse: MessageFns<SendSmsResponse> = {
  encode(message: SendSmsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accepted !== false) {
      writer.uint32(8).bool(message.accepted);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendSmsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendSmsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accepted = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendSmsResponse {
    return {
      accepted: isSet(object.accepted) ? globalThis.Boolean(object.accepted) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: SendSmsResponse): unknown {
    const obj: any = {};
    if (message.accepted !== false) {
      obj.accepted = message.accepted;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create(base?: DeepPartial<SendSmsResponse>): SendSmsResponse {
    return SendSmsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SendSmsResponse>): SendSmsResponse {
    const message = createBaseSendSmsResponse();
    message.accepted = object.accepted ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

/** MSC management API for mobile-terminated voice, SMS, and call state. */
export type MscManagementServiceDefinition = typeof MscManagementServiceDefinition;
export const MscManagementServiceDefinition = {
  name: "MscManagementService",
  fullName: "msc_management.v1.MscManagementService",
  methods: {
    /** Initiates a mobile-terminated voice call through the BSC and voice gateway. */
    initiateCall: {
      name: "InitiateCall",
      requestType: InitiateCallRequest as typeof InitiateCallRequest,
      requestStream: false,
      responseType: InitiateCallResponse as typeof InitiateCallResponse,
      responseStream: false,
      options: {},
    },
    /** Submits an SMS for mobile-terminated delivery. */
    sendSms: {
      name: "SendSms",
      requestType: SendSmsRequest as typeof SendSmsRequest,
      requestStream: false,
      responseType: SendSmsResponse as typeof SendSmsResponse,
      responseStream: false,
      options: {},
    },
    /** Lists active MSC call IDs. */
    listCalls: {
      name: "ListCalls",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: CallList as typeof CallList,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface MscManagementServiceImplementation<CallContextExt = {}> {
  /** Initiates a mobile-terminated voice call through the BSC and voice gateway. */
  initiateCall(
    request: InitiateCallRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<InitiateCallResponse>>;
  /** Submits an SMS for mobile-terminated delivery. */
  sendSms(request: SendSmsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<SendSmsResponse>>;
  /** Lists active MSC call IDs. */
  listCalls(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<CallList>>;
}

export interface MscManagementServiceClient<CallOptionsExt = {}> {
  /** Initiates a mobile-terminated voice call through the BSC and voice gateway. */
  initiateCall(
    request: DeepPartial<InitiateCallRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<InitiateCallResponse>;
  /** Submits an SMS for mobile-terminated delivery. */
  sendSms(request: DeepPartial<SendSmsRequest>, options?: CallOptions & CallOptionsExt): Promise<SendSmsResponse>;
  /** Lists active MSC call IDs. */
  listCalls(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<CallList>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
