// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: management/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { AccessEvent, PagingEvent, RadioMetrics, SystemStatus, TrafficEvent } from "../../bsc/v1/service";
import { Empty } from "../../google/protobuf/empty";

export const protobufPackage = "management.v1";

/** Health summary for one node participating in the network-in-a-box stack. */
export interface NodeHealth {
  /** Stable node identifier used in logs and management UI. */
  nodeId: string;
  /** Node role such as BTS, BSC, MSC, HLR, SMSC, PCF, or PDSN. */
  nodeType: string;
  /** True when the node is reachable and serving its expected role. */
  healthy: boolean;
  /** Human-readable status or failure reason. */
  message: string;
}

/** Aggregated management snapshot across radio and core services. */
export interface SystemOverview {
  /** Current BSC/BTS radio-access status. */
  bscStatus:
    | SystemStatus
    | undefined;
  /** Health state for each managed node. */
  nodes: NodeHealth[];
}

/** Unified event stream item for the management facade. */
export interface ManagementEvent {
  /** Node identifier that emitted the event. */
  sourceNodeId: string;
  /** Node role that emitted the event. */
  sourceNodeType: string;
  /** Event category used by clients for filtering and display. */
  classification: string;
  /** Radio TX/RX/bearer metrics update. */
  radioMetrics?:
    | RadioMetrics
    | undefined;
  /** Forward paging-channel transmission event. */
  pagingEvent?:
    | PagingEvent
    | undefined;
  /** Reverse access-channel receive event. */
  accessEvent?:
    | AccessEvent
    | undefined;
  /** Forward dedicated traffic-channel transmission event. */
  trafficEvent?:
    | TrafficEvent
    | undefined;
  /** Node health transition or heartbeat. */
  nodeHealth?: NodeHealth | undefined;
}

function createBaseNodeHealth(): NodeHealth {
  return { nodeId: "", nodeType: "", healthy: false, message: "" };
}

export const NodeHealth: MessageFns<NodeHealth> = {
  encode(message: NodeHealth, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.nodeType !== "") {
      writer.uint32(18).string(message.nodeType);
    }
    if (message.healthy !== false) {
      writer.uint32(24).bool(message.healthy);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NodeHealth {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeHealth();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodeType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.healthy = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeHealth {
    return {
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      nodeType: isSet(object.nodeType)
        ? globalThis.String(object.nodeType)
        : isSet(object.node_type)
        ? globalThis.String(object.node_type)
        : "",
      healthy: isSet(object.healthy) ? globalThis.Boolean(object.healthy) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: NodeHealth): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.nodeType !== "") {
      obj.nodeType = message.nodeType;
    }
    if (message.healthy !== false) {
      obj.healthy = message.healthy;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create(base?: DeepPartial<NodeHealth>): NodeHealth {
    return NodeHealth.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NodeHealth>): NodeHealth {
    const message = createBaseNodeHealth();
    message.nodeId = object.nodeId ?? "";
    message.nodeType = object.nodeType ?? "";
    message.healthy = object.healthy ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseSystemOverview(): SystemOverview {
  return { bscStatus: undefined, nodes: [] };
}

export const SystemOverview: MessageFns<SystemOverview> = {
  encode(message: SystemOverview, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bscStatus !== undefined) {
      SystemStatus.encode(message.bscStatus, writer.uint32(10).fork()).join();
    }
    for (const v of message.nodes) {
      NodeHealth.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SystemOverview {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSystemOverview();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bscStatus = SystemStatus.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodes.push(NodeHealth.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SystemOverview {
    return {
      bscStatus: isSet(object.bscStatus)
        ? SystemStatus.fromJSON(object.bscStatus)
        : isSet(object.bsc_status)
        ? SystemStatus.fromJSON(object.bsc_status)
        : undefined,
      nodes: globalThis.Array.isArray(object?.nodes) ? object.nodes.map((e: any) => NodeHealth.fromJSON(e)) : [],
    };
  },

  toJSON(message: SystemOverview): unknown {
    const obj: any = {};
    if (message.bscStatus !== undefined) {
      obj.bscStatus = SystemStatus.toJSON(message.bscStatus);
    }
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => NodeHealth.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<SystemOverview>): SystemOverview {
    return SystemOverview.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SystemOverview>): SystemOverview {
    const message = createBaseSystemOverview();
    message.bscStatus = (object.bscStatus !== undefined && object.bscStatus !== null)
      ? SystemStatus.fromPartial(object.bscStatus)
      : undefined;
    message.nodes = object.nodes?.map((e) => NodeHealth.fromPartial(e)) || [];
    return message;
  },
};

function createBaseManagementEvent(): ManagementEvent {
  return {
    sourceNodeId: "",
    sourceNodeType: "",
    classification: "",
    radioMetrics: undefined,
    pagingEvent: undefined,
    accessEvent: undefined,
    trafficEvent: undefined,
    nodeHealth: undefined,
  };
}

export const ManagementEvent: MessageFns<ManagementEvent> = {
  encode(message: ManagementEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sourceNodeId !== "") {
      writer.uint32(10).string(message.sourceNodeId);
    }
    if (message.sourceNodeType !== "") {
      writer.uint32(18).string(message.sourceNodeType);
    }
    if (message.classification !== "") {
      writer.uint32(26).string(message.classification);
    }
    if (message.radioMetrics !== undefined) {
      RadioMetrics.encode(message.radioMetrics, writer.uint32(82).fork()).join();
    }
    if (message.pagingEvent !== undefined) {
      PagingEvent.encode(message.pagingEvent, writer.uint32(90).fork()).join();
    }
    if (message.accessEvent !== undefined) {
      AccessEvent.encode(message.accessEvent, writer.uint32(98).fork()).join();
    }
    if (message.trafficEvent !== undefined) {
      TrafficEvent.encode(message.trafficEvent, writer.uint32(106).fork()).join();
    }
    if (message.nodeHealth !== undefined) {
      NodeHealth.encode(message.nodeHealth, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ManagementEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseManagementEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sourceNodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceNodeType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.classification = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.radioMetrics = RadioMetrics.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.pagingEvent = PagingEvent.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.accessEvent = AccessEvent.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.trafficEvent = TrafficEvent.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.nodeHealth = NodeHealth.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ManagementEvent {
    return {
      sourceNodeId: isSet(object.sourceNodeId)
        ? globalThis.String(object.sourceNodeId)
        : isSet(object.source_node_id)
        ? globalThis.String(object.source_node_id)
        : "",
      sourceNodeType: isSet(object.sourceNodeType)
        ? globalThis.String(object.sourceNodeType)
        : isSet(object.source_node_type)
        ? globalThis.String(object.source_node_type)
        : "",
      classification: isSet(object.classification) ? globalThis.String(object.classification) : "",
      radioMetrics: isSet(object.radioMetrics)
        ? RadioMetrics.fromJSON(object.radioMetrics)
        : isSet(object.radio_metrics)
        ? RadioMetrics.fromJSON(object.radio_metrics)
        : undefined,
      pagingEvent: isSet(object.pagingEvent)
        ? PagingEvent.fromJSON(object.pagingEvent)
        : isSet(object.paging_event)
        ? PagingEvent.fromJSON(object.paging_event)
        : undefined,
      accessEvent: isSet(object.accessEvent)
        ? AccessEvent.fromJSON(object.accessEvent)
        : isSet(object.access_event)
        ? AccessEvent.fromJSON(object.access_event)
        : undefined,
      trafficEvent: isSet(object.trafficEvent)
        ? TrafficEvent.fromJSON(object.trafficEvent)
        : isSet(object.traffic_event)
        ? TrafficEvent.fromJSON(object.traffic_event)
        : undefined,
      nodeHealth: isSet(object.nodeHealth)
        ? NodeHealth.fromJSON(object.nodeHealth)
        : isSet(object.node_health)
        ? NodeHealth.fromJSON(object.node_health)
        : undefined,
    };
  },

  toJSON(message: ManagementEvent): unknown {
    const obj: any = {};
    if (message.sourceNodeId !== "") {
      obj.sourceNodeId = message.sourceNodeId;
    }
    if (message.sourceNodeType !== "") {
      obj.sourceNodeType = message.sourceNodeType;
    }
    if (message.classification !== "") {
      obj.classification = message.classification;
    }
    if (message.radioMetrics !== undefined) {
      obj.radioMetrics = RadioMetrics.toJSON(message.radioMetrics);
    }
    if (message.pagingEvent !== undefined) {
      obj.pagingEvent = PagingEvent.toJSON(message.pagingEvent);
    }
    if (message.accessEvent !== undefined) {
      obj.accessEvent = AccessEvent.toJSON(message.accessEvent);
    }
    if (message.trafficEvent !== undefined) {
      obj.trafficEvent = TrafficEvent.toJSON(message.trafficEvent);
    }
    if (message.nodeHealth !== undefined) {
      obj.nodeHealth = NodeHealth.toJSON(message.nodeHealth);
    }
    return obj;
  },

  create(base?: DeepPartial<ManagementEvent>): ManagementEvent {
    return ManagementEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ManagementEvent>): ManagementEvent {
    const message = createBaseManagementEvent();
    message.sourceNodeId = object.sourceNodeId ?? "";
    message.sourceNodeType = object.sourceNodeType ?? "";
    message.classification = object.classification ?? "";
    message.radioMetrics = (object.radioMetrics !== undefined && object.radioMetrics !== null)
      ? RadioMetrics.fromPartial(object.radioMetrics)
      : undefined;
    message.pagingEvent = (object.pagingEvent !== undefined && object.pagingEvent !== null)
      ? PagingEvent.fromPartial(object.pagingEvent)
      : undefined;
    message.accessEvent = (object.accessEvent !== undefined && object.accessEvent !== null)
      ? AccessEvent.fromPartial(object.accessEvent)
      : undefined;
    message.trafficEvent = (object.trafficEvent !== undefined && object.trafficEvent !== null)
      ? TrafficEvent.fromPartial(object.trafficEvent)
      : undefined;
    message.nodeHealth = (object.nodeHealth !== undefined && object.nodeHealth !== null)
      ? NodeHealth.fromPartial(object.nodeHealth)
      : undefined;
    return message;
  },
};

/** Facade service for clients that want a single management endpoint for the stack. */
export type ManagementFacadeServiceDefinition = typeof ManagementFacadeServiceDefinition;
export const ManagementFacadeServiceDefinition = {
  name: "ManagementFacadeService",
  fullName: "management.v1.ManagementFacadeService",
  methods: {
    /** Returns a point-in-time status summary for all managed services. */
    getSystemOverview: {
      name: "GetSystemOverview",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: SystemOverview as typeof SystemOverview,
      responseStream: false,
      options: {},
    },
    /** Streams cross-node radio, paging, access, traffic, and health events. */
    streamSystemEvents: {
      name: "StreamSystemEvents",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: ManagementEvent as typeof ManagementEvent,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface ManagementFacadeServiceImplementation<CallContextExt = {}> {
  /** Returns a point-in-time status summary for all managed services. */
  getSystemOverview(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<SystemOverview>>;
  /** Streams cross-node radio, paging, access, traffic, and health events. */
  streamSystemEvents(
    request: Empty,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<ManagementEvent>>;
}

export interface ManagementFacadeServiceClient<CallOptionsExt = {}> {
  /** Returns a point-in-time status summary for all managed services. */
  getSystemOverview(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<SystemOverview>;
  /** Streams cross-node radio, paging, access, traffic, and health events. */
  streamSystemEvents(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<ManagementEvent>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
