// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: mgmt/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import {
  GetSessionEventsRequest,
  GetSessionEventsResponse,
  GetSessionRequest,
  GetSessionResponse,
  GetSessionsRequest,
  GetSessionsResponse,
  GetUatiAllocationRequest,
  GetUatiAllocationResponse,
} from "../../an/v1/service";
import {
  AccessEvent,
  BtsConfig,
  ChannelList,
  InitiateDataCallRequest,
  InitiateDataCallResponse,
  IqCaptureStatus,
  MobileList,
  PagingEvent,
  RadioMetrics,
  SetTrafficChannelPowerOverrideRequest,
  SetTrafficChannelPowerOverrideResponse,
  SystemStatus,
  TrafficChannelPower,
  TrafficEvent,
} from "../../bsc/v1/service";
import {
  BtsList,
  CellRequest,
  ReversePowerControlList,
  ReversePowerControlRequest,
} from "../../bts_management/v1/service";
import { Empty } from "../../google/protobuf/empty";
import { ManagementEvent } from "../../management/v1/service";
import { GetSessionByIpResponse, GetSessionStatusResponse, SetSessionCaptureResponse } from "../../packet/v1/service";
import { GetPcfSessionRequest, PcfSessionList } from "../../pcf_management/v1/service";
import {
  GetPdsnSessionByIpRequest,
  GetPdsnSessionRequest,
  PdsnSessionList,
  SetPacketTraceCaptureRequest,
} from "../../pdsn_management/v1/service";

export const protobufPackage = "mgmt.v1";

/**
 * Names one base station (a BSC) by its stable config id, from
 * `base_stations[].id` in the MSC config (default: the management endpoint).
 */
export interface BsSelector {
  baseStation: string;
}

/** A method scoped to one base station with no further arguments. */
export interface BsRequest {
  selector: BsSelector | undefined;
}

/** A method scoped to one base station and, within it, one cell. */
export interface CellScopedRequest {
  selector: BsSelector | undefined;
  request: CellRequest | undefined;
}

/** A method scoped to one base station and one traffic Walsh code on one cell. */
export interface ReversePowerControlScopedRequest {
  selector: BsSelector | undefined;
  request: ReversePowerControlRequest | undefined;
}

/** A power-control override scoped to one base station. */
export interface PowerOverrideScopedRequest {
  selector: BsSelector | undefined;
  request: SetTrafficChannelPowerOverrideRequest | undefined;
}

/** A data-call initiation scoped to one base station. */
export interface InitiateDataCallScopedRequest {
  selector: BsSelector | undefined;
  request: InitiateDataCallRequest | undefined;
}

/** An HRPD access-network session list scoped to one cell. */
export interface AnSessionsScopedRequest {
  selector: BsSelector | undefined;
  cell: CellRequest | undefined;
  request: GetSessionsRequest | undefined;
}

/** An HRPD access-network single-session lookup scoped to one cell. */
export interface AnSessionScopedRequest {
  selector: BsSelector | undefined;
  cell: CellRequest | undefined;
  request: GetSessionRequest | undefined;
}

/** An HRPD UATI-allocation inspection scoped to one cell. */
export interface AnUatiAllocationScopedRequest {
  selector: BsSelector | undefined;
  cell: CellRequest | undefined;
  request: GetUatiAllocationRequest | undefined;
}

/** An HRPD session-event history request scoped to one cell. */
export interface AnSessionEventsScopedRequest {
  selector: BsSelector | undefined;
  cell: CellRequest | undefined;
  request: GetSessionEventsRequest | undefined;
}

function createBaseBsSelector(): BsSelector {
  return { baseStation: "" };
}

export const BsSelector: MessageFns<BsSelector> = {
  encode(message: BsSelector, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baseStation !== "") {
      writer.uint32(10).string(message.baseStation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BsSelector {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBsSelector();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.baseStation = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BsSelector {
    return {
      baseStation: isSet(object.baseStation)
        ? globalThis.String(object.baseStation)
        : isSet(object.base_station)
        ? globalThis.String(object.base_station)
        : "",
    };
  },

  toJSON(message: BsSelector): unknown {
    const obj: any = {};
    if (message.baseStation !== "") {
      obj.baseStation = message.baseStation;
    }
    return obj;
  },

  create(base?: DeepPartial<BsSelector>): BsSelector {
    return BsSelector.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BsSelector>): BsSelector {
    const message = createBaseBsSelector();
    message.baseStation = object.baseStation ?? "";
    return message;
  },
};

function createBaseBsRequest(): BsRequest {
  return { selector: undefined };
}

export const BsRequest: MessageFns<BsRequest> = {
  encode(message: BsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BsRequest {
    return { selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined };
  },

  toJSON(message: BsRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    return obj;
  },

  create(base?: DeepPartial<BsRequest>): BsRequest {
    return BsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BsRequest>): BsRequest {
    const message = createBaseBsRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    return message;
  },
};

function createBaseCellScopedRequest(): CellScopedRequest {
  return { selector: undefined, request: undefined };
}

export const CellScopedRequest: MessageFns<CellScopedRequest> = {
  encode(message: CellScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.request !== undefined) {
      CellRequest.encode(message.request, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CellScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCellScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request = CellRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CellScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      request: isSet(object.request) ? CellRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: CellScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.request !== undefined) {
      obj.request = CellRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<CellScopedRequest>): CellScopedRequest {
    return CellScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CellScopedRequest>): CellScopedRequest {
    const message = createBaseCellScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? CellRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseReversePowerControlScopedRequest(): ReversePowerControlScopedRequest {
  return { selector: undefined, request: undefined };
}

export const ReversePowerControlScopedRequest: MessageFns<ReversePowerControlScopedRequest> = {
  encode(message: ReversePowerControlScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.request !== undefined) {
      ReversePowerControlRequest.encode(message.request, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReversePowerControlScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReversePowerControlScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request = ReversePowerControlRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReversePowerControlScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      request: isSet(object.request) ? ReversePowerControlRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: ReversePowerControlScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.request !== undefined) {
      obj.request = ReversePowerControlRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<ReversePowerControlScopedRequest>): ReversePowerControlScopedRequest {
    return ReversePowerControlScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReversePowerControlScopedRequest>): ReversePowerControlScopedRequest {
    const message = createBaseReversePowerControlScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? ReversePowerControlRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBasePowerOverrideScopedRequest(): PowerOverrideScopedRequest {
  return { selector: undefined, request: undefined };
}

export const PowerOverrideScopedRequest: MessageFns<PowerOverrideScopedRequest> = {
  encode(message: PowerOverrideScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.request !== undefined) {
      SetTrafficChannelPowerOverrideRequest.encode(message.request, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PowerOverrideScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePowerOverrideScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request = SetTrafficChannelPowerOverrideRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PowerOverrideScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      request: isSet(object.request) ? SetTrafficChannelPowerOverrideRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: PowerOverrideScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.request !== undefined) {
      obj.request = SetTrafficChannelPowerOverrideRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<PowerOverrideScopedRequest>): PowerOverrideScopedRequest {
    return PowerOverrideScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PowerOverrideScopedRequest>): PowerOverrideScopedRequest {
    const message = createBasePowerOverrideScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? SetTrafficChannelPowerOverrideRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseInitiateDataCallScopedRequest(): InitiateDataCallScopedRequest {
  return { selector: undefined, request: undefined };
}

export const InitiateDataCallScopedRequest: MessageFns<InitiateDataCallScopedRequest> = {
  encode(message: InitiateDataCallScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.request !== undefined) {
      InitiateDataCallRequest.encode(message.request, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InitiateDataCallScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInitiateDataCallScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request = InitiateDataCallRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InitiateDataCallScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      request: isSet(object.request) ? InitiateDataCallRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: InitiateDataCallScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.request !== undefined) {
      obj.request = InitiateDataCallRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<InitiateDataCallScopedRequest>): InitiateDataCallScopedRequest {
    return InitiateDataCallScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<InitiateDataCallScopedRequest>): InitiateDataCallScopedRequest {
    const message = createBaseInitiateDataCallScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? InitiateDataCallRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseAnSessionsScopedRequest(): AnSessionsScopedRequest {
  return { selector: undefined, cell: undefined, request: undefined };
}

export const AnSessionsScopedRequest: MessageFns<AnSessionsScopedRequest> = {
  encode(message: AnSessionsScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.cell !== undefined) {
      CellRequest.encode(message.cell, writer.uint32(18).fork()).join();
    }
    if (message.request !== undefined) {
      GetSessionsRequest.encode(message.request, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnSessionsScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnSessionsScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cell = CellRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.request = GetSessionsRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnSessionsScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      cell: isSet(object.cell) ? CellRequest.fromJSON(object.cell) : undefined,
      request: isSet(object.request) ? GetSessionsRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: AnSessionsScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.cell !== undefined) {
      obj.cell = CellRequest.toJSON(message.cell);
    }
    if (message.request !== undefined) {
      obj.request = GetSessionsRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<AnSessionsScopedRequest>): AnSessionsScopedRequest {
    return AnSessionsScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnSessionsScopedRequest>): AnSessionsScopedRequest {
    const message = createBaseAnSessionsScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.cell = (object.cell !== undefined && object.cell !== null)
      ? CellRequest.fromPartial(object.cell)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? GetSessionsRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseAnSessionScopedRequest(): AnSessionScopedRequest {
  return { selector: undefined, cell: undefined, request: undefined };
}

export const AnSessionScopedRequest: MessageFns<AnSessionScopedRequest> = {
  encode(message: AnSessionScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.cell !== undefined) {
      CellRequest.encode(message.cell, writer.uint32(18).fork()).join();
    }
    if (message.request !== undefined) {
      GetSessionRequest.encode(message.request, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnSessionScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnSessionScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cell = CellRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.request = GetSessionRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnSessionScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      cell: isSet(object.cell) ? CellRequest.fromJSON(object.cell) : undefined,
      request: isSet(object.request) ? GetSessionRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: AnSessionScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.cell !== undefined) {
      obj.cell = CellRequest.toJSON(message.cell);
    }
    if (message.request !== undefined) {
      obj.request = GetSessionRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<AnSessionScopedRequest>): AnSessionScopedRequest {
    return AnSessionScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnSessionScopedRequest>): AnSessionScopedRequest {
    const message = createBaseAnSessionScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.cell = (object.cell !== undefined && object.cell !== null)
      ? CellRequest.fromPartial(object.cell)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? GetSessionRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseAnUatiAllocationScopedRequest(): AnUatiAllocationScopedRequest {
  return { selector: undefined, cell: undefined, request: undefined };
}

export const AnUatiAllocationScopedRequest: MessageFns<AnUatiAllocationScopedRequest> = {
  encode(message: AnUatiAllocationScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.cell !== undefined) {
      CellRequest.encode(message.cell, writer.uint32(18).fork()).join();
    }
    if (message.request !== undefined) {
      GetUatiAllocationRequest.encode(message.request, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnUatiAllocationScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnUatiAllocationScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cell = CellRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.request = GetUatiAllocationRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnUatiAllocationScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      cell: isSet(object.cell) ? CellRequest.fromJSON(object.cell) : undefined,
      request: isSet(object.request) ? GetUatiAllocationRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: AnUatiAllocationScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.cell !== undefined) {
      obj.cell = CellRequest.toJSON(message.cell);
    }
    if (message.request !== undefined) {
      obj.request = GetUatiAllocationRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<AnUatiAllocationScopedRequest>): AnUatiAllocationScopedRequest {
    return AnUatiAllocationScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnUatiAllocationScopedRequest>): AnUatiAllocationScopedRequest {
    const message = createBaseAnUatiAllocationScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.cell = (object.cell !== undefined && object.cell !== null)
      ? CellRequest.fromPartial(object.cell)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? GetUatiAllocationRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseAnSessionEventsScopedRequest(): AnSessionEventsScopedRequest {
  return { selector: undefined, cell: undefined, request: undefined };
}

export const AnSessionEventsScopedRequest: MessageFns<AnSessionEventsScopedRequest> = {
  encode(message: AnSessionEventsScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selector !== undefined) {
      BsSelector.encode(message.selector, writer.uint32(10).fork()).join();
    }
    if (message.cell !== undefined) {
      CellRequest.encode(message.cell, writer.uint32(18).fork()).join();
    }
    if (message.request !== undefined) {
      GetSessionEventsRequest.encode(message.request, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnSessionEventsScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnSessionEventsScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.selector = BsSelector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cell = CellRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.request = GetSessionEventsRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnSessionEventsScopedRequest {
    return {
      selector: isSet(object.selector) ? BsSelector.fromJSON(object.selector) : undefined,
      cell: isSet(object.cell) ? CellRequest.fromJSON(object.cell) : undefined,
      request: isSet(object.request) ? GetSessionEventsRequest.fromJSON(object.request) : undefined,
    };
  },

  toJSON(message: AnSessionEventsScopedRequest): unknown {
    const obj: any = {};
    if (message.selector !== undefined) {
      obj.selector = BsSelector.toJSON(message.selector);
    }
    if (message.cell !== undefined) {
      obj.cell = CellRequest.toJSON(message.cell);
    }
    if (message.request !== undefined) {
      obj.request = GetSessionEventsRequest.toJSON(message.request);
    }
    return obj;
  },

  create(base?: DeepPartial<AnSessionEventsScopedRequest>): AnSessionEventsScopedRequest {
    return AnSessionEventsScopedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnSessionEventsScopedRequest>): AnSessionEventsScopedRequest {
    const message = createBaseAnSessionEventsScopedRequest();
    message.selector = (object.selector !== undefined && object.selector !== null)
      ? BsSelector.fromPartial(object.selector)
      : undefined;
    message.cell = (object.cell !== undefined && object.cell !== null)
      ? CellRequest.fromPartial(object.cell)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? GetSessionEventsRequest.fromPartial(object.request)
      : undefined;
    return message;
  },
};

/**
 * Single management interface for the whole network.
 *
 * The web dials only this service. It has three families:
 *
 *   - Per-selector proxy: a `BsSelector` names one base station (a BSC) and
 *     the call is forwarded to that BSC's BtsManagement/BscManagement, or to
 *     one of its cells' HRPD access networks. The response (or stream) is
 *     returned unchanged.
 *   - Global interface: the PCF and PDSN are single core elements, so their
 *     management methods take no selector and forward to the one packet core.
 *   - Aggregation: methods that fan out to every base station and merge, for
 *     views that span the whole network.
 *
 * The implementation lives in one module so it can later move into a
 * standalone management-plane gateway without touching the wire contract.
 */
export type NetworkManagementServiceDefinition = typeof NetworkManagementServiceDefinition;
export const NetworkManagementServiceDefinition = {
  name: "NetworkManagementService",
  fullName: "mgmt.v1.NetworkManagementService",
  methods: {
    /** Lists the cells of one base station. */
    listBts: {
      name: "ListBts",
      requestType: BsRequest as typeof BsRequest,
      requestStream: false,
      responseType: BtsList as typeof BtsList,
      responseStream: false,
      options: {},
    },
    /** Returns runtime status for one cell. */
    getBtsStatus: {
      name: "GetBtsStatus",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: SystemStatus as typeof SystemStatus,
      responseStream: false,
      options: {},
    },
    /** Returns the active radio and overhead configuration for one cell. */
    getBtsConfig: {
      name: "GetBtsConfig",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: BtsConfig as typeof BtsConfig,
      responseStream: false,
      options: {},
    },
    /** Returns the latest radio metrics snapshot for one cell. */
    getRadioMetrics: {
      name: "GetRadioMetrics",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: RadioMetrics as typeof RadioMetrics,
      responseStream: false,
      options: {},
    },
    /** Streams radio metrics for one cell. */
    streamRadioMetrics: {
      name: "StreamRadioMetrics",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: RadioMetrics as typeof RadioMetrics,
      responseStream: true,
      options: {},
    },
    /** Returns IQ capture state for one cell. */
    getIqCaptureStatus: {
      name: "GetIqCaptureStatus",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: IqCaptureStatus as typeof IqCaptureStatus,
      responseStream: false,
      options: {},
    },
    /** Starts an IQ capture on one cell. */
    startIqCapture: {
      name: "StartIqCapture",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: IqCaptureStatus as typeof IqCaptureStatus,
      responseStream: false,
      options: {},
    },
    /** Stops the active IQ capture on one cell. */
    stopIqCapture: {
      name: "StopIqCapture",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: IqCaptureStatus as typeof IqCaptureStatus,
      responseStream: false,
      options: {},
    },
    /** Lists local radio resources for one cell. */
    listLocalRadioResources: {
      name: "ListLocalRadioResources",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: ChannelList as typeof ChannelList,
      responseStream: false,
      options: {},
    },
    /** Returns reverse power-control state for one traffic Walsh code on one cell. */
    getReversePowerControl: {
      name: "GetReversePowerControl",
      requestType: ReversePowerControlScopedRequest as typeof ReversePowerControlScopedRequest,
      requestStream: false,
      responseType: TrafficChannelPower as typeof TrafficChannelPower,
      responseStream: false,
      options: {},
    },
    /** Lists reverse power-control state for one cell. */
    listReversePowerControls: {
      name: "ListReversePowerControls",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: ReversePowerControlList as typeof ReversePowerControlList,
      responseStream: false,
      options: {},
    },
    /** Applies or clears a reverse power-control override on one cell. */
    setReversePowerControlOverride: {
      name: "SetReversePowerControlOverride",
      requestType: PowerOverrideScopedRequest as typeof PowerOverrideScopedRequest,
      requestStream: false,
      responseType: SetTrafficChannelPowerOverrideResponse as typeof SetTrafficChannelPowerOverrideResponse,
      responseStream: false,
      options: {},
    },
    /** Streams paging-channel transmissions from one cell. */
    streamPchTransmissions: {
      name: "StreamPchTransmissions",
      requestType: CellScopedRequest as typeof CellScopedRequest,
      requestStream: false,
      responseType: PagingEvent as typeof PagingEvent,
      responseStream: true,
      options: {},
    },
    /** Returns serving status for one base station. */
    getBscStatus: {
      name: "GetBscStatus",
      requestType: BsRequest as typeof BsRequest,
      requestStream: false,
      responseType: SystemStatus as typeof SystemStatus,
      responseStream: false,
      options: {},
    },
    /** Lists mobiles on one base station. */
    listMobiles: {
      name: "ListMobiles",
      requestType: BsRequest as typeof BsRequest,
      requestStream: false,
      responseType: MobileList as typeof MobileList,
      responseStream: false,
      options: {},
    },
    /** Lists channels on one base station. */
    listChannels: {
      name: "ListChannels",
      requestType: BsRequest as typeof BsRequest,
      requestStream: false,
      responseType: ChannelList as typeof ChannelList,
      responseStream: false,
      options: {},
    },
    /** Streams reverse access-channel events from one base station. */
    streamAccessEvents: {
      name: "StreamAccessEvents",
      requestType: BsRequest as typeof BsRequest,
      requestStream: false,
      responseType: AccessEvent as typeof AccessEvent,
      responseStream: true,
      options: {},
    },
    /** Streams paging-channel transmissions from one base station. */
    streamPagingEvents: {
      name: "StreamPagingEvents",
      requestType: BsRequest as typeof BsRequest,
      requestStream: false,
      responseType: PagingEvent as typeof PagingEvent,
      responseStream: true,
      options: {},
    },
    /** Streams traffic-channel transmissions from one base station. */
    streamTrafficEvents: {
      name: "StreamTrafficEvents",
      requestType: BsRequest as typeof BsRequest,
      requestStream: false,
      responseType: TrafficEvent as typeof TrafficEvent,
      responseStream: true,
      options: {},
    },
    /**
     * Applies or clears a reverse power-control override, resolved by the base
     * station across its cells.
     */
    setTrafficChannelPowerOverride: {
      name: "SetTrafficChannelPowerOverride",
      requestType: PowerOverrideScopedRequest as typeof PowerOverrideScopedRequest,
      requestStream: false,
      responseType: SetTrafficChannelPowerOverrideResponse as typeof SetTrafficChannelPowerOverrideResponse,
      responseStream: false,
      options: {},
    },
    /** Lists HRPD sessions on one cell's access network. */
    getAnSessions: {
      name: "GetAnSessions",
      requestType: AnSessionsScopedRequest as typeof AnSessionsScopedRequest,
      requestStream: false,
      responseType: GetSessionsResponse as typeof GetSessionsResponse,
      responseStream: false,
      options: {},
    },
    /** Fetches one HRPD session by UATI on one cell's access network. */
    getAnSession: {
      name: "GetAnSession",
      requestType: AnSessionScopedRequest as typeof AnSessionScopedRequest,
      requestStream: false,
      responseType: GetSessionResponse as typeof GetSessionResponse,
      responseStream: false,
      options: {},
    },
    /** Inspects UATI allocation on one cell's access network. */
    getAnUatiAllocation: {
      name: "GetAnUatiAllocation",
      requestType: AnUatiAllocationScopedRequest as typeof AnUatiAllocationScopedRequest,
      requestStream: false,
      responseType: GetUatiAllocationResponse as typeof GetUatiAllocationResponse,
      responseStream: false,
      options: {},
    },
    /** Returns buffered HRPD session events for one UATI on one cell. */
    getAnSessionEvents: {
      name: "GetAnSessionEvents",
      requestType: AnSessionEventsScopedRequest as typeof AnSessionEventsScopedRequest,
      requestStream: false,
      responseType: GetSessionEventsResponse as typeof GetSessionEventsResponse,
      responseStream: false,
      options: {},
    },
    /**
     * Initiates a data call by paging the mobile and requesting packet service
     * on the named base station.
     */
    initiateDataCall: {
      name: "InitiateDataCall",
      requestType: InitiateDataCallScopedRequest as typeof InitiateDataCallScopedRequest,
      requestStream: false,
      responseType: InitiateDataCallResponse as typeof InitiateDataCallResponse,
      responseStream: false,
      options: {},
    },
    /** Lists packet sessions known by the PCF. */
    listPcfSessions: {
      name: "ListPcfSessions",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: PcfSessionList as typeof PcfSessionList,
      responseStream: false,
      options: {},
    },
    /** Returns detailed status for one PCF packet session. */
    getPcfSession: {
      name: "GetPcfSession",
      requestType: GetPcfSessionRequest as typeof GetPcfSessionRequest,
      requestStream: false,
      responseType: GetSessionStatusResponse as typeof GetSessionStatusResponse,
      responseStream: false,
      options: {},
    },
    /** Lists packet sessions known by the PDSN. */
    listPdsnSessions: {
      name: "ListPdsnSessions",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: PdsnSessionList as typeof PdsnSessionList,
      responseStream: false,
      options: {},
    },
    /** Returns detailed status for one PDSN packet session. */
    getPdsnSession: {
      name: "GetPdsnSession",
      requestType: GetPdsnSessionRequest as typeof GetPdsnSessionRequest,
      requestStream: false,
      responseType: GetSessionStatusResponse as typeof GetSessionStatusResponse,
      responseStream: false,
      options: {},
    },
    /** Looks up one active packet session by its assigned mobile IP. */
    getPdsnSessionByIp: {
      name: "GetPdsnSessionByIp",
      requestType: GetPdsnSessionByIpRequest as typeof GetPdsnSessionByIpRequest,
      requestStream: false,
      responseType: GetSessionByIpResponse as typeof GetSessionByIpResponse,
      responseStream: false,
      options: {},
    },
    /** Enables or disables trace capture on one PDSN packet session. */
    setPacketTraceCapture: {
      name: "SetPacketTraceCapture",
      requestType: SetPacketTraceCaptureRequest as typeof SetPacketTraceCaptureRequest,
      requestStream: false,
      responseType: SetSessionCaptureResponse as typeof SetSessionCaptureResponse,
      responseStream: false,
      options: {},
    },
    /** Lists mobiles across every base station. */
    listAllMobiles: {
      name: "ListAllMobiles",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: MobileList as typeof MobileList,
      responseStream: false,
      options: {},
    },
    /** Lists channels across every base station. */
    listAllChannels: {
      name: "ListAllChannels",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: ChannelList as typeof ChannelList,
      responseStream: false,
      options: {},
    },
    /**
     * Streams radio, paging, access, traffic, and health events merged across
     * every base station.
     */
    streamSystemEvents: {
      name: "StreamSystemEvents",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: ManagementEvent as typeof ManagementEvent,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface NetworkManagementServiceImplementation<CallContextExt = {}> {
  /** Lists the cells of one base station. */
  listBts(request: BsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<BtsList>>;
  /** Returns runtime status for one cell. */
  getBtsStatus(request: CellScopedRequest, context: CallContext & CallContextExt): Promise<DeepPartial<SystemStatus>>;
  /** Returns the active radio and overhead configuration for one cell. */
  getBtsConfig(request: CellScopedRequest, context: CallContext & CallContextExt): Promise<DeepPartial<BtsConfig>>;
  /** Returns the latest radio metrics snapshot for one cell. */
  getRadioMetrics(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RadioMetrics>>;
  /** Streams radio metrics for one cell. */
  streamRadioMetrics(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<RadioMetrics>>;
  /** Returns IQ capture state for one cell. */
  getIqCaptureStatus(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<IqCaptureStatus>>;
  /** Starts an IQ capture on one cell. */
  startIqCapture(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<IqCaptureStatus>>;
  /** Stops the active IQ capture on one cell. */
  stopIqCapture(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<IqCaptureStatus>>;
  /** Lists local radio resources for one cell. */
  listLocalRadioResources(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ChannelList>>;
  /** Returns reverse power-control state for one traffic Walsh code on one cell. */
  getReversePowerControl(
    request: ReversePowerControlScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<TrafficChannelPower>>;
  /** Lists reverse power-control state for one cell. */
  listReversePowerControls(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ReversePowerControlList>>;
  /** Applies or clears a reverse power-control override on one cell. */
  setReversePowerControlOverride(
    request: PowerOverrideScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetTrafficChannelPowerOverrideResponse>>;
  /** Streams paging-channel transmissions from one cell. */
  streamPchTransmissions(
    request: CellScopedRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<PagingEvent>>;
  /** Returns serving status for one base station. */
  getBscStatus(request: BsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<SystemStatus>>;
  /** Lists mobiles on one base station. */
  listMobiles(request: BsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<MobileList>>;
  /** Lists channels on one base station. */
  listChannels(request: BsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<ChannelList>>;
  /** Streams reverse access-channel events from one base station. */
  streamAccessEvents(
    request: BsRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<AccessEvent>>;
  /** Streams paging-channel transmissions from one base station. */
  streamPagingEvents(
    request: BsRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<PagingEvent>>;
  /** Streams traffic-channel transmissions from one base station. */
  streamTrafficEvents(
    request: BsRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<TrafficEvent>>;
  /**
   * Applies or clears a reverse power-control override, resolved by the base
   * station across its cells.
   */
  setTrafficChannelPowerOverride(
    request: PowerOverrideScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetTrafficChannelPowerOverrideResponse>>;
  /** Lists HRPD sessions on one cell's access network. */
  getAnSessions(
    request: AnSessionsScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionsResponse>>;
  /** Fetches one HRPD session by UATI on one cell's access network. */
  getAnSession(
    request: AnSessionScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionResponse>>;
  /** Inspects UATI allocation on one cell's access network. */
  getAnUatiAllocation(
    request: AnUatiAllocationScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetUatiAllocationResponse>>;
  /** Returns buffered HRPD session events for one UATI on one cell. */
  getAnSessionEvents(
    request: AnSessionEventsScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionEventsResponse>>;
  /**
   * Initiates a data call by paging the mobile and requesting packet service
   * on the named base station.
   */
  initiateDataCall(
    request: InitiateDataCallScopedRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<InitiateDataCallResponse>>;
  /** Lists packet sessions known by the PCF. */
  listPcfSessions(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<PcfSessionList>>;
  /** Returns detailed status for one PCF packet session. */
  getPcfSession(
    request: GetPcfSessionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionStatusResponse>>;
  /** Lists packet sessions known by the PDSN. */
  listPdsnSessions(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<PdsnSessionList>>;
  /** Returns detailed status for one PDSN packet session. */
  getPdsnSession(
    request: GetPdsnSessionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionStatusResponse>>;
  /** Looks up one active packet session by its assigned mobile IP. */
  getPdsnSessionByIp(
    request: GetPdsnSessionByIpRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionByIpResponse>>;
  /** Enables or disables trace capture on one PDSN packet session. */
  setPacketTraceCapture(
    request: SetPacketTraceCaptureRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetSessionCaptureResponse>>;
  /** Lists mobiles across every base station. */
  listAllMobiles(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<MobileList>>;
  /** Lists channels across every base station. */
  listAllChannels(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<ChannelList>>;
  /**
   * Streams radio, paging, access, traffic, and health events merged across
   * every base station.
   */
  streamSystemEvents(
    request: Empty,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<ManagementEvent>>;
}

export interface NetworkManagementServiceClient<CallOptionsExt = {}> {
  /** Lists the cells of one base station. */
  listBts(request: DeepPartial<BsRequest>, options?: CallOptions & CallOptionsExt): Promise<BtsList>;
  /** Returns runtime status for one cell. */
  getBtsStatus(request: DeepPartial<CellScopedRequest>, options?: CallOptions & CallOptionsExt): Promise<SystemStatus>;
  /** Returns the active radio and overhead configuration for one cell. */
  getBtsConfig(request: DeepPartial<CellScopedRequest>, options?: CallOptions & CallOptionsExt): Promise<BtsConfig>;
  /** Returns the latest radio metrics snapshot for one cell. */
  getRadioMetrics(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RadioMetrics>;
  /** Streams radio metrics for one cell. */
  streamRadioMetrics(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<RadioMetrics>;
  /** Returns IQ capture state for one cell. */
  getIqCaptureStatus(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<IqCaptureStatus>;
  /** Starts an IQ capture on one cell. */
  startIqCapture(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<IqCaptureStatus>;
  /** Stops the active IQ capture on one cell. */
  stopIqCapture(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<IqCaptureStatus>;
  /** Lists local radio resources for one cell. */
  listLocalRadioResources(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ChannelList>;
  /** Returns reverse power-control state for one traffic Walsh code on one cell. */
  getReversePowerControl(
    request: DeepPartial<ReversePowerControlScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<TrafficChannelPower>;
  /** Lists reverse power-control state for one cell. */
  listReversePowerControls(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ReversePowerControlList>;
  /** Applies or clears a reverse power-control override on one cell. */
  setReversePowerControlOverride(
    request: DeepPartial<PowerOverrideScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetTrafficChannelPowerOverrideResponse>;
  /** Streams paging-channel transmissions from one cell. */
  streamPchTransmissions(
    request: DeepPartial<CellScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<PagingEvent>;
  /** Returns serving status for one base station. */
  getBscStatus(request: DeepPartial<BsRequest>, options?: CallOptions & CallOptionsExt): Promise<SystemStatus>;
  /** Lists mobiles on one base station. */
  listMobiles(request: DeepPartial<BsRequest>, options?: CallOptions & CallOptionsExt): Promise<MobileList>;
  /** Lists channels on one base station. */
  listChannels(request: DeepPartial<BsRequest>, options?: CallOptions & CallOptionsExt): Promise<ChannelList>;
  /** Streams reverse access-channel events from one base station. */
  streamAccessEvents(
    request: DeepPartial<BsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<AccessEvent>;
  /** Streams paging-channel transmissions from one base station. */
  streamPagingEvents(
    request: DeepPartial<BsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<PagingEvent>;
  /** Streams traffic-channel transmissions from one base station. */
  streamTrafficEvents(
    request: DeepPartial<BsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<TrafficEvent>;
  /**
   * Applies or clears a reverse power-control override, resolved by the base
   * station across its cells.
   */
  setTrafficChannelPowerOverride(
    request: DeepPartial<PowerOverrideScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetTrafficChannelPowerOverrideResponse>;
  /** Lists HRPD sessions on one cell's access network. */
  getAnSessions(
    request: DeepPartial<AnSessionsScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionsResponse>;
  /** Fetches one HRPD session by UATI on one cell's access network. */
  getAnSession(
    request: DeepPartial<AnSessionScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionResponse>;
  /** Inspects UATI allocation on one cell's access network. */
  getAnUatiAllocation(
    request: DeepPartial<AnUatiAllocationScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetUatiAllocationResponse>;
  /** Returns buffered HRPD session events for one UATI on one cell. */
  getAnSessionEvents(
    request: DeepPartial<AnSessionEventsScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionEventsResponse>;
  /**
   * Initiates a data call by paging the mobile and requesting packet service
   * on the named base station.
   */
  initiateDataCall(
    request: DeepPartial<InitiateDataCallScopedRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<InitiateDataCallResponse>;
  /** Lists packet sessions known by the PCF. */
  listPcfSessions(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<PcfSessionList>;
  /** Returns detailed status for one PCF packet session. */
  getPcfSession(
    request: DeepPartial<GetPcfSessionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionStatusResponse>;
  /** Lists packet sessions known by the PDSN. */
  listPdsnSessions(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<PdsnSessionList>;
  /** Returns detailed status for one PDSN packet session. */
  getPdsnSession(
    request: DeepPartial<GetPdsnSessionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionStatusResponse>;
  /** Looks up one active packet session by its assigned mobile IP. */
  getPdsnSessionByIp(
    request: DeepPartial<GetPdsnSessionByIpRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionByIpResponse>;
  /** Enables or disables trace capture on one PDSN packet session. */
  setPacketTraceCapture(
    request: DeepPartial<SetPacketTraceCaptureRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetSessionCaptureResponse>;
  /** Lists mobiles across every base station. */
  listAllMobiles(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<MobileList>;
  /** Lists channels across every base station. */
  listAllChannels(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<ChannelList>;
  /**
   * Streams radio, paging, access, traffic, and health events merged across
   * every base station.
   */
  streamSystemEvents(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<ManagementEvent>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
