// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: bts_management/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import {
  BtsConfig,
  ChannelList,
  IqCaptureStatus,
  PagingEvent,
  RadioMetrics,
  SetTrafficChannelPowerOverrideRequest,
  SetTrafficChannelPowerOverrideResponse,
  SystemStatus,
  TrafficChannelPower,
} from "../../bsc/v1/service";
import { Empty } from "../../google/protobuf/empty";

export const protobufPackage = "bts_management.v1";

/** Selects an active traffic channel by Walsh code. */
export interface ReversePowerControlRequest {
  /** Forward traffic-channel Walsh code assigned to the mobile. */
  walshCode: number;
}

/** Collection of reverse power-control snapshots for active traffic channels. */
export interface ReversePowerControlList {
  /** One snapshot per active traffic channel. */
  powerControls: TrafficChannelPower[];
}

function createBaseReversePowerControlRequest(): ReversePowerControlRequest {
  return { walshCode: 0 };
}

export const ReversePowerControlRequest: MessageFns<ReversePowerControlRequest> = {
  encode(message: ReversePowerControlRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.walshCode !== 0) {
      writer.uint32(8).uint32(message.walshCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReversePowerControlRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReversePowerControlRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.walshCode = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReversePowerControlRequest {
    return {
      walshCode: isSet(object.walshCode)
        ? globalThis.Number(object.walshCode)
        : isSet(object.walsh_code)
        ? globalThis.Number(object.walsh_code)
        : 0,
    };
  },

  toJSON(message: ReversePowerControlRequest): unknown {
    const obj: any = {};
    if (message.walshCode !== 0) {
      obj.walshCode = Math.round(message.walshCode);
    }
    return obj;
  },

  create(base?: DeepPartial<ReversePowerControlRequest>): ReversePowerControlRequest {
    return ReversePowerControlRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReversePowerControlRequest>): ReversePowerControlRequest {
    const message = createBaseReversePowerControlRequest();
    message.walshCode = object.walshCode ?? 0;
    return message;
  },
};

function createBaseReversePowerControlList(): ReversePowerControlList {
  return { powerControls: [] };
}

export const ReversePowerControlList: MessageFns<ReversePowerControlList> = {
  encode(message: ReversePowerControlList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.powerControls) {
      TrafficChannelPower.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReversePowerControlList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReversePowerControlList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.powerControls.push(TrafficChannelPower.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReversePowerControlList {
    return {
      powerControls: globalThis.Array.isArray(object?.powerControls)
        ? object.powerControls.map((e: any) => TrafficChannelPower.fromJSON(e))
        : globalThis.Array.isArray(object?.power_controls)
        ? object.power_controls.map((e: any) => TrafficChannelPower.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ReversePowerControlList): unknown {
    const obj: any = {};
    if (message.powerControls?.length) {
      obj.powerControls = message.powerControls.map((e) => TrafficChannelPower.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ReversePowerControlList>): ReversePowerControlList {
    return ReversePowerControlList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReversePowerControlList>): ReversePowerControlList {
    const message = createBaseReversePowerControlList();
    message.powerControls = object.powerControls?.map((e) => TrafficChannelPower.fromPartial(e)) || [];
    return message;
  },
};

/** BTS-local management API for radio state, capture control, and BTS-originated events. */
export type BtsManagementServiceDefinition = typeof BtsManagementServiceDefinition;
export const BtsManagementServiceDefinition = {
  name: "BtsManagementService",
  fullName: "bts_management.v1.BtsManagementService",
  methods: {
    /** Returns BTS runtime status and configured identity. */
    getBtsStatus: {
      name: "GetBtsStatus",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: SystemStatus as typeof SystemStatus,
      responseStream: false,
      options: {},
    },
    /** Returns the active BTS radio and overhead configuration. */
    getBtsConfig: {
      name: "GetBtsConfig",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: BtsConfig as typeof BtsConfig,
      responseStream: false,
      options: {},
    },
    /** Returns the latest TX/RX/bearer radio metrics snapshot. */
    getRadioMetrics: {
      name: "GetRadioMetrics",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: RadioMetrics as typeof RadioMetrics,
      responseStream: false,
      options: {},
    },
    /** Streams TX/RX/bearer radio metrics as they are updated. */
    streamRadioMetrics: {
      name: "StreamRadioMetrics",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: RadioMetrics as typeof RadioMetrics,
      responseStream: true,
      options: {},
    },
    /** Returns current IQ capture state and output paths. */
    getIqCaptureStatus: {
      name: "GetIqCaptureStatus",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: IqCaptureStatus as typeof IqCaptureStatus,
      responseStream: false,
      options: {},
    },
    /** Starts a BTS-side IQ capture using the configured capture directory. */
    startIqCapture: {
      name: "StartIqCapture",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: IqCaptureStatus as typeof IqCaptureStatus,
      responseStream: false,
      options: {},
    },
    /** Stops the active BTS-side IQ capture, if any. */
    stopIqCapture: {
      name: "StopIqCapture",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: IqCaptureStatus as typeof IqCaptureStatus,
      responseStream: false,
      options: {},
    },
    /** Lists local pilot, sync, paging, access, and traffic resources. */
    listLocalRadioResources: {
      name: "ListLocalRadioResources",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: ChannelList as typeof ChannelList,
      responseStream: false,
      options: {},
    },
    /** Returns reverse closed-loop power control state for one traffic Walsh code. */
    getReversePowerControl: {
      name: "GetReversePowerControl",
      requestType: ReversePowerControlRequest as typeof ReversePowerControlRequest,
      requestStream: false,
      responseType: TrafficChannelPower as typeof TrafficChannelPower,
      responseStream: false,
      options: {},
    },
    /** Lists reverse closed-loop power control state for active traffic channels. */
    listReversePowerControls: {
      name: "ListReversePowerControls",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: ReversePowerControlList as typeof ReversePowerControlList,
      responseStream: false,
      options: {},
    },
    /** Applies or clears a manual reverse power-control target override. */
    setReversePowerControlOverride: {
      name: "SetReversePowerControlOverride",
      requestType: SetTrafficChannelPowerOverrideRequest as typeof SetTrafficChannelPowerOverrideRequest,
      requestStream: false,
      responseType: SetTrafficChannelPowerOverrideResponse as typeof SetTrafficChannelPowerOverrideResponse,
      responseStream: false,
      options: {},
    },
    /** Streams BTS-emitted paging-channel transmissions. */
    streamPchTransmissions: {
      name: "StreamPchTransmissions",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: PagingEvent as typeof PagingEvent,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface BtsManagementServiceImplementation<CallContextExt = {}> {
  /** Returns BTS runtime status and configured identity. */
  getBtsStatus(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<SystemStatus>>;
  /** Returns the active BTS radio and overhead configuration. */
  getBtsConfig(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<BtsConfig>>;
  /** Returns the latest TX/RX/bearer radio metrics snapshot. */
  getRadioMetrics(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<RadioMetrics>>;
  /** Streams TX/RX/bearer radio metrics as they are updated. */
  streamRadioMetrics(
    request: Empty,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<RadioMetrics>>;
  /** Returns current IQ capture state and output paths. */
  getIqCaptureStatus(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<IqCaptureStatus>>;
  /** Starts a BTS-side IQ capture using the configured capture directory. */
  startIqCapture(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<IqCaptureStatus>>;
  /** Stops the active BTS-side IQ capture, if any. */
  stopIqCapture(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<IqCaptureStatus>>;
  /** Lists local pilot, sync, paging, access, and traffic resources. */
  listLocalRadioResources(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<ChannelList>>;
  /** Returns reverse closed-loop power control state for one traffic Walsh code. */
  getReversePowerControl(
    request: ReversePowerControlRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<TrafficChannelPower>>;
  /** Lists reverse closed-loop power control state for active traffic channels. */
  listReversePowerControls(
    request: Empty,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ReversePowerControlList>>;
  /** Applies or clears a manual reverse power-control target override. */
  setReversePowerControlOverride(
    request: SetTrafficChannelPowerOverrideRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetTrafficChannelPowerOverrideResponse>>;
  /** Streams BTS-emitted paging-channel transmissions. */
  streamPchTransmissions(
    request: Empty,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<PagingEvent>>;
}

export interface BtsManagementServiceClient<CallOptionsExt = {}> {
  /** Returns BTS runtime status and configured identity. */
  getBtsStatus(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<SystemStatus>;
  /** Returns the active BTS radio and overhead configuration. */
  getBtsConfig(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<BtsConfig>;
  /** Returns the latest TX/RX/bearer radio metrics snapshot. */
  getRadioMetrics(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<RadioMetrics>;
  /** Streams TX/RX/bearer radio metrics as they are updated. */
  streamRadioMetrics(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): AsyncIterable<RadioMetrics>;
  /** Returns current IQ capture state and output paths. */
  getIqCaptureStatus(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<IqCaptureStatus>;
  /** Starts a BTS-side IQ capture using the configured capture directory. */
  startIqCapture(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<IqCaptureStatus>;
  /** Stops the active BTS-side IQ capture, if any. */
  stopIqCapture(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<IqCaptureStatus>;
  /** Lists local pilot, sync, paging, access, and traffic resources. */
  listLocalRadioResources(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<ChannelList>;
  /** Returns reverse closed-loop power control state for one traffic Walsh code. */
  getReversePowerControl(
    request: DeepPartial<ReversePowerControlRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<TrafficChannelPower>;
  /** Lists reverse closed-loop power control state for active traffic channels. */
  listReversePowerControls(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ReversePowerControlList>;
  /** Applies or clears a manual reverse power-control target override. */
  setReversePowerControlOverride(
    request: DeepPartial<SetTrafficChannelPowerOverrideRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetTrafficChannelPowerOverrideResponse>;
  /** Streams BTS-emitted paging-channel transmissions. */
  streamPchTransmissions(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<PagingEvent>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
