// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: pdsn_management/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "../../google/protobuf/empty";
import {
  GetSessionByIpResponse,
  GetSessionStatusResponse,
  PacketSessionInfo,
  SetSessionCaptureResponse,
} from "../../packet/v1/service";

export const protobufPackage = "pdsn_management.v1";

/** Packet sessions visible through the PDSN management service. */
export interface PdsnSessionList {
  /** Summary for each active or recently tracked packet session. */
  sessions: PacketSessionInfo[];
}

/** Selects a PDSN packet session. */
export interface GetPdsnSessionRequest {
  /** Packet session identifier allocated by packet-call setup. */
  sessionId: string;
}

/** Selects a PDSN packet session by its assigned mobile IP. */
export interface GetPdsnSessionByIpRequest {
  /** Mobile (peer) IP address as the engine reports it, e.g. "10.55.0.2". */
  peerIp: string;
}

/** Enables or disables packet trace capture for one session. */
export interface SetPacketTraceCaptureRequest {
  /** Packet session identifier. */
  sessionId: string;
  /** True to retain packet trace events, false to stop capture. */
  enabled: boolean;
}

function createBasePdsnSessionList(): PdsnSessionList {
  return { sessions: [] };
}

export const PdsnSessionList: MessageFns<PdsnSessionList> = {
  encode(message: PdsnSessionList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sessions) {
      PacketSessionInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PdsnSessionList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePdsnSessionList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessions.push(PacketSessionInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PdsnSessionList {
    return {
      sessions: globalThis.Array.isArray(object?.sessions)
        ? object.sessions.map((e: any) => PacketSessionInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PdsnSessionList): unknown {
    const obj: any = {};
    if (message.sessions?.length) {
      obj.sessions = message.sessions.map((e) => PacketSessionInfo.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<PdsnSessionList>): PdsnSessionList {
    return PdsnSessionList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PdsnSessionList>): PdsnSessionList {
    const message = createBasePdsnSessionList();
    message.sessions = object.sessions?.map((e) => PacketSessionInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetPdsnSessionRequest(): GetPdsnSessionRequest {
  return { sessionId: "" };
}

export const GetPdsnSessionRequest: MessageFns<GetPdsnSessionRequest> = {
  encode(message: GetPdsnSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPdsnSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPdsnSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPdsnSessionRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: GetPdsnSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetPdsnSessionRequest>): GetPdsnSessionRequest {
    return GetPdsnSessionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetPdsnSessionRequest>): GetPdsnSessionRequest {
    const message = createBaseGetPdsnSessionRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseGetPdsnSessionByIpRequest(): GetPdsnSessionByIpRequest {
  return { peerIp: "" };
}

export const GetPdsnSessionByIpRequest: MessageFns<GetPdsnSessionByIpRequest> = {
  encode(message: GetPdsnSessionByIpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.peerIp !== "") {
      writer.uint32(10).string(message.peerIp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPdsnSessionByIpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPdsnSessionByIpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.peerIp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPdsnSessionByIpRequest {
    return {
      peerIp: isSet(object.peerIp)
        ? globalThis.String(object.peerIp)
        : isSet(object.peer_ip)
        ? globalThis.String(object.peer_ip)
        : "",
    };
  },

  toJSON(message: GetPdsnSessionByIpRequest): unknown {
    const obj: any = {};
    if (message.peerIp !== "") {
      obj.peerIp = message.peerIp;
    }
    return obj;
  },

  create(base?: DeepPartial<GetPdsnSessionByIpRequest>): GetPdsnSessionByIpRequest {
    return GetPdsnSessionByIpRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetPdsnSessionByIpRequest>): GetPdsnSessionByIpRequest {
    const message = createBaseGetPdsnSessionByIpRequest();
    message.peerIp = object.peerIp ?? "";
    return message;
  },
};

function createBaseSetPacketTraceCaptureRequest(): SetPacketTraceCaptureRequest {
  return { sessionId: "", enabled: false };
}

export const SetPacketTraceCaptureRequest: MessageFns<SetPacketTraceCaptureRequest> = {
  encode(message: SetPacketTraceCaptureRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.enabled !== false) {
      writer.uint32(16).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetPacketTraceCaptureRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetPacketTraceCaptureRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetPacketTraceCaptureRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
    };
  },

  toJSON(message: SetPacketTraceCaptureRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create(base?: DeepPartial<SetPacketTraceCaptureRequest>): SetPacketTraceCaptureRequest {
    return SetPacketTraceCaptureRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetPacketTraceCaptureRequest>): SetPacketTraceCaptureRequest {
    const message = createBaseSetPacketTraceCaptureRequest();
    message.sessionId = object.sessionId ?? "";
    message.enabled = object.enabled ?? false;
    return message;
  },
};

/** PDSN management API for packet session status and trace capture control. */
export type PdsnManagementServiceDefinition = typeof PdsnManagementServiceDefinition;
export const PdsnManagementServiceDefinition = {
  name: "PdsnManagementService",
  fullName: "pdsn_management.v1.PdsnManagementService",
  methods: {
    /** Lists packet sessions known by the PDSN. */
    listPdsnSessions: {
      name: "ListPdsnSessions",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: PdsnSessionList as typeof PdsnSessionList,
      responseStream: false,
      options: {},
    },
    /** Returns detailed status for one packet session. */
    getPdsnSession: {
      name: "GetPdsnSession",
      requestType: GetPdsnSessionRequest as typeof GetPdsnSessionRequest,
      requestStream: false,
      responseType: GetSessionStatusResponse as typeof GetSessionStatusResponse,
      responseStream: false,
      options: {},
    },
    /**
     * Looks up one active packet session by its assigned mobile IP. Used by
     * the edge MSISDN resolver in fou-nat to attribute inbound HTTP requests
     * to a subscriber. Returns an unset `session` field on miss.
     */
    getPdsnSessionByIp: {
      name: "GetPdsnSessionByIp",
      requestType: GetPdsnSessionByIpRequest as typeof GetPdsnSessionByIpRequest,
      requestStream: false,
      responseType: GetSessionByIpResponse as typeof GetSessionByIpResponse,
      responseStream: false,
      options: {},
    },
    /** Enables or disables trace capture on one packet session. */
    setPacketTraceCapture: {
      name: "SetPacketTraceCapture",
      requestType: SetPacketTraceCaptureRequest as typeof SetPacketTraceCaptureRequest,
      requestStream: false,
      responseType: SetSessionCaptureResponse as typeof SetSessionCaptureResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface PdsnManagementServiceImplementation<CallContextExt = {}> {
  /** Lists packet sessions known by the PDSN. */
  listPdsnSessions(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<PdsnSessionList>>;
  /** Returns detailed status for one packet session. */
  getPdsnSession(
    request: GetPdsnSessionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionStatusResponse>>;
  /**
   * Looks up one active packet session by its assigned mobile IP. Used by
   * the edge MSISDN resolver in fou-nat to attribute inbound HTTP requests
   * to a subscriber. Returns an unset `session` field on miss.
   */
  getPdsnSessionByIp(
    request: GetPdsnSessionByIpRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionByIpResponse>>;
  /** Enables or disables trace capture on one packet session. */
  setPacketTraceCapture(
    request: SetPacketTraceCaptureRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetSessionCaptureResponse>>;
}

export interface PdsnManagementServiceClient<CallOptionsExt = {}> {
  /** Lists packet sessions known by the PDSN. */
  listPdsnSessions(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<PdsnSessionList>;
  /** Returns detailed status for one packet session. */
  getPdsnSession(
    request: DeepPartial<GetPdsnSessionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionStatusResponse>;
  /**
   * Looks up one active packet session by its assigned mobile IP. Used by
   * the edge MSISDN resolver in fou-nat to attribute inbound HTTP requests
   * to a subscriber. Returns an unset `session` field on miss.
   */
  getPdsnSessionByIp(
    request: DeepPartial<GetPdsnSessionByIpRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionByIpResponse>;
  /** Enables or disables trace capture on one packet session. */
  setPacketTraceCapture(
    request: DeepPartial<SetPacketTraceCaptureRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetSessionCaptureResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
