// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: events/v1/an.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "events.v1";

/** Reason an HRPD session-layer event was emitted. */
export enum HrpdSessionReason {
  HRPD_SESSION_REASON_UNSPECIFIED = 0,
  HRPD_SESSION_REASON_OPENED = 1,
  HRPD_SESSION_REASON_CLOSED = 2,
  HRPD_SESSION_REASON_UATI_ASSIGNED = 3,
  HRPD_SESSION_REASON_PROTOCOL_NEGOTIATED = 4,
  HRPD_SESSION_REASON_UATI_RELEASED = 5,
  UNRECOGNIZED = -1,
}

export function hrpdSessionReasonFromJSON(object: any): HrpdSessionReason {
  switch (object) {
    case 0:
    case "HRPD_SESSION_REASON_UNSPECIFIED":
      return HrpdSessionReason.HRPD_SESSION_REASON_UNSPECIFIED;
    case 1:
    case "HRPD_SESSION_REASON_OPENED":
      return HrpdSessionReason.HRPD_SESSION_REASON_OPENED;
    case 2:
    case "HRPD_SESSION_REASON_CLOSED":
      return HrpdSessionReason.HRPD_SESSION_REASON_CLOSED;
    case 3:
    case "HRPD_SESSION_REASON_UATI_ASSIGNED":
      return HrpdSessionReason.HRPD_SESSION_REASON_UATI_ASSIGNED;
    case 4:
    case "HRPD_SESSION_REASON_PROTOCOL_NEGOTIATED":
      return HrpdSessionReason.HRPD_SESSION_REASON_PROTOCOL_NEGOTIATED;
    case 5:
    case "HRPD_SESSION_REASON_UATI_RELEASED":
      return HrpdSessionReason.HRPD_SESSION_REASON_UATI_RELEASED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HrpdSessionReason.UNRECOGNIZED;
  }
}

export function hrpdSessionReasonToJSON(object: HrpdSessionReason): string {
  switch (object) {
    case HrpdSessionReason.HRPD_SESSION_REASON_UNSPECIFIED:
      return "HRPD_SESSION_REASON_UNSPECIFIED";
    case HrpdSessionReason.HRPD_SESSION_REASON_OPENED:
      return "HRPD_SESSION_REASON_OPENED";
    case HrpdSessionReason.HRPD_SESSION_REASON_CLOSED:
      return "HRPD_SESSION_REASON_CLOSED";
    case HrpdSessionReason.HRPD_SESSION_REASON_UATI_ASSIGNED:
      return "HRPD_SESSION_REASON_UATI_ASSIGNED";
    case HrpdSessionReason.HRPD_SESSION_REASON_PROTOCOL_NEGOTIATED:
      return "HRPD_SESSION_REASON_PROTOCOL_NEGOTIATED";
    case HrpdSessionReason.HRPD_SESSION_REASON_UATI_RELEASED:
      return "HRPD_SESSION_REASON_UATI_RELEASED";
    case HrpdSessionReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Reason an HRPD access-channel event was emitted. */
export enum HrpdAccessReason {
  HRPD_ACCESS_REASON_UNSPECIFIED = 0,
  HRPD_ACCESS_REASON_CONNECTION_REQUEST = 1,
  HRPD_ACCESS_REASON_UATI_REQUEST = 2,
  HRPD_ACCESS_REASON_ROUTE_UPDATE = 3,
  HRPD_ACCESS_REASON_KEEP_ALIVE = 4,
  HRPD_ACCESS_REASON_UNKNOWN = 5,
  UNRECOGNIZED = -1,
}

export function hrpdAccessReasonFromJSON(object: any): HrpdAccessReason {
  switch (object) {
    case 0:
    case "HRPD_ACCESS_REASON_UNSPECIFIED":
      return HrpdAccessReason.HRPD_ACCESS_REASON_UNSPECIFIED;
    case 1:
    case "HRPD_ACCESS_REASON_CONNECTION_REQUEST":
      return HrpdAccessReason.HRPD_ACCESS_REASON_CONNECTION_REQUEST;
    case 2:
    case "HRPD_ACCESS_REASON_UATI_REQUEST":
      return HrpdAccessReason.HRPD_ACCESS_REASON_UATI_REQUEST;
    case 3:
    case "HRPD_ACCESS_REASON_ROUTE_UPDATE":
      return HrpdAccessReason.HRPD_ACCESS_REASON_ROUTE_UPDATE;
    case 4:
    case "HRPD_ACCESS_REASON_KEEP_ALIVE":
      return HrpdAccessReason.HRPD_ACCESS_REASON_KEEP_ALIVE;
    case 5:
    case "HRPD_ACCESS_REASON_UNKNOWN":
      return HrpdAccessReason.HRPD_ACCESS_REASON_UNKNOWN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HrpdAccessReason.UNRECOGNIZED;
  }
}

export function hrpdAccessReasonToJSON(object: HrpdAccessReason): string {
  switch (object) {
    case HrpdAccessReason.HRPD_ACCESS_REASON_UNSPECIFIED:
      return "HRPD_ACCESS_REASON_UNSPECIFIED";
    case HrpdAccessReason.HRPD_ACCESS_REASON_CONNECTION_REQUEST:
      return "HRPD_ACCESS_REASON_CONNECTION_REQUEST";
    case HrpdAccessReason.HRPD_ACCESS_REASON_UATI_REQUEST:
      return "HRPD_ACCESS_REASON_UATI_REQUEST";
    case HrpdAccessReason.HRPD_ACCESS_REASON_ROUTE_UPDATE:
      return "HRPD_ACCESS_REASON_ROUTE_UPDATE";
    case HrpdAccessReason.HRPD_ACCESS_REASON_KEEP_ALIVE:
      return "HRPD_ACCESS_REASON_KEEP_ALIVE";
    case HrpdAccessReason.HRPD_ACCESS_REASON_UNKNOWN:
      return "HRPD_ACCESS_REASON_UNKNOWN";
    case HrpdAccessReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Reason an HRPD reverse/forward traffic event was emitted. */
export enum HrpdTrafficReason {
  HRPD_TRAFFIC_REASON_UNSPECIFIED = 0,
  HRPD_TRAFFIC_REASON_FRAME_DECODED = 1,
  HRPD_TRAFFIC_REASON_DRC_UPDATED = 2,
  HRPD_TRAFFIC_REASON_ACK_RECEIVED = 3,
  HRPD_TRAFFIC_REASON_CONNECTION_CLOSE = 4,
  HRPD_TRAFFIC_REASON_REVERSE_PILOT_SNR_UPDATED = 5,
  UNRECOGNIZED = -1,
}

export function hrpdTrafficReasonFromJSON(object: any): HrpdTrafficReason {
  switch (object) {
    case 0:
    case "HRPD_TRAFFIC_REASON_UNSPECIFIED":
      return HrpdTrafficReason.HRPD_TRAFFIC_REASON_UNSPECIFIED;
    case 1:
    case "HRPD_TRAFFIC_REASON_FRAME_DECODED":
      return HrpdTrafficReason.HRPD_TRAFFIC_REASON_FRAME_DECODED;
    case 2:
    case "HRPD_TRAFFIC_REASON_DRC_UPDATED":
      return HrpdTrafficReason.HRPD_TRAFFIC_REASON_DRC_UPDATED;
    case 3:
    case "HRPD_TRAFFIC_REASON_ACK_RECEIVED":
      return HrpdTrafficReason.HRPD_TRAFFIC_REASON_ACK_RECEIVED;
    case 4:
    case "HRPD_TRAFFIC_REASON_CONNECTION_CLOSE":
      return HrpdTrafficReason.HRPD_TRAFFIC_REASON_CONNECTION_CLOSE;
    case 5:
    case "HRPD_TRAFFIC_REASON_REVERSE_PILOT_SNR_UPDATED":
      return HrpdTrafficReason.HRPD_TRAFFIC_REASON_REVERSE_PILOT_SNR_UPDATED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HrpdTrafficReason.UNRECOGNIZED;
  }
}

export function hrpdTrafficReasonToJSON(object: HrpdTrafficReason): string {
  switch (object) {
    case HrpdTrafficReason.HRPD_TRAFFIC_REASON_UNSPECIFIED:
      return "HRPD_TRAFFIC_REASON_UNSPECIFIED";
    case HrpdTrafficReason.HRPD_TRAFFIC_REASON_FRAME_DECODED:
      return "HRPD_TRAFFIC_REASON_FRAME_DECODED";
    case HrpdTrafficReason.HRPD_TRAFFIC_REASON_DRC_UPDATED:
      return "HRPD_TRAFFIC_REASON_DRC_UPDATED";
    case HrpdTrafficReason.HRPD_TRAFFIC_REASON_ACK_RECEIVED:
      return "HRPD_TRAFFIC_REASON_ACK_RECEIVED";
    case HrpdTrafficReason.HRPD_TRAFFIC_REASON_CONNECTION_CLOSE:
      return "HRPD_TRAFFIC_REASON_CONNECTION_CLOSE";
    case HrpdTrafficReason.HRPD_TRAFFIC_REASON_REVERSE_PILOT_SNR_UPDATED:
      return "HRPD_TRAFFIC_REASON_REVERSE_PILOT_SNR_UPDATED";
    case HrpdTrafficReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Air-interface direction for a UI-visible HRPD message. */
export enum HrpdDirection {
  HRPD_DIRECTION_UNSPECIFIED = 0,
  HRPD_DIRECTION_RX = 1,
  HRPD_DIRECTION_TX = 2,
  UNRECOGNIZED = -1,
}

export function hrpdDirectionFromJSON(object: any): HrpdDirection {
  switch (object) {
    case 0:
    case "HRPD_DIRECTION_UNSPECIFIED":
      return HrpdDirection.HRPD_DIRECTION_UNSPECIFIED;
    case 1:
    case "HRPD_DIRECTION_RX":
      return HrpdDirection.HRPD_DIRECTION_RX;
    case 2:
    case "HRPD_DIRECTION_TX":
      return HrpdDirection.HRPD_DIRECTION_TX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HrpdDirection.UNRECOGNIZED;
  }
}

export function hrpdDirectionToJSON(object: HrpdDirection): string {
  switch (object) {
    case HrpdDirection.HRPD_DIRECTION_UNSPECIFIED:
      return "HRPD_DIRECTION_UNSPECIFIED";
    case HrpdDirection.HRPD_DIRECTION_RX:
      return "HRPD_DIRECTION_RX";
    case HrpdDirection.HRPD_DIRECTION_TX:
      return "HRPD_DIRECTION_TX";
    case HrpdDirection.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Canonical 128-bit HRPD UATI assigned by Address Management. The 32-bit
 * receive ATI used on the air interface is derived as
 * UATIColorCode | UATI[23:0] and is carried separately when needed.
 */
export interface HrpdUati {
  value: Uint8Array;
  colorCode: number;
  subnetMask: number;
  compactUati32: number;
}

/**
 * One decoded HRPD signaling/message element carried by an access capsule or
 * traffic frame. The detailed fields retain the protocol decode alongside the
 * raw bytes so logs can show what happened without reparsing payloads.
 */
export interface HrpdDecodedMessage {
  /** Stable short type label, e.g. "RouteUpdate" or "ConnectionRequest". */
  typeName: string;
  /** One-line decoded summary for log rows. */
  summary: string;
  /** HRPD protocol type that carried the message, when known. */
  protocolType: number;
  /** MessageID within protocol_type, when known. */
  messageId: number;
  /** Raw decoded message payload, when available. */
  payload: Uint8Array;
}

/** HRPD session-layer event (UATI assignment, protocol negotiation, teardown). */
export interface HrpdSessionEvent {
  timestampNs: string;
  uati: number;
  reason: HrpdSessionReason;
  /** Sector color code that scopes the UATI. */
  colorCode: number;
  /**
   * Negotiated protocol subtype per HRPD layer, carried as the raw subtype
   * number (0 = Default subtype, which is all Rev 0 negotiates). Each layer has
   * its own subtype number space, so these stay raw integers rather than enums.
   */
  airLinkManagementSubtype: number;
  sessionManagementSubtype: number;
  addressManagementSubtype: number;
  connectionLayerSubtype: number;
  securitySubtype: number;
  macSubtype: number;
  physicalLayerSubtype: number;
  fullUati: HrpdUati | undefined;
}

/** HRPD access-channel event (capsule received on the reverse access channel). */
export interface HrpdAccessEvent {
  timestampNs: string;
  /** 32-bit access signature observed for this capsule. */
  accessSignature: string;
  reason: HrpdAccessReason;
  /** Raw access capsule payload, post-decode. */
  payload: Uint8Array;
  /** Sector that received the capsule. */
  colorCode: number;
  /** Access messages are reverse-link messages from the AT. */
  direction: HrpdDirection;
  /** Decoded messages contained in this access capsule. */
  decodedMessages: HrpdDecodedMessage[];
  /**
   * Payload length retained for JSON/SSE display even when bytes encode as
   * base64 or an object in JavaScript.
   */
  payloadLengthBytes: number;
  /**
   * Session or receive-form UATI when the access capsule can be associated
   * with one. Zero means the capsule was pre-UATI or unresolved.
   */
  uati: number;
  fullUati: HrpdUati | undefined;
  receiveAti: number;
}

/** HRPD traffic-layer event (per-frame decode, DRC update, ACK, teardown). */
export interface HrpdTrafficEvent {
  timestampNs: string;
  uati: number;
  reason: HrpdTrafficReason;
  /** Negotiated MAC index for the AT's traffic channel. */
  macIndex: number;
  /** Most recent Data Rate Control value reported by the AT. */
  drcValue: number;
  /** Optional decoded frame payload (when reason = FRAME_DECODED). */
  payload: Uint8Array;
  /** Reverse-pilot SNR in tenths of a dB, when known (0 = unknown). */
  reversePilotSnrDbTenths: number;
  /** Direction of the UI-visible traffic event. */
  direction: HrpdDirection;
  /** Decoded signaling/messages carried by this event. */
  decodedMessages: HrpdDecodedMessage[];
  /**
   * Payload length retained for JSON/SSE display even when bytes encode as
   * base64 or an object in JavaScript.
   */
  payloadLengthBytes: number;
  fullUati: HrpdUati | undefined;
  receiveAti: number;
}

/**
 * AN wrapper sub-message for the aggregated event bus. One arm per HRPD
 * event class, matching the per-component wrapper convention of the bus.
 */
export interface AnNetworkEvent {
  session?: HrpdSessionEvent | undefined;
  access?: HrpdAccessEvent | undefined;
  traffic?: HrpdTrafficEvent | undefined;
}

function createBaseHrpdUati(): HrpdUati {
  return { value: new Uint8Array(0), colorCode: 0, subnetMask: 0, compactUati32: 0 };
}

export const HrpdUati: MessageFns<HrpdUati> = {
  encode(message: HrpdUati, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value.length !== 0) {
      writer.uint32(10).bytes(message.value);
    }
    if (message.colorCode !== 0) {
      writer.uint32(16).uint32(message.colorCode);
    }
    if (message.subnetMask !== 0) {
      writer.uint32(24).uint32(message.subnetMask);
    }
    if (message.compactUati32 !== 0) {
      writer.uint32(32).uint32(message.compactUati32);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HrpdUati {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHrpdUati();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.colorCode = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.subnetMask = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.compactUati32 = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HrpdUati {
    return {
      value: isSet(object.value) ? bytesFromBase64(object.value) : new Uint8Array(0),
      colorCode: isSet(object.colorCode)
        ? globalThis.Number(object.colorCode)
        : isSet(object.color_code)
        ? globalThis.Number(object.color_code)
        : 0,
      subnetMask: isSet(object.subnetMask)
        ? globalThis.Number(object.subnetMask)
        : isSet(object.subnet_mask)
        ? globalThis.Number(object.subnet_mask)
        : 0,
      compactUati32: isSet(object.compactUati32)
        ? globalThis.Number(object.compactUati32)
        : isSet(object.compact_uati32)
        ? globalThis.Number(object.compact_uati32)
        : 0,
    };
  },

  toJSON(message: HrpdUati): unknown {
    const obj: any = {};
    if (message.value.length !== 0) {
      obj.value = base64FromBytes(message.value);
    }
    if (message.colorCode !== 0) {
      obj.colorCode = Math.round(message.colorCode);
    }
    if (message.subnetMask !== 0) {
      obj.subnetMask = Math.round(message.subnetMask);
    }
    if (message.compactUati32 !== 0) {
      obj.compactUati32 = Math.round(message.compactUati32);
    }
    return obj;
  },

  create(base?: DeepPartial<HrpdUati>): HrpdUati {
    return HrpdUati.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HrpdUati>): HrpdUati {
    const message = createBaseHrpdUati();
    message.value = object.value ?? new Uint8Array(0);
    message.colorCode = object.colorCode ?? 0;
    message.subnetMask = object.subnetMask ?? 0;
    message.compactUati32 = object.compactUati32 ?? 0;
    return message;
  },
};

function createBaseHrpdDecodedMessage(): HrpdDecodedMessage {
  return { typeName: "", summary: "", protocolType: 0, messageId: 0, payload: new Uint8Array(0) };
}

export const HrpdDecodedMessage: MessageFns<HrpdDecodedMessage> = {
  encode(message: HrpdDecodedMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.typeName !== "") {
      writer.uint32(10).string(message.typeName);
    }
    if (message.summary !== "") {
      writer.uint32(18).string(message.summary);
    }
    if (message.protocolType !== 0) {
      writer.uint32(24).uint32(message.protocolType);
    }
    if (message.messageId !== 0) {
      writer.uint32(32).uint32(message.messageId);
    }
    if (message.payload.length !== 0) {
      writer.uint32(42).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HrpdDecodedMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHrpdDecodedMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.typeName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.protocolType = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.messageId = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HrpdDecodedMessage {
    return {
      typeName: isSet(object.typeName)
        ? globalThis.String(object.typeName)
        : isSet(object.type_name)
        ? globalThis.String(object.type_name)
        : "",
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
      protocolType: isSet(object.protocolType)
        ? globalThis.Number(object.protocolType)
        : isSet(object.protocol_type)
        ? globalThis.Number(object.protocol_type)
        : 0,
      messageId: isSet(object.messageId)
        ? globalThis.Number(object.messageId)
        : isSet(object.message_id)
        ? globalThis.Number(object.message_id)
        : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: HrpdDecodedMessage): unknown {
    const obj: any = {};
    if (message.typeName !== "") {
      obj.typeName = message.typeName;
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    if (message.protocolType !== 0) {
      obj.protocolType = Math.round(message.protocolType);
    }
    if (message.messageId !== 0) {
      obj.messageId = Math.round(message.messageId);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create(base?: DeepPartial<HrpdDecodedMessage>): HrpdDecodedMessage {
    return HrpdDecodedMessage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HrpdDecodedMessage>): HrpdDecodedMessage {
    const message = createBaseHrpdDecodedMessage();
    message.typeName = object.typeName ?? "";
    message.summary = object.summary ?? "";
    message.protocolType = object.protocolType ?? 0;
    message.messageId = object.messageId ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseHrpdSessionEvent(): HrpdSessionEvent {
  return {
    timestampNs: "0",
    uati: 0,
    reason: 0,
    colorCode: 0,
    airLinkManagementSubtype: 0,
    sessionManagementSubtype: 0,
    addressManagementSubtype: 0,
    connectionLayerSubtype: 0,
    securitySubtype: 0,
    macSubtype: 0,
    physicalLayerSubtype: 0,
    fullUati: undefined,
  };
}

export const HrpdSessionEvent: MessageFns<HrpdSessionEvent> = {
  encode(message: HrpdSessionEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestampNs !== "0") {
      writer.uint32(8).uint64(message.timestampNs);
    }
    if (message.uati !== 0) {
      writer.uint32(16).uint32(message.uati);
    }
    if (message.reason !== 0) {
      writer.uint32(24).int32(message.reason);
    }
    if (message.colorCode !== 0) {
      writer.uint32(32).uint32(message.colorCode);
    }
    if (message.airLinkManagementSubtype !== 0) {
      writer.uint32(40).uint32(message.airLinkManagementSubtype);
    }
    if (message.sessionManagementSubtype !== 0) {
      writer.uint32(48).uint32(message.sessionManagementSubtype);
    }
    if (message.addressManagementSubtype !== 0) {
      writer.uint32(56).uint32(message.addressManagementSubtype);
    }
    if (message.connectionLayerSubtype !== 0) {
      writer.uint32(64).uint32(message.connectionLayerSubtype);
    }
    if (message.securitySubtype !== 0) {
      writer.uint32(72).uint32(message.securitySubtype);
    }
    if (message.macSubtype !== 0) {
      writer.uint32(80).uint32(message.macSubtype);
    }
    if (message.physicalLayerSubtype !== 0) {
      writer.uint32(88).uint32(message.physicalLayerSubtype);
    }
    if (message.fullUati !== undefined) {
      HrpdUati.encode(message.fullUati, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HrpdSessionEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHrpdSessionEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestampNs = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.uati = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reason = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.colorCode = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.airLinkManagementSubtype = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sessionManagementSubtype = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.addressManagementSubtype = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.connectionLayerSubtype = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.securitySubtype = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.macSubtype = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.physicalLayerSubtype = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.fullUati = HrpdUati.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HrpdSessionEvent {
    return {
      timestampNs: isSet(object.timestampNs)
        ? globalThis.String(object.timestampNs)
        : isSet(object.timestamp_ns)
        ? globalThis.String(object.timestamp_ns)
        : "0",
      uati: isSet(object.uati) ? globalThis.Number(object.uati) : 0,
      reason: isSet(object.reason) ? hrpdSessionReasonFromJSON(object.reason) : 0,
      colorCode: isSet(object.colorCode)
        ? globalThis.Number(object.colorCode)
        : isSet(object.color_code)
        ? globalThis.Number(object.color_code)
        : 0,
      airLinkManagementSubtype: isSet(object.airLinkManagementSubtype)
        ? globalThis.Number(object.airLinkManagementSubtype)
        : isSet(object.air_link_management_subtype)
        ? globalThis.Number(object.air_link_management_subtype)
        : 0,
      sessionManagementSubtype: isSet(object.sessionManagementSubtype)
        ? globalThis.Number(object.sessionManagementSubtype)
        : isSet(object.session_management_subtype)
        ? globalThis.Number(object.session_management_subtype)
        : 0,
      addressManagementSubtype: isSet(object.addressManagementSubtype)
        ? globalThis.Number(object.addressManagementSubtype)
        : isSet(object.address_management_subtype)
        ? globalThis.Number(object.address_management_subtype)
        : 0,
      connectionLayerSubtype: isSet(object.connectionLayerSubtype)
        ? globalThis.Number(object.connectionLayerSubtype)
        : isSet(object.connection_layer_subtype)
        ? globalThis.Number(object.connection_layer_subtype)
        : 0,
      securitySubtype: isSet(object.securitySubtype)
        ? globalThis.Number(object.securitySubtype)
        : isSet(object.security_subtype)
        ? globalThis.Number(object.security_subtype)
        : 0,
      macSubtype: isSet(object.macSubtype)
        ? globalThis.Number(object.macSubtype)
        : isSet(object.mac_subtype)
        ? globalThis.Number(object.mac_subtype)
        : 0,
      physicalLayerSubtype: isSet(object.physicalLayerSubtype)
        ? globalThis.Number(object.physicalLayerSubtype)
        : isSet(object.physical_layer_subtype)
        ? globalThis.Number(object.physical_layer_subtype)
        : 0,
      fullUati: isSet(object.fullUati)
        ? HrpdUati.fromJSON(object.fullUati)
        : isSet(object.full_uati)
        ? HrpdUati.fromJSON(object.full_uati)
        : undefined,
    };
  },

  toJSON(message: HrpdSessionEvent): unknown {
    const obj: any = {};
    if (message.timestampNs !== "0") {
      obj.timestampNs = globalThis.String(message.timestampNs);
    }
    if (message.uati !== 0) {
      obj.uati = Math.round(message.uati);
    }
    if (message.reason !== 0) {
      obj.reason = hrpdSessionReasonToJSON(message.reason);
    }
    if (message.colorCode !== 0) {
      obj.colorCode = Math.round(message.colorCode);
    }
    if (message.airLinkManagementSubtype !== 0) {
      obj.airLinkManagementSubtype = Math.round(message.airLinkManagementSubtype);
    }
    if (message.sessionManagementSubtype !== 0) {
      obj.sessionManagementSubtype = Math.round(message.sessionManagementSubtype);
    }
    if (message.addressManagementSubtype !== 0) {
      obj.addressManagementSubtype = Math.round(message.addressManagementSubtype);
    }
    if (message.connectionLayerSubtype !== 0) {
      obj.connectionLayerSubtype = Math.round(message.connectionLayerSubtype);
    }
    if (message.securitySubtype !== 0) {
      obj.securitySubtype = Math.round(message.securitySubtype);
    }
    if (message.macSubtype !== 0) {
      obj.macSubtype = Math.round(message.macSubtype);
    }
    if (message.physicalLayerSubtype !== 0) {
      obj.physicalLayerSubtype = Math.round(message.physicalLayerSubtype);
    }
    if (message.fullUati !== undefined) {
      obj.fullUati = HrpdUati.toJSON(message.fullUati);
    }
    return obj;
  },

  create(base?: DeepPartial<HrpdSessionEvent>): HrpdSessionEvent {
    return HrpdSessionEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HrpdSessionEvent>): HrpdSessionEvent {
    const message = createBaseHrpdSessionEvent();
    message.timestampNs = object.timestampNs ?? "0";
    message.uati = object.uati ?? 0;
    message.reason = object.reason ?? 0;
    message.colorCode = object.colorCode ?? 0;
    message.airLinkManagementSubtype = object.airLinkManagementSubtype ?? 0;
    message.sessionManagementSubtype = object.sessionManagementSubtype ?? 0;
    message.addressManagementSubtype = object.addressManagementSubtype ?? 0;
    message.connectionLayerSubtype = object.connectionLayerSubtype ?? 0;
    message.securitySubtype = object.securitySubtype ?? 0;
    message.macSubtype = object.macSubtype ?? 0;
    message.physicalLayerSubtype = object.physicalLayerSubtype ?? 0;
    message.fullUati = (object.fullUati !== undefined && object.fullUati !== null)
      ? HrpdUati.fromPartial(object.fullUati)
      : undefined;
    return message;
  },
};

function createBaseHrpdAccessEvent(): HrpdAccessEvent {
  return {
    timestampNs: "0",
    accessSignature: "0",
    reason: 0,
    payload: new Uint8Array(0),
    colorCode: 0,
    direction: 0,
    decodedMessages: [],
    payloadLengthBytes: 0,
    uati: 0,
    fullUati: undefined,
    receiveAti: 0,
  };
}

export const HrpdAccessEvent: MessageFns<HrpdAccessEvent> = {
  encode(message: HrpdAccessEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestampNs !== "0") {
      writer.uint32(8).uint64(message.timestampNs);
    }
    if (message.accessSignature !== "0") {
      writer.uint32(16).uint64(message.accessSignature);
    }
    if (message.reason !== 0) {
      writer.uint32(24).int32(message.reason);
    }
    if (message.payload.length !== 0) {
      writer.uint32(34).bytes(message.payload);
    }
    if (message.colorCode !== 0) {
      writer.uint32(40).uint32(message.colorCode);
    }
    if (message.direction !== 0) {
      writer.uint32(48).int32(message.direction);
    }
    for (const v of message.decodedMessages) {
      HrpdDecodedMessage.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.payloadLengthBytes !== 0) {
      writer.uint32(64).uint32(message.payloadLengthBytes);
    }
    if (message.uati !== 0) {
      writer.uint32(72).uint32(message.uati);
    }
    if (message.fullUati !== undefined) {
      HrpdUati.encode(message.fullUati, writer.uint32(82).fork()).join();
    }
    if (message.receiveAti !== 0) {
      writer.uint32(88).uint32(message.receiveAti);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HrpdAccessEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHrpdAccessEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestampNs = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.accessSignature = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reason = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.colorCode = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.direction = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.decodedMessages.push(HrpdDecodedMessage.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.payloadLengthBytes = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.uati = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.fullUati = HrpdUati.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.receiveAti = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HrpdAccessEvent {
    return {
      timestampNs: isSet(object.timestampNs)
        ? globalThis.String(object.timestampNs)
        : isSet(object.timestamp_ns)
        ? globalThis.String(object.timestamp_ns)
        : "0",
      accessSignature: isSet(object.accessSignature)
        ? globalThis.String(object.accessSignature)
        : isSet(object.access_signature)
        ? globalThis.String(object.access_signature)
        : "0",
      reason: isSet(object.reason) ? hrpdAccessReasonFromJSON(object.reason) : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      colorCode: isSet(object.colorCode)
        ? globalThis.Number(object.colorCode)
        : isSet(object.color_code)
        ? globalThis.Number(object.color_code)
        : 0,
      direction: isSet(object.direction) ? hrpdDirectionFromJSON(object.direction) : 0,
      decodedMessages: globalThis.Array.isArray(object?.decodedMessages)
        ? object.decodedMessages.map((e: any) => HrpdDecodedMessage.fromJSON(e))
        : globalThis.Array.isArray(object?.decoded_messages)
        ? object.decoded_messages.map((e: any) => HrpdDecodedMessage.fromJSON(e))
        : [],
      payloadLengthBytes: isSet(object.payloadLengthBytes)
        ? globalThis.Number(object.payloadLengthBytes)
        : isSet(object.payload_length_bytes)
        ? globalThis.Number(object.payload_length_bytes)
        : 0,
      uati: isSet(object.uati) ? globalThis.Number(object.uati) : 0,
      fullUati: isSet(object.fullUati)
        ? HrpdUati.fromJSON(object.fullUati)
        : isSet(object.full_uati)
        ? HrpdUati.fromJSON(object.full_uati)
        : undefined,
      receiveAti: isSet(object.receiveAti)
        ? globalThis.Number(object.receiveAti)
        : isSet(object.receive_ati)
        ? globalThis.Number(object.receive_ati)
        : 0,
    };
  },

  toJSON(message: HrpdAccessEvent): unknown {
    const obj: any = {};
    if (message.timestampNs !== "0") {
      obj.timestampNs = globalThis.String(message.timestampNs);
    }
    if (message.accessSignature !== "0") {
      obj.accessSignature = globalThis.String(message.accessSignature);
    }
    if (message.reason !== 0) {
      obj.reason = hrpdAccessReasonToJSON(message.reason);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.colorCode !== 0) {
      obj.colorCode = Math.round(message.colorCode);
    }
    if (message.direction !== 0) {
      obj.direction = hrpdDirectionToJSON(message.direction);
    }
    if (message.decodedMessages?.length) {
      obj.decodedMessages = message.decodedMessages.map((e) => HrpdDecodedMessage.toJSON(e));
    }
    if (message.payloadLengthBytes !== 0) {
      obj.payloadLengthBytes = Math.round(message.payloadLengthBytes);
    }
    if (message.uati !== 0) {
      obj.uati = Math.round(message.uati);
    }
    if (message.fullUati !== undefined) {
      obj.fullUati = HrpdUati.toJSON(message.fullUati);
    }
    if (message.receiveAti !== 0) {
      obj.receiveAti = Math.round(message.receiveAti);
    }
    return obj;
  },

  create(base?: DeepPartial<HrpdAccessEvent>): HrpdAccessEvent {
    return HrpdAccessEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HrpdAccessEvent>): HrpdAccessEvent {
    const message = createBaseHrpdAccessEvent();
    message.timestampNs = object.timestampNs ?? "0";
    message.accessSignature = object.accessSignature ?? "0";
    message.reason = object.reason ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    message.colorCode = object.colorCode ?? 0;
    message.direction = object.direction ?? 0;
    message.decodedMessages = object.decodedMessages?.map((e) => HrpdDecodedMessage.fromPartial(e)) || [];
    message.payloadLengthBytes = object.payloadLengthBytes ?? 0;
    message.uati = object.uati ?? 0;
    message.fullUati = (object.fullUati !== undefined && object.fullUati !== null)
      ? HrpdUati.fromPartial(object.fullUati)
      : undefined;
    message.receiveAti = object.receiveAti ?? 0;
    return message;
  },
};

function createBaseHrpdTrafficEvent(): HrpdTrafficEvent {
  return {
    timestampNs: "0",
    uati: 0,
    reason: 0,
    macIndex: 0,
    drcValue: 0,
    payload: new Uint8Array(0),
    reversePilotSnrDbTenths: 0,
    direction: 0,
    decodedMessages: [],
    payloadLengthBytes: 0,
    fullUati: undefined,
    receiveAti: 0,
  };
}

export const HrpdTrafficEvent: MessageFns<HrpdTrafficEvent> = {
  encode(message: HrpdTrafficEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestampNs !== "0") {
      writer.uint32(8).uint64(message.timestampNs);
    }
    if (message.uati !== 0) {
      writer.uint32(16).uint32(message.uati);
    }
    if (message.reason !== 0) {
      writer.uint32(24).int32(message.reason);
    }
    if (message.macIndex !== 0) {
      writer.uint32(32).uint32(message.macIndex);
    }
    if (message.drcValue !== 0) {
      writer.uint32(40).uint32(message.drcValue);
    }
    if (message.payload.length !== 0) {
      writer.uint32(50).bytes(message.payload);
    }
    if (message.reversePilotSnrDbTenths !== 0) {
      writer.uint32(56).sint32(message.reversePilotSnrDbTenths);
    }
    if (message.direction !== 0) {
      writer.uint32(64).int32(message.direction);
    }
    for (const v of message.decodedMessages) {
      HrpdDecodedMessage.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.payloadLengthBytes !== 0) {
      writer.uint32(80).uint32(message.payloadLengthBytes);
    }
    if (message.fullUati !== undefined) {
      HrpdUati.encode(message.fullUati, writer.uint32(90).fork()).join();
    }
    if (message.receiveAti !== 0) {
      writer.uint32(96).uint32(message.receiveAti);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HrpdTrafficEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHrpdTrafficEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestampNs = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.uati = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reason = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.macIndex = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.drcValue = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.reversePilotSnrDbTenths = reader.sint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.direction = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.decodedMessages.push(HrpdDecodedMessage.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.payloadLengthBytes = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.fullUati = HrpdUati.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.receiveAti = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HrpdTrafficEvent {
    return {
      timestampNs: isSet(object.timestampNs)
        ? globalThis.String(object.timestampNs)
        : isSet(object.timestamp_ns)
        ? globalThis.String(object.timestamp_ns)
        : "0",
      uati: isSet(object.uati) ? globalThis.Number(object.uati) : 0,
      reason: isSet(object.reason) ? hrpdTrafficReasonFromJSON(object.reason) : 0,
      macIndex: isSet(object.macIndex)
        ? globalThis.Number(object.macIndex)
        : isSet(object.mac_index)
        ? globalThis.Number(object.mac_index)
        : 0,
      drcValue: isSet(object.drcValue)
        ? globalThis.Number(object.drcValue)
        : isSet(object.drc_value)
        ? globalThis.Number(object.drc_value)
        : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      reversePilotSnrDbTenths: isSet(object.reversePilotSnrDbTenths)
        ? globalThis.Number(object.reversePilotSnrDbTenths)
        : isSet(object.reverse_pilot_snr_db_tenths)
        ? globalThis.Number(object.reverse_pilot_snr_db_tenths)
        : 0,
      direction: isSet(object.direction) ? hrpdDirectionFromJSON(object.direction) : 0,
      decodedMessages: globalThis.Array.isArray(object?.decodedMessages)
        ? object.decodedMessages.map((e: any) => HrpdDecodedMessage.fromJSON(e))
        : globalThis.Array.isArray(object?.decoded_messages)
        ? object.decoded_messages.map((e: any) => HrpdDecodedMessage.fromJSON(e))
        : [],
      payloadLengthBytes: isSet(object.payloadLengthBytes)
        ? globalThis.Number(object.payloadLengthBytes)
        : isSet(object.payload_length_bytes)
        ? globalThis.Number(object.payload_length_bytes)
        : 0,
      fullUati: isSet(object.fullUati)
        ? HrpdUati.fromJSON(object.fullUati)
        : isSet(object.full_uati)
        ? HrpdUati.fromJSON(object.full_uati)
        : undefined,
      receiveAti: isSet(object.receiveAti)
        ? globalThis.Number(object.receiveAti)
        : isSet(object.receive_ati)
        ? globalThis.Number(object.receive_ati)
        : 0,
    };
  },

  toJSON(message: HrpdTrafficEvent): unknown {
    const obj: any = {};
    if (message.timestampNs !== "0") {
      obj.timestampNs = globalThis.String(message.timestampNs);
    }
    if (message.uati !== 0) {
      obj.uati = Math.round(message.uati);
    }
    if (message.reason !== 0) {
      obj.reason = hrpdTrafficReasonToJSON(message.reason);
    }
    if (message.macIndex !== 0) {
      obj.macIndex = Math.round(message.macIndex);
    }
    if (message.drcValue !== 0) {
      obj.drcValue = Math.round(message.drcValue);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.reversePilotSnrDbTenths !== 0) {
      obj.reversePilotSnrDbTenths = Math.round(message.reversePilotSnrDbTenths);
    }
    if (message.direction !== 0) {
      obj.direction = hrpdDirectionToJSON(message.direction);
    }
    if (message.decodedMessages?.length) {
      obj.decodedMessages = message.decodedMessages.map((e) => HrpdDecodedMessage.toJSON(e));
    }
    if (message.payloadLengthBytes !== 0) {
      obj.payloadLengthBytes = Math.round(message.payloadLengthBytes);
    }
    if (message.fullUati !== undefined) {
      obj.fullUati = HrpdUati.toJSON(message.fullUati);
    }
    if (message.receiveAti !== 0) {
      obj.receiveAti = Math.round(message.receiveAti);
    }
    return obj;
  },

  create(base?: DeepPartial<HrpdTrafficEvent>): HrpdTrafficEvent {
    return HrpdTrafficEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HrpdTrafficEvent>): HrpdTrafficEvent {
    const message = createBaseHrpdTrafficEvent();
    message.timestampNs = object.timestampNs ?? "0";
    message.uati = object.uati ?? 0;
    message.reason = object.reason ?? 0;
    message.macIndex = object.macIndex ?? 0;
    message.drcValue = object.drcValue ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    message.reversePilotSnrDbTenths = object.reversePilotSnrDbTenths ?? 0;
    message.direction = object.direction ?? 0;
    message.decodedMessages = object.decodedMessages?.map((e) => HrpdDecodedMessage.fromPartial(e)) || [];
    message.payloadLengthBytes = object.payloadLengthBytes ?? 0;
    message.fullUati = (object.fullUati !== undefined && object.fullUati !== null)
      ? HrpdUati.fromPartial(object.fullUati)
      : undefined;
    message.receiveAti = object.receiveAti ?? 0;
    return message;
  },
};

function createBaseAnNetworkEvent(): AnNetworkEvent {
  return { session: undefined, access: undefined, traffic: undefined };
}

export const AnNetworkEvent: MessageFns<AnNetworkEvent> = {
  encode(message: AnNetworkEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      HrpdSessionEvent.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.access !== undefined) {
      HrpdAccessEvent.encode(message.access, writer.uint32(18).fork()).join();
    }
    if (message.traffic !== undefined) {
      HrpdTrafficEvent.encode(message.traffic, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnNetworkEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnNetworkEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = HrpdSessionEvent.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.access = HrpdAccessEvent.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.traffic = HrpdTrafficEvent.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnNetworkEvent {
    return {
      session: isSet(object.session) ? HrpdSessionEvent.fromJSON(object.session) : undefined,
      access: isSet(object.access) ? HrpdAccessEvent.fromJSON(object.access) : undefined,
      traffic: isSet(object.traffic) ? HrpdTrafficEvent.fromJSON(object.traffic) : undefined,
    };
  },

  toJSON(message: AnNetworkEvent): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = HrpdSessionEvent.toJSON(message.session);
    }
    if (message.access !== undefined) {
      obj.access = HrpdAccessEvent.toJSON(message.access);
    }
    if (message.traffic !== undefined) {
      obj.traffic = HrpdTrafficEvent.toJSON(message.traffic);
    }
    return obj;
  },

  create(base?: DeepPartial<AnNetworkEvent>): AnNetworkEvent {
    return AnNetworkEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnNetworkEvent>): AnNetworkEvent {
    const message = createBaseAnNetworkEvent();
    message.session = (object.session !== undefined && object.session !== null)
      ? HrpdSessionEvent.fromPartial(object.session)
      : undefined;
    message.access = (object.access !== undefined && object.access !== null)
      ? HrpdAccessEvent.fromPartial(object.access)
      : undefined;
    message.traffic = (object.traffic !== undefined && object.traffic !== null)
      ? HrpdTrafficEvent.fromPartial(object.traffic)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
