// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: events/v1/bsc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "events.v1";

/**
 * BSC-originated events. Empty placeholder; variants added in follow-ups
 * (bridging the existing AccessEvent / PagingEvent / TrafficEvent streams).
 */
export interface BscNetworkEvent {
}

function createBaseBscNetworkEvent(): BscNetworkEvent {
  return {};
}

export const BscNetworkEvent: MessageFns<BscNetworkEvent> = {
  encode(_: BscNetworkEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BscNetworkEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBscNetworkEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): BscNetworkEvent {
    return {};
  },

  toJSON(_: BscNetworkEvent): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<BscNetworkEvent>): BscNetworkEvent {
    return BscNetworkEvent.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<BscNetworkEvent>): BscNetworkEvent {
    const message = createBaseBscNetworkEvent();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
