// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: events/v1/bts.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "events.v1";

/** BTS-originated events. Empty placeholder. */
export interface BtsNetworkEvent {
}

function createBaseBtsNetworkEvent(): BtsNetworkEvent {
  return {};
}

export const BtsNetworkEvent: MessageFns<BtsNetworkEvent> = {
  encode(_: BtsNetworkEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BtsNetworkEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBtsNetworkEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): BtsNetworkEvent {
    return {};
  },

  toJSON(_: BtsNetworkEvent): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<BtsNetworkEvent>): BtsNetworkEvent {
    return BtsNetworkEvent.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<BtsNetworkEvent>): BtsNetworkEvent {
    const message = createBaseBtsNetworkEvent();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
