// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: events/v1/cell.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "events.v1";

/**
 * Cell that served an air-interface transaction, mirroring the Abis Cell
 * Identifier IE (A.S0003-A 7.5).
 */
export interface CellId {
  /** Cell number broadcast as BASE_ID. */
  cell: number;
  /** Sector within the cell. */
  sector: number;
}

function createBaseCellId(): CellId {
  return { cell: 0, sector: 0 };
}

export const CellId: MessageFns<CellId> = {
  encode(message: CellId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cell !== 0) {
      writer.uint32(8).uint32(message.cell);
    }
    if (message.sector !== 0) {
      writer.uint32(16).uint32(message.sector);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CellId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCellId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cell = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sector = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CellId {
    return {
      cell: isSet(object.cell) ? globalThis.Number(object.cell) : 0,
      sector: isSet(object.sector) ? globalThis.Number(object.sector) : 0,
    };
  },

  toJSON(message: CellId): unknown {
    const obj: any = {};
    if (message.cell !== 0) {
      obj.cell = Math.round(message.cell);
    }
    if (message.sector !== 0) {
      obj.sector = Math.round(message.sector);
    }
    return obj;
  },

  create(base?: DeepPartial<CellId>): CellId {
    return CellId.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CellId>): CellId {
    const message = createBaseCellId();
    message.cell = object.cell ?? 0;
    message.sector = object.sector ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
