// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: events/v1/pdsn.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "events.v1";

/**
 * CDMA Service Option per 3GPP2 / IS-707. Variant numbers equal the
 * standard SO wire value, so producers may also set this field to a raw
 * integer SO not yet listed here and consumers will receive the number
 * untranslated.
 */
export enum ServiceOption {
  SERVICE_OPTION_UNSPECIFIED = 0,
  /** SERVICE_OPTION_VOICE_8K - SO1 — basic voice (8 kbps QCELP). */
  SERVICE_OPTION_VOICE_8K = 1,
  /** SERVICE_OPTION_EVRC - SO3 — EVRC voice (8 kbps). */
  SERVICE_OPTION_EVRC = 3,
  /** SERVICE_OPTION_SMS - SO6 — SMS (short message service). */
  SERVICE_OPTION_SMS = 6,
  /** SERVICE_OPTION_PACKET_DATA_RC1 - SO7 — packet data, RLP Type 1 (legacy). */
  SERVICE_OPTION_PACKET_DATA_RC1 = 7,
  /** SERVICE_OPTION_PACKET_DATA_RC3 - SO33 — packet data, RLP Type 3 (cdma2000). */
  SERVICE_OPTION_PACKET_DATA_RC3 = 33,
  /** SERVICE_OPTION_EVRC_B - SO68 — EVRC-B voice. */
  SERVICE_OPTION_EVRC_B = 68,
  /** SERVICE_OPTION_SMS_EXT - SO70 — extended SMS encoding. */
  SERVICE_OPTION_SMS_EXT = 70,
  UNRECOGNIZED = -1,
}

export function serviceOptionFromJSON(object: any): ServiceOption {
  switch (object) {
    case 0:
    case "SERVICE_OPTION_UNSPECIFIED":
      return ServiceOption.SERVICE_OPTION_UNSPECIFIED;
    case 1:
    case "SERVICE_OPTION_VOICE_8K":
      return ServiceOption.SERVICE_OPTION_VOICE_8K;
    case 3:
    case "SERVICE_OPTION_EVRC":
      return ServiceOption.SERVICE_OPTION_EVRC;
    case 6:
    case "SERVICE_OPTION_SMS":
      return ServiceOption.SERVICE_OPTION_SMS;
    case 7:
    case "SERVICE_OPTION_PACKET_DATA_RC1":
      return ServiceOption.SERVICE_OPTION_PACKET_DATA_RC1;
    case 33:
    case "SERVICE_OPTION_PACKET_DATA_RC3":
      return ServiceOption.SERVICE_OPTION_PACKET_DATA_RC3;
    case 68:
    case "SERVICE_OPTION_EVRC_B":
      return ServiceOption.SERVICE_OPTION_EVRC_B;
    case 70:
    case "SERVICE_OPTION_SMS_EXT":
      return ServiceOption.SERVICE_OPTION_SMS_EXT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ServiceOption.UNRECOGNIZED;
  }
}

export function serviceOptionToJSON(object: ServiceOption): string {
  switch (object) {
    case ServiceOption.SERVICE_OPTION_UNSPECIFIED:
      return "SERVICE_OPTION_UNSPECIFIED";
    case ServiceOption.SERVICE_OPTION_VOICE_8K:
      return "SERVICE_OPTION_VOICE_8K";
    case ServiceOption.SERVICE_OPTION_EVRC:
      return "SERVICE_OPTION_EVRC";
    case ServiceOption.SERVICE_OPTION_SMS:
      return "SERVICE_OPTION_SMS";
    case ServiceOption.SERVICE_OPTION_PACKET_DATA_RC1:
      return "SERVICE_OPTION_PACKET_DATA_RC1";
    case ServiceOption.SERVICE_OPTION_PACKET_DATA_RC3:
      return "SERVICE_OPTION_PACKET_DATA_RC3";
    case ServiceOption.SERVICE_OPTION_EVRC_B:
      return "SERVICE_OPTION_EVRC_B";
    case ServiceOption.SERVICE_OPTION_SMS_EXT:
      return "SERVICE_OPTION_SMS_EXT";
    case ServiceOption.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum PacketSessionUnbindReason {
  PACKET_SESSION_UNBIND_REASON_UNSPECIFIED = 0,
  /** PACKET_SESSION_UNBIND_REASON_UPLINK_CLOSED - Mobile dropped the session (uplink channel closed). */
  PACKET_SESSION_UNBIND_REASON_UPLINK_CLOSED = 1,
  UNRECOGNIZED = -1,
}

export function packetSessionUnbindReasonFromJSON(object: any): PacketSessionUnbindReason {
  switch (object) {
    case 0:
    case "PACKET_SESSION_UNBIND_REASON_UNSPECIFIED":
      return PacketSessionUnbindReason.PACKET_SESSION_UNBIND_REASON_UNSPECIFIED;
    case 1:
    case "PACKET_SESSION_UNBIND_REASON_UPLINK_CLOSED":
      return PacketSessionUnbindReason.PACKET_SESSION_UNBIND_REASON_UPLINK_CLOSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PacketSessionUnbindReason.UNRECOGNIZED;
  }
}

export function packetSessionUnbindReasonToJSON(object: PacketSessionUnbindReason): string {
  switch (object) {
    case PacketSessionUnbindReason.PACKET_SESSION_UNBIND_REASON_UNSPECIFIED:
      return "PACKET_SESSION_UNBIND_REASON_UNSPECIFIED";
    case PacketSessionUnbindReason.PACKET_SESSION_UNBIND_REASON_UPLINK_CLOSED:
      return "PACKET_SESSION_UNBIND_REASON_UPLINK_CLOSED";
    case PacketSessionUnbindReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** PDSN-originated events. */
export interface PdsnNetworkEvent {
  bound?: PacketSessionBound | undefined;
  unbound?: PacketSessionUnbound | undefined;
}

/**
 * A packet-data session has been established: a mobile now owns an IP.
 * Subscriber/identity context for the mobile lives in the NetworkEvent
 * envelope; this message carries only the session-specific details.
 */
export interface PacketSessionBound {
  sessionId: string;
  mobileIp: string;
  pdsnIp: string;
  serviceOption: ServiceOption;
}

/** A packet-data session has been torn down: the IP is released. */
export interface PacketSessionUnbound {
  sessionId: string;
  mobileIp: string;
  reason: PacketSessionUnbindReason;
}

function createBasePdsnNetworkEvent(): PdsnNetworkEvent {
  return { bound: undefined, unbound: undefined };
}

export const PdsnNetworkEvent: MessageFns<PdsnNetworkEvent> = {
  encode(message: PdsnNetworkEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bound !== undefined) {
      PacketSessionBound.encode(message.bound, writer.uint32(10).fork()).join();
    }
    if (message.unbound !== undefined) {
      PacketSessionUnbound.encode(message.unbound, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PdsnNetworkEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePdsnNetworkEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bound = PacketSessionBound.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.unbound = PacketSessionUnbound.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PdsnNetworkEvent {
    return {
      bound: isSet(object.bound) ? PacketSessionBound.fromJSON(object.bound) : undefined,
      unbound: isSet(object.unbound) ? PacketSessionUnbound.fromJSON(object.unbound) : undefined,
    };
  },

  toJSON(message: PdsnNetworkEvent): unknown {
    const obj: any = {};
    if (message.bound !== undefined) {
      obj.bound = PacketSessionBound.toJSON(message.bound);
    }
    if (message.unbound !== undefined) {
      obj.unbound = PacketSessionUnbound.toJSON(message.unbound);
    }
    return obj;
  },

  create(base?: DeepPartial<PdsnNetworkEvent>): PdsnNetworkEvent {
    return PdsnNetworkEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PdsnNetworkEvent>): PdsnNetworkEvent {
    const message = createBasePdsnNetworkEvent();
    message.bound = (object.bound !== undefined && object.bound !== null)
      ? PacketSessionBound.fromPartial(object.bound)
      : undefined;
    message.unbound = (object.unbound !== undefined && object.unbound !== null)
      ? PacketSessionUnbound.fromPartial(object.unbound)
      : undefined;
    return message;
  },
};

function createBasePacketSessionBound(): PacketSessionBound {
  return { sessionId: "", mobileIp: "", pdsnIp: "", serviceOption: 0 };
}

export const PacketSessionBound: MessageFns<PacketSessionBound> = {
  encode(message: PacketSessionBound, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.mobileIp !== "") {
      writer.uint32(18).string(message.mobileIp);
    }
    if (message.pdsnIp !== "") {
      writer.uint32(26).string(message.pdsnIp);
    }
    if (message.serviceOption !== 0) {
      writer.uint32(32).int32(message.serviceOption);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketSessionBound {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketSessionBound();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mobileIp = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pdsnIp = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.serviceOption = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketSessionBound {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      mobileIp: isSet(object.mobileIp)
        ? globalThis.String(object.mobileIp)
        : isSet(object.mobile_ip)
        ? globalThis.String(object.mobile_ip)
        : "",
      pdsnIp: isSet(object.pdsnIp)
        ? globalThis.String(object.pdsnIp)
        : isSet(object.pdsn_ip)
        ? globalThis.String(object.pdsn_ip)
        : "",
      serviceOption: isSet(object.serviceOption)
        ? serviceOptionFromJSON(object.serviceOption)
        : isSet(object.service_option)
        ? serviceOptionFromJSON(object.service_option)
        : 0,
    };
  },

  toJSON(message: PacketSessionBound): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.mobileIp !== "") {
      obj.mobileIp = message.mobileIp;
    }
    if (message.pdsnIp !== "") {
      obj.pdsnIp = message.pdsnIp;
    }
    if (message.serviceOption !== 0) {
      obj.serviceOption = serviceOptionToJSON(message.serviceOption);
    }
    return obj;
  },

  create(base?: DeepPartial<PacketSessionBound>): PacketSessionBound {
    return PacketSessionBound.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PacketSessionBound>): PacketSessionBound {
    const message = createBasePacketSessionBound();
    message.sessionId = object.sessionId ?? "";
    message.mobileIp = object.mobileIp ?? "";
    message.pdsnIp = object.pdsnIp ?? "";
    message.serviceOption = object.serviceOption ?? 0;
    return message;
  },
};

function createBasePacketSessionUnbound(): PacketSessionUnbound {
  return { sessionId: "", mobileIp: "", reason: 0 };
}

export const PacketSessionUnbound: MessageFns<PacketSessionUnbound> = {
  encode(message: PacketSessionUnbound, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.mobileIp !== "") {
      writer.uint32(18).string(message.mobileIp);
    }
    if (message.reason !== 0) {
      writer.uint32(24).int32(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketSessionUnbound {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketSessionUnbound();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mobileIp = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reason = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketSessionUnbound {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      mobileIp: isSet(object.mobileIp)
        ? globalThis.String(object.mobileIp)
        : isSet(object.mobile_ip)
        ? globalThis.String(object.mobile_ip)
        : "",
      reason: isSet(object.reason) ? packetSessionUnbindReasonFromJSON(object.reason) : 0,
    };
  },

  toJSON(message: PacketSessionUnbound): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.mobileIp !== "") {
      obj.mobileIp = message.mobileIp;
    }
    if (message.reason !== 0) {
      obj.reason = packetSessionUnbindReasonToJSON(message.reason);
    }
    return obj;
  },

  create(base?: DeepPartial<PacketSessionUnbound>): PacketSessionUnbound {
    return PacketSessionUnbound.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PacketSessionUnbound>): PacketSessionUnbound {
    const message = createBasePacketSessionUnbound();
    message.sessionId = object.sessionId ?? "";
    message.mobileIp = object.mobileIp ?? "";
    message.reason = object.reason ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
