// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: base_station/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { CellId } from "../../bsc/v1/service";

export const protobufPackage = "base_station.v1";

export interface EnrollRequest {
}

export interface EnrollResponse {
  /**
   * Stable identifier the node writes into registration bindings. Unique
   * across every base station one MSC serves.
   */
  nodeId: string;
  /** Address the node's A1 signaling listener accepts the MSC on. */
  a1Addr: string;
  cells: ServedCell[];
}

/** One cell a base station serves, with the identity it broadcasts. */
export interface ServedCell {
  cell: CellId | undefined;
  sid: number;
  nid: number;
  /** Decimal digits as broadcast, e.g. "310". */
  mccDigits: string;
  /** Decimal digits as broadcast, e.g. "00". */
  imsi1112Digits: string;
  /** Whether the cell currently carries traffic. */
  inService: boolean;
}

function createBaseEnrollRequest(): EnrollRequest {
  return {};
}

export const EnrollRequest: MessageFns<EnrollRequest> = {
  encode(_: EnrollRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EnrollRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnrollRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EnrollRequest {
    return {};
  },

  toJSON(_: EnrollRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<EnrollRequest>): EnrollRequest {
    return EnrollRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<EnrollRequest>): EnrollRequest {
    const message = createBaseEnrollRequest();
    return message;
  },
};

function createBaseEnrollResponse(): EnrollResponse {
  return { nodeId: "", a1Addr: "", cells: [] };
}

export const EnrollResponse: MessageFns<EnrollResponse> = {
  encode(message: EnrollResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.a1Addr !== "") {
      writer.uint32(18).string(message.a1Addr);
    }
    for (const v of message.cells) {
      ServedCell.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EnrollResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnrollResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.a1Addr = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cells.push(ServedCell.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EnrollResponse {
    return {
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      a1Addr: isSet(object.a1Addr)
        ? globalThis.String(object.a1Addr)
        : isSet(object.a1_addr)
        ? globalThis.String(object.a1_addr)
        : "",
      cells: globalThis.Array.isArray(object?.cells) ? object.cells.map((e: any) => ServedCell.fromJSON(e)) : [],
    };
  },

  toJSON(message: EnrollResponse): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.a1Addr !== "") {
      obj.a1Addr = message.a1Addr;
    }
    if (message.cells?.length) {
      obj.cells = message.cells.map((e) => ServedCell.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<EnrollResponse>): EnrollResponse {
    return EnrollResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EnrollResponse>): EnrollResponse {
    const message = createBaseEnrollResponse();
    message.nodeId = object.nodeId ?? "";
    message.a1Addr = object.a1Addr ?? "";
    message.cells = object.cells?.map((e) => ServedCell.fromPartial(e)) || [];
    return message;
  },
};

function createBaseServedCell(): ServedCell {
  return { cell: undefined, sid: 0, nid: 0, mccDigits: "", imsi1112Digits: "", inService: false };
}

export const ServedCell: MessageFns<ServedCell> = {
  encode(message: ServedCell, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cell !== undefined) {
      CellId.encode(message.cell, writer.uint32(10).fork()).join();
    }
    if (message.sid !== 0) {
      writer.uint32(16).uint32(message.sid);
    }
    if (message.nid !== 0) {
      writer.uint32(24).uint32(message.nid);
    }
    if (message.mccDigits !== "") {
      writer.uint32(34).string(message.mccDigits);
    }
    if (message.imsi1112Digits !== "") {
      writer.uint32(42).string(message.imsi1112Digits);
    }
    if (message.inService !== false) {
      writer.uint32(48).bool(message.inService);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServedCell {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServedCell();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cell = CellId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sid = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.nid = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.mccDigits = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.imsi1112Digits = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.inService = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServedCell {
    return {
      cell: isSet(object.cell) ? CellId.fromJSON(object.cell) : undefined,
      sid: isSet(object.sid) ? globalThis.Number(object.sid) : 0,
      nid: isSet(object.nid) ? globalThis.Number(object.nid) : 0,
      mccDigits: isSet(object.mccDigits)
        ? globalThis.String(object.mccDigits)
        : isSet(object.mcc_digits)
        ? globalThis.String(object.mcc_digits)
        : "",
      imsi1112Digits: isSet(object.imsi1112Digits)
        ? globalThis.String(object.imsi1112Digits)
        : isSet(object.imsi_11_12_digits)
        ? globalThis.String(object.imsi_11_12_digits)
        : "",
      inService: isSet(object.inService)
        ? globalThis.Boolean(object.inService)
        : isSet(object.in_service)
        ? globalThis.Boolean(object.in_service)
        : false,
    };
  },

  toJSON(message: ServedCell): unknown {
    const obj: any = {};
    if (message.cell !== undefined) {
      obj.cell = CellId.toJSON(message.cell);
    }
    if (message.sid !== 0) {
      obj.sid = Math.round(message.sid);
    }
    if (message.nid !== 0) {
      obj.nid = Math.round(message.nid);
    }
    if (message.mccDigits !== "") {
      obj.mccDigits = message.mccDigits;
    }
    if (message.imsi1112Digits !== "") {
      obj.imsi1112Digits = message.imsi1112Digits;
    }
    if (message.inService !== false) {
      obj.inService = message.inService;
    }
    return obj;
  },

  create(base?: DeepPartial<ServedCell>): ServedCell {
    return ServedCell.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ServedCell>): ServedCell {
    const message = createBaseServedCell();
    message.cell = (object.cell !== undefined && object.cell !== null) ? CellId.fromPartial(object.cell) : undefined;
    message.sid = object.sid ?? 0;
    message.nid = object.nid ?? 0;
    message.mccDigits = object.mccDigits ?? "";
    message.imsi1112Digits = object.imsi1112Digits ?? "";
    message.inService = object.inService ?? false;
    return message;
  },
};

/**
 * Identity and served cells of a base station, the element that terminates
 * A1 toward the MSC. A BSC is a base station serving every cell enrolled with
 * it. Enrollment precedes the A1 dial, so identity never rides A1.
 */
export type BaseStationServiceDefinition = typeof BaseStationServiceDefinition;
export const BaseStationServiceDefinition = {
  name: "BaseStationService",
  fullName: "base_station.v1.BaseStationService",
  methods: {
    /**
     * Returns the node as it stands. Every call reports the current served
     * cells, so calling again refreshes them.
     */
    enroll: {
      name: "Enroll",
      requestType: EnrollRequest as typeof EnrollRequest,
      requestStream: false,
      responseType: EnrollResponse as typeof EnrollResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface BaseStationServiceImplementation<CallContextExt = {}> {
  /**
   * Returns the node as it stands. Every call reports the current served
   * cells, so calling again refreshes them.
   */
  enroll(request: EnrollRequest, context: CallContext & CallContextExt): Promise<DeepPartial<EnrollResponse>>;
}

export interface BaseStationServiceClient<CallOptionsExt = {}> {
  /**
   * Returns the node as it stands. Every call reports the current served
   * cells, so calling again refreshes them.
   */
  enroll(request: DeepPartial<EnrollRequest>, options?: CallOptions & CallOptionsExt): Promise<EnrollResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
