[package]
name = "cdma-abis"
version = "0.1.0"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Abis control and bearer transport types for 1xBTS BTS/BSC communication."

[dependencies]
log = "0.4"
parking_lot = "0.12"
tokio = { version = "1", features = ["net", "io-util", "sync", "macros", "rt", "time"] }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
