// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: smsc/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "smsc.v1";

/** SMS submission accepted by the SMSC. */
export interface SmsSubmission {
  /** UUID */
  smsId: string;
  originatingNumber: string;
  /** set when targeting by phone */
  destinationNumber?: string | undefined;
  originatingSubscriberId?: string | undefined;
  destinationSubscriberId?: string | undefined;
  text: string;
  /** "accepted", "paging", "page_response_received", "sent", "failed", "expired" */
  state: string;
  failureReason?: string | undefined;
  createdAt: Date | undefined;
  updatedAt:
    | Date
    | undefined;
  /** set when targeting by ESN */
  destinationEsn?:
    | number
    | undefined;
  /** set when targeting by IMSI/IMSI_S digits */
  destinationImsi?: string | undefined;
}

/** One delivery attempt for an SMS submission. */
export interface SmsDeliveryAttempt {
  /** UUID */
  smsDeliveryAttemptId: string;
  /** FK */
  smsId: string;
  attemptNumber: number;
  /** "queued", "paging", "page_response_received", "forward_sent", "failed", "expired" */
  state: string;
  /** absent for unprovisioned MS */
  targetSubscriberId?: string | undefined;
  failureReason?: string | undefined;
  requestedAt: Date | undefined;
  completedAt?: Date | undefined;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

/** MO SMS deduplication fingerprint extracted from teleservice payloads. */
export interface MoSmsFingerprint {
  teleserviceId: number;
  messageType: number;
  messageId: number;
}

/** Creates an SMS submission for later routing and delivery. */
export interface CreateSmsSubmissionRequest {
  originatingNumber: string;
  /** set one of the three destination fields */
  destinationNumber?: string | undefined;
  text: string;
  originatingSubscriberId?: string | undefined;
  destinationSubscriberId?: string | undefined;
  destinationEsn?: number | undefined;
  destinationImsi?: string | undefined;
}

/** Created SMS submission. */
export interface CreateSmsSubmissionResponse {
  submission: SmsSubmission | undefined;
}

/** Creates an MO SMS submission or returns a recent matching duplicate. */
export interface CreateOrGetRecentMoSubmissionRequest {
  originatingNumber: string;
  destinationNumber: string;
  text: string;
  originatingSubscriberId?: string | undefined;
  destinationSubscriberId?: string | undefined;
  fingerprint: MoSmsFingerprint | undefined;
}

export interface CreateOrGetRecentMoSubmissionResponse {
  submission: SmsSubmission | undefined;
  created: boolean;
}

/** Updates the state of an SMS submission. */
export interface UpdateSmsSubmissionStateRequest {
  smsId: string;
  state: string;
  failureReason?: string | undefined;
}

/** Updated SMS submission. */
export interface UpdateSmsSubmissionStateResponse {
  submission: SmsSubmission | undefined;
}

/** Looks up one SMS submission. */
export interface GetSmsSubmissionRequest {
  smsId: string;
}

/** SMS submission plus its delivery attempts. */
export interface GetSmsSubmissionResponse {
  submission: SmsSubmission | undefined;
  deliveryAttempts: SmsDeliveryAttempt[];
}

/** Paged/filterable request for SMS submission list views. */
export interface ListSmsSubmissionsRequest {
  limit?: number | undefined;
  offset?: number | undefined;
  destinationNumber?: string | undefined;
  state?: string | undefined;
  destinationEsn?: number | undefined;
  destinationImsi?: string | undefined;
}

/** SMS submission list page and total count. */
export interface ListSmsSubmissionsResponse {
  submissions: SmsSubmission[];
  total: number;
}

/** Creates a new delivery attempt for a submission. */
export interface CreateDeliveryAttemptRequest {
  smsId: string;
  /** omit for unprovisioned MS */
  targetSubscriberId?: string | undefined;
}

/** Created delivery attempt. */
export interface CreateDeliveryAttemptResponse {
  attempt: SmsDeliveryAttempt | undefined;
}

/** Updates the state of one delivery attempt. */
export interface UpdateDeliveryAttemptStateRequest {
  smsDeliveryAttemptId: string;
  state: string;
  failureReason?: string | undefined;
}

/** Updated delivery attempt. */
export interface UpdateDeliveryAttemptStateResponse {
  attempt: SmsDeliveryAttempt | undefined;
}

/** Assigns or updates the resolved destination subscriber for a submission. */
export interface UpdateDestinationSubscriberRequest {
  smsId: string;
  destinationSubscriberId: string;
}

function createBaseSmsSubmission(): SmsSubmission {
  return {
    smsId: "",
    originatingNumber: "",
    destinationNumber: undefined,
    originatingSubscriberId: undefined,
    destinationSubscriberId: undefined,
    text: "",
    state: "",
    failureReason: undefined,
    createdAt: undefined,
    updatedAt: undefined,
    destinationEsn: undefined,
    destinationImsi: undefined,
  };
}

export const SmsSubmission: MessageFns<SmsSubmission> = {
  encode(message: SmsSubmission, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smsId !== "") {
      writer.uint32(10).string(message.smsId);
    }
    if (message.originatingNumber !== "") {
      writer.uint32(18).string(message.originatingNumber);
    }
    if (message.destinationNumber !== undefined) {
      writer.uint32(26).string(message.destinationNumber);
    }
    if (message.originatingSubscriberId !== undefined) {
      writer.uint32(34).string(message.originatingSubscriberId);
    }
    if (message.destinationSubscriberId !== undefined) {
      writer.uint32(42).string(message.destinationSubscriberId);
    }
    if (message.text !== "") {
      writer.uint32(50).string(message.text);
    }
    if (message.state !== "") {
      writer.uint32(58).string(message.state);
    }
    if (message.failureReason !== undefined) {
      writer.uint32(66).string(message.failureReason);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(74).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(82).fork()).join();
    }
    if (message.destinationEsn !== undefined) {
      writer.uint32(88).uint64(message.destinationEsn);
    }
    if (message.destinationImsi !== undefined) {
      writer.uint32(98).string(message.destinationImsi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SmsSubmission {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSmsSubmission();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smsId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.originatingNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.destinationNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.originatingSubscriberId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.destinationSubscriberId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.failureReason = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.destinationEsn = longToNumber(reader.uint64());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.destinationImsi = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SmsSubmission {
    return {
      smsId: isSet(object.smsId)
        ? globalThis.String(object.smsId)
        : isSet(object.sms_id)
        ? globalThis.String(object.sms_id)
        : "",
      originatingNumber: isSet(object.originatingNumber)
        ? globalThis.String(object.originatingNumber)
        : isSet(object.originating_number)
        ? globalThis.String(object.originating_number)
        : "",
      destinationNumber: isSet(object.destinationNumber)
        ? globalThis.String(object.destinationNumber)
        : isSet(object.destination_number)
        ? globalThis.String(object.destination_number)
        : undefined,
      originatingSubscriberId: isSet(object.originatingSubscriberId)
        ? globalThis.String(object.originatingSubscriberId)
        : isSet(object.originating_subscriber_id)
        ? globalThis.String(object.originating_subscriber_id)
        : undefined,
      destinationSubscriberId: isSet(object.destinationSubscriberId)
        ? globalThis.String(object.destinationSubscriberId)
        : isSet(object.destination_subscriber_id)
        ? globalThis.String(object.destination_subscriber_id)
        : undefined,
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      failureReason: isSet(object.failureReason)
        ? globalThis.String(object.failureReason)
        : isSet(object.failure_reason)
        ? globalThis.String(object.failure_reason)
        : undefined,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
      updatedAt: isSet(object.updatedAt)
        ? fromJsonTimestamp(object.updatedAt)
        : isSet(object.updated_at)
        ? fromJsonTimestamp(object.updated_at)
        : undefined,
      destinationEsn: isSet(object.destinationEsn)
        ? globalThis.Number(object.destinationEsn)
        : isSet(object.destination_esn)
        ? globalThis.Number(object.destination_esn)
        : undefined,
      destinationImsi: isSet(object.destinationImsi)
        ? globalThis.String(object.destinationImsi)
        : isSet(object.destination_imsi)
        ? globalThis.String(object.destination_imsi)
        : undefined,
    };
  },

  toJSON(message: SmsSubmission): unknown {
    const obj: any = {};
    if (message.smsId !== "") {
      obj.smsId = message.smsId;
    }
    if (message.originatingNumber !== "") {
      obj.originatingNumber = message.originatingNumber;
    }
    if (message.destinationNumber !== undefined) {
      obj.destinationNumber = message.destinationNumber;
    }
    if (message.originatingSubscriberId !== undefined) {
      obj.originatingSubscriberId = message.originatingSubscriberId;
    }
    if (message.destinationSubscriberId !== undefined) {
      obj.destinationSubscriberId = message.destinationSubscriberId;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.failureReason !== undefined) {
      obj.failureReason = message.failureReason;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    if (message.destinationEsn !== undefined) {
      obj.destinationEsn = Math.round(message.destinationEsn);
    }
    if (message.destinationImsi !== undefined) {
      obj.destinationImsi = message.destinationImsi;
    }
    return obj;
  },

  create(base?: DeepPartial<SmsSubmission>): SmsSubmission {
    return SmsSubmission.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SmsSubmission>): SmsSubmission {
    const message = createBaseSmsSubmission();
    message.smsId = object.smsId ?? "";
    message.originatingNumber = object.originatingNumber ?? "";
    message.destinationNumber = object.destinationNumber ?? undefined;
    message.originatingSubscriberId = object.originatingSubscriberId ?? undefined;
    message.destinationSubscriberId = object.destinationSubscriberId ?? undefined;
    message.text = object.text ?? "";
    message.state = object.state ?? "";
    message.failureReason = object.failureReason ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    message.destinationEsn = object.destinationEsn ?? undefined;
    message.destinationImsi = object.destinationImsi ?? undefined;
    return message;
  },
};

function createBaseSmsDeliveryAttempt(): SmsDeliveryAttempt {
  return {
    smsDeliveryAttemptId: "",
    smsId: "",
    attemptNumber: 0,
    state: "",
    targetSubscriberId: undefined,
    failureReason: undefined,
    requestedAt: undefined,
    completedAt: undefined,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const SmsDeliveryAttempt: MessageFns<SmsDeliveryAttempt> = {
  encode(message: SmsDeliveryAttempt, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smsDeliveryAttemptId !== "") {
      writer.uint32(10).string(message.smsDeliveryAttemptId);
    }
    if (message.smsId !== "") {
      writer.uint32(18).string(message.smsId);
    }
    if (message.attemptNumber !== 0) {
      writer.uint32(24).uint32(message.attemptNumber);
    }
    if (message.state !== "") {
      writer.uint32(34).string(message.state);
    }
    if (message.targetSubscriberId !== undefined) {
      writer.uint32(42).string(message.targetSubscriberId);
    }
    if (message.failureReason !== undefined) {
      writer.uint32(50).string(message.failureReason);
    }
    if (message.requestedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.requestedAt), writer.uint32(58).fork()).join();
    }
    if (message.completedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.completedAt), writer.uint32(66).fork()).join();
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(74).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SmsDeliveryAttempt {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSmsDeliveryAttempt();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smsDeliveryAttemptId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.smsId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.attemptNumber = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.targetSubscriberId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.failureReason = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.requestedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.completedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SmsDeliveryAttempt {
    return {
      smsDeliveryAttemptId: isSet(object.smsDeliveryAttemptId)
        ? globalThis.String(object.smsDeliveryAttemptId)
        : isSet(object.sms_delivery_attempt_id)
        ? globalThis.String(object.sms_delivery_attempt_id)
        : "",
      smsId: isSet(object.smsId)
        ? globalThis.String(object.smsId)
        : isSet(object.sms_id)
        ? globalThis.String(object.sms_id)
        : "",
      attemptNumber: isSet(object.attemptNumber)
        ? globalThis.Number(object.attemptNumber)
        : isSet(object.attempt_number)
        ? globalThis.Number(object.attempt_number)
        : 0,
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      targetSubscriberId: isSet(object.targetSubscriberId)
        ? globalThis.String(object.targetSubscriberId)
        : isSet(object.target_subscriber_id)
        ? globalThis.String(object.target_subscriber_id)
        : undefined,
      failureReason: isSet(object.failureReason)
        ? globalThis.String(object.failureReason)
        : isSet(object.failure_reason)
        ? globalThis.String(object.failure_reason)
        : undefined,
      requestedAt: isSet(object.requestedAt)
        ? fromJsonTimestamp(object.requestedAt)
        : isSet(object.requested_at)
        ? fromJsonTimestamp(object.requested_at)
        : undefined,
      completedAt: isSet(object.completedAt)
        ? fromJsonTimestamp(object.completedAt)
        : isSet(object.completed_at)
        ? fromJsonTimestamp(object.completed_at)
        : undefined,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
      updatedAt: isSet(object.updatedAt)
        ? fromJsonTimestamp(object.updatedAt)
        : isSet(object.updated_at)
        ? fromJsonTimestamp(object.updated_at)
        : undefined,
    };
  },

  toJSON(message: SmsDeliveryAttempt): unknown {
    const obj: any = {};
    if (message.smsDeliveryAttemptId !== "") {
      obj.smsDeliveryAttemptId = message.smsDeliveryAttemptId;
    }
    if (message.smsId !== "") {
      obj.smsId = message.smsId;
    }
    if (message.attemptNumber !== 0) {
      obj.attemptNumber = Math.round(message.attemptNumber);
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.targetSubscriberId !== undefined) {
      obj.targetSubscriberId = message.targetSubscriberId;
    }
    if (message.failureReason !== undefined) {
      obj.failureReason = message.failureReason;
    }
    if (message.requestedAt !== undefined) {
      obj.requestedAt = message.requestedAt.toISOString();
    }
    if (message.completedAt !== undefined) {
      obj.completedAt = message.completedAt.toISOString();
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<SmsDeliveryAttempt>): SmsDeliveryAttempt {
    return SmsDeliveryAttempt.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SmsDeliveryAttempt>): SmsDeliveryAttempt {
    const message = createBaseSmsDeliveryAttempt();
    message.smsDeliveryAttemptId = object.smsDeliveryAttemptId ?? "";
    message.smsId = object.smsId ?? "";
    message.attemptNumber = object.attemptNumber ?? 0;
    message.state = object.state ?? "";
    message.targetSubscriberId = object.targetSubscriberId ?? undefined;
    message.failureReason = object.failureReason ?? undefined;
    message.requestedAt = object.requestedAt ?? undefined;
    message.completedAt = object.completedAt ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseMoSmsFingerprint(): MoSmsFingerprint {
  return { teleserviceId: 0, messageType: 0, messageId: 0 };
}

export const MoSmsFingerprint: MessageFns<MoSmsFingerprint> = {
  encode(message: MoSmsFingerprint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.teleserviceId !== 0) {
      writer.uint32(8).uint32(message.teleserviceId);
    }
    if (message.messageType !== 0) {
      writer.uint32(16).uint32(message.messageType);
    }
    if (message.messageId !== 0) {
      writer.uint32(24).uint32(message.messageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MoSmsFingerprint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoSmsFingerprint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.teleserviceId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.messageType = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.messageId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MoSmsFingerprint {
    return {
      teleserviceId: isSet(object.teleserviceId)
        ? globalThis.Number(object.teleserviceId)
        : isSet(object.teleservice_id)
        ? globalThis.Number(object.teleservice_id)
        : 0,
      messageType: isSet(object.messageType)
        ? globalThis.Number(object.messageType)
        : isSet(object.message_type)
        ? globalThis.Number(object.message_type)
        : 0,
      messageId: isSet(object.messageId)
        ? globalThis.Number(object.messageId)
        : isSet(object.message_id)
        ? globalThis.Number(object.message_id)
        : 0,
    };
  },

  toJSON(message: MoSmsFingerprint): unknown {
    const obj: any = {};
    if (message.teleserviceId !== 0) {
      obj.teleserviceId = Math.round(message.teleserviceId);
    }
    if (message.messageType !== 0) {
      obj.messageType = Math.round(message.messageType);
    }
    if (message.messageId !== 0) {
      obj.messageId = Math.round(message.messageId);
    }
    return obj;
  },

  create(base?: DeepPartial<MoSmsFingerprint>): MoSmsFingerprint {
    return MoSmsFingerprint.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MoSmsFingerprint>): MoSmsFingerprint {
    const message = createBaseMoSmsFingerprint();
    message.teleserviceId = object.teleserviceId ?? 0;
    message.messageType = object.messageType ?? 0;
    message.messageId = object.messageId ?? 0;
    return message;
  },
};

function createBaseCreateSmsSubmissionRequest(): CreateSmsSubmissionRequest {
  return {
    originatingNumber: "",
    destinationNumber: undefined,
    text: "",
    originatingSubscriberId: undefined,
    destinationSubscriberId: undefined,
    destinationEsn: undefined,
    destinationImsi: undefined,
  };
}

export const CreateSmsSubmissionRequest: MessageFns<CreateSmsSubmissionRequest> = {
  encode(message: CreateSmsSubmissionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.originatingNumber !== "") {
      writer.uint32(10).string(message.originatingNumber);
    }
    if (message.destinationNumber !== undefined) {
      writer.uint32(18).string(message.destinationNumber);
    }
    if (message.text !== "") {
      writer.uint32(26).string(message.text);
    }
    if (message.originatingSubscriberId !== undefined) {
      writer.uint32(34).string(message.originatingSubscriberId);
    }
    if (message.destinationSubscriberId !== undefined) {
      writer.uint32(42).string(message.destinationSubscriberId);
    }
    if (message.destinationEsn !== undefined) {
      writer.uint32(48).uint64(message.destinationEsn);
    }
    if (message.destinationImsi !== undefined) {
      writer.uint32(58).string(message.destinationImsi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSmsSubmissionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSmsSubmissionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.originatingNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.destinationNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.originatingSubscriberId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.destinationSubscriberId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.destinationEsn = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.destinationImsi = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSmsSubmissionRequest {
    return {
      originatingNumber: isSet(object.originatingNumber)
        ? globalThis.String(object.originatingNumber)
        : isSet(object.originating_number)
        ? globalThis.String(object.originating_number)
        : "",
      destinationNumber: isSet(object.destinationNumber)
        ? globalThis.String(object.destinationNumber)
        : isSet(object.destination_number)
        ? globalThis.String(object.destination_number)
        : undefined,
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      originatingSubscriberId: isSet(object.originatingSubscriberId)
        ? globalThis.String(object.originatingSubscriberId)
        : isSet(object.originating_subscriber_id)
        ? globalThis.String(object.originating_subscriber_id)
        : undefined,
      destinationSubscriberId: isSet(object.destinationSubscriberId)
        ? globalThis.String(object.destinationSubscriberId)
        : isSet(object.destination_subscriber_id)
        ? globalThis.String(object.destination_subscriber_id)
        : undefined,
      destinationEsn: isSet(object.destinationEsn)
        ? globalThis.Number(object.destinationEsn)
        : isSet(object.destination_esn)
        ? globalThis.Number(object.destination_esn)
        : undefined,
      destinationImsi: isSet(object.destinationImsi)
        ? globalThis.String(object.destinationImsi)
        : isSet(object.destination_imsi)
        ? globalThis.String(object.destination_imsi)
        : undefined,
    };
  },

  toJSON(message: CreateSmsSubmissionRequest): unknown {
    const obj: any = {};
    if (message.originatingNumber !== "") {
      obj.originatingNumber = message.originatingNumber;
    }
    if (message.destinationNumber !== undefined) {
      obj.destinationNumber = message.destinationNumber;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.originatingSubscriberId !== undefined) {
      obj.originatingSubscriberId = message.originatingSubscriberId;
    }
    if (message.destinationSubscriberId !== undefined) {
      obj.destinationSubscriberId = message.destinationSubscriberId;
    }
    if (message.destinationEsn !== undefined) {
      obj.destinationEsn = Math.round(message.destinationEsn);
    }
    if (message.destinationImsi !== undefined) {
      obj.destinationImsi = message.destinationImsi;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSmsSubmissionRequest>): CreateSmsSubmissionRequest {
    return CreateSmsSubmissionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSmsSubmissionRequest>): CreateSmsSubmissionRequest {
    const message = createBaseCreateSmsSubmissionRequest();
    message.originatingNumber = object.originatingNumber ?? "";
    message.destinationNumber = object.destinationNumber ?? undefined;
    message.text = object.text ?? "";
    message.originatingSubscriberId = object.originatingSubscriberId ?? undefined;
    message.destinationSubscriberId = object.destinationSubscriberId ?? undefined;
    message.destinationEsn = object.destinationEsn ?? undefined;
    message.destinationImsi = object.destinationImsi ?? undefined;
    return message;
  },
};

function createBaseCreateSmsSubmissionResponse(): CreateSmsSubmissionResponse {
  return { submission: undefined };
}

export const CreateSmsSubmissionResponse: MessageFns<CreateSmsSubmissionResponse> = {
  encode(message: CreateSmsSubmissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.submission !== undefined) {
      SmsSubmission.encode(message.submission, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSmsSubmissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSmsSubmissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.submission = SmsSubmission.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSmsSubmissionResponse {
    return { submission: isSet(object.submission) ? SmsSubmission.fromJSON(object.submission) : undefined };
  },

  toJSON(message: CreateSmsSubmissionResponse): unknown {
    const obj: any = {};
    if (message.submission !== undefined) {
      obj.submission = SmsSubmission.toJSON(message.submission);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSmsSubmissionResponse>): CreateSmsSubmissionResponse {
    return CreateSmsSubmissionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSmsSubmissionResponse>): CreateSmsSubmissionResponse {
    const message = createBaseCreateSmsSubmissionResponse();
    message.submission = (object.submission !== undefined && object.submission !== null)
      ? SmsSubmission.fromPartial(object.submission)
      : undefined;
    return message;
  },
};

function createBaseCreateOrGetRecentMoSubmissionRequest(): CreateOrGetRecentMoSubmissionRequest {
  return {
    originatingNumber: "",
    destinationNumber: "",
    text: "",
    originatingSubscriberId: undefined,
    destinationSubscriberId: undefined,
    fingerprint: undefined,
  };
}

export const CreateOrGetRecentMoSubmissionRequest: MessageFns<CreateOrGetRecentMoSubmissionRequest> = {
  encode(message: CreateOrGetRecentMoSubmissionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.originatingNumber !== "") {
      writer.uint32(10).string(message.originatingNumber);
    }
    if (message.destinationNumber !== "") {
      writer.uint32(18).string(message.destinationNumber);
    }
    if (message.text !== "") {
      writer.uint32(26).string(message.text);
    }
    if (message.originatingSubscriberId !== undefined) {
      writer.uint32(34).string(message.originatingSubscriberId);
    }
    if (message.destinationSubscriberId !== undefined) {
      writer.uint32(42).string(message.destinationSubscriberId);
    }
    if (message.fingerprint !== undefined) {
      MoSmsFingerprint.encode(message.fingerprint, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrGetRecentMoSubmissionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrGetRecentMoSubmissionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.originatingNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.destinationNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.originatingSubscriberId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.destinationSubscriberId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fingerprint = MoSmsFingerprint.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrGetRecentMoSubmissionRequest {
    return {
      originatingNumber: isSet(object.originatingNumber)
        ? globalThis.String(object.originatingNumber)
        : isSet(object.originating_number)
        ? globalThis.String(object.originating_number)
        : "",
      destinationNumber: isSet(object.destinationNumber)
        ? globalThis.String(object.destinationNumber)
        : isSet(object.destination_number)
        ? globalThis.String(object.destination_number)
        : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      originatingSubscriberId: isSet(object.originatingSubscriberId)
        ? globalThis.String(object.originatingSubscriberId)
        : isSet(object.originating_subscriber_id)
        ? globalThis.String(object.originating_subscriber_id)
        : undefined,
      destinationSubscriberId: isSet(object.destinationSubscriberId)
        ? globalThis.String(object.destinationSubscriberId)
        : isSet(object.destination_subscriber_id)
        ? globalThis.String(object.destination_subscriber_id)
        : undefined,
      fingerprint: isSet(object.fingerprint) ? MoSmsFingerprint.fromJSON(object.fingerprint) : undefined,
    };
  },

  toJSON(message: CreateOrGetRecentMoSubmissionRequest): unknown {
    const obj: any = {};
    if (message.originatingNumber !== "") {
      obj.originatingNumber = message.originatingNumber;
    }
    if (message.destinationNumber !== "") {
      obj.destinationNumber = message.destinationNumber;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.originatingSubscriberId !== undefined) {
      obj.originatingSubscriberId = message.originatingSubscriberId;
    }
    if (message.destinationSubscriberId !== undefined) {
      obj.destinationSubscriberId = message.destinationSubscriberId;
    }
    if (message.fingerprint !== undefined) {
      obj.fingerprint = MoSmsFingerprint.toJSON(message.fingerprint);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateOrGetRecentMoSubmissionRequest>): CreateOrGetRecentMoSubmissionRequest {
    return CreateOrGetRecentMoSubmissionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateOrGetRecentMoSubmissionRequest>): CreateOrGetRecentMoSubmissionRequest {
    const message = createBaseCreateOrGetRecentMoSubmissionRequest();
    message.originatingNumber = object.originatingNumber ?? "";
    message.destinationNumber = object.destinationNumber ?? "";
    message.text = object.text ?? "";
    message.originatingSubscriberId = object.originatingSubscriberId ?? undefined;
    message.destinationSubscriberId = object.destinationSubscriberId ?? undefined;
    message.fingerprint = (object.fingerprint !== undefined && object.fingerprint !== null)
      ? MoSmsFingerprint.fromPartial(object.fingerprint)
      : undefined;
    return message;
  },
};

function createBaseCreateOrGetRecentMoSubmissionResponse(): CreateOrGetRecentMoSubmissionResponse {
  return { submission: undefined, created: false };
}

export const CreateOrGetRecentMoSubmissionResponse: MessageFns<CreateOrGetRecentMoSubmissionResponse> = {
  encode(message: CreateOrGetRecentMoSubmissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.submission !== undefined) {
      SmsSubmission.encode(message.submission, writer.uint32(10).fork()).join();
    }
    if (message.created !== false) {
      writer.uint32(16).bool(message.created);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrGetRecentMoSubmissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrGetRecentMoSubmissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.submission = SmsSubmission.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.created = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrGetRecentMoSubmissionResponse {
    return {
      submission: isSet(object.submission) ? SmsSubmission.fromJSON(object.submission) : undefined,
      created: isSet(object.created) ? globalThis.Boolean(object.created) : false,
    };
  },

  toJSON(message: CreateOrGetRecentMoSubmissionResponse): unknown {
    const obj: any = {};
    if (message.submission !== undefined) {
      obj.submission = SmsSubmission.toJSON(message.submission);
    }
    if (message.created !== false) {
      obj.created = message.created;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateOrGetRecentMoSubmissionResponse>): CreateOrGetRecentMoSubmissionResponse {
    return CreateOrGetRecentMoSubmissionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateOrGetRecentMoSubmissionResponse>): CreateOrGetRecentMoSubmissionResponse {
    const message = createBaseCreateOrGetRecentMoSubmissionResponse();
    message.submission = (object.submission !== undefined && object.submission !== null)
      ? SmsSubmission.fromPartial(object.submission)
      : undefined;
    message.created = object.created ?? false;
    return message;
  },
};

function createBaseUpdateSmsSubmissionStateRequest(): UpdateSmsSubmissionStateRequest {
  return { smsId: "", state: "", failureReason: undefined };
}

export const UpdateSmsSubmissionStateRequest: MessageFns<UpdateSmsSubmissionStateRequest> = {
  encode(message: UpdateSmsSubmissionStateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smsId !== "") {
      writer.uint32(10).string(message.smsId);
    }
    if (message.state !== "") {
      writer.uint32(18).string(message.state);
    }
    if (message.failureReason !== undefined) {
      writer.uint32(26).string(message.failureReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateSmsSubmissionStateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateSmsSubmissionStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smsId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.failureReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateSmsSubmissionStateRequest {
    return {
      smsId: isSet(object.smsId)
        ? globalThis.String(object.smsId)
        : isSet(object.sms_id)
        ? globalThis.String(object.sms_id)
        : "",
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      failureReason: isSet(object.failureReason)
        ? globalThis.String(object.failureReason)
        : isSet(object.failure_reason)
        ? globalThis.String(object.failure_reason)
        : undefined,
    };
  },

  toJSON(message: UpdateSmsSubmissionStateRequest): unknown {
    const obj: any = {};
    if (message.smsId !== "") {
      obj.smsId = message.smsId;
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.failureReason !== undefined) {
      obj.failureReason = message.failureReason;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateSmsSubmissionStateRequest>): UpdateSmsSubmissionStateRequest {
    return UpdateSmsSubmissionStateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateSmsSubmissionStateRequest>): UpdateSmsSubmissionStateRequest {
    const message = createBaseUpdateSmsSubmissionStateRequest();
    message.smsId = object.smsId ?? "";
    message.state = object.state ?? "";
    message.failureReason = object.failureReason ?? undefined;
    return message;
  },
};

function createBaseUpdateSmsSubmissionStateResponse(): UpdateSmsSubmissionStateResponse {
  return { submission: undefined };
}

export const UpdateSmsSubmissionStateResponse: MessageFns<UpdateSmsSubmissionStateResponse> = {
  encode(message: UpdateSmsSubmissionStateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.submission !== undefined) {
      SmsSubmission.encode(message.submission, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateSmsSubmissionStateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateSmsSubmissionStateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.submission = SmsSubmission.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateSmsSubmissionStateResponse {
    return { submission: isSet(object.submission) ? SmsSubmission.fromJSON(object.submission) : undefined };
  },

  toJSON(message: UpdateSmsSubmissionStateResponse): unknown {
    const obj: any = {};
    if (message.submission !== undefined) {
      obj.submission = SmsSubmission.toJSON(message.submission);
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateSmsSubmissionStateResponse>): UpdateSmsSubmissionStateResponse {
    return UpdateSmsSubmissionStateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateSmsSubmissionStateResponse>): UpdateSmsSubmissionStateResponse {
    const message = createBaseUpdateSmsSubmissionStateResponse();
    message.submission = (object.submission !== undefined && object.submission !== null)
      ? SmsSubmission.fromPartial(object.submission)
      : undefined;
    return message;
  },
};

function createBaseGetSmsSubmissionRequest(): GetSmsSubmissionRequest {
  return { smsId: "" };
}

export const GetSmsSubmissionRequest: MessageFns<GetSmsSubmissionRequest> = {
  encode(message: GetSmsSubmissionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smsId !== "") {
      writer.uint32(10).string(message.smsId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSmsSubmissionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSmsSubmissionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smsId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSmsSubmissionRequest {
    return {
      smsId: isSet(object.smsId)
        ? globalThis.String(object.smsId)
        : isSet(object.sms_id)
        ? globalThis.String(object.sms_id)
        : "",
    };
  },

  toJSON(message: GetSmsSubmissionRequest): unknown {
    const obj: any = {};
    if (message.smsId !== "") {
      obj.smsId = message.smsId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetSmsSubmissionRequest>): GetSmsSubmissionRequest {
    return GetSmsSubmissionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSmsSubmissionRequest>): GetSmsSubmissionRequest {
    const message = createBaseGetSmsSubmissionRequest();
    message.smsId = object.smsId ?? "";
    return message;
  },
};

function createBaseGetSmsSubmissionResponse(): GetSmsSubmissionResponse {
  return { submission: undefined, deliveryAttempts: [] };
}

export const GetSmsSubmissionResponse: MessageFns<GetSmsSubmissionResponse> = {
  encode(message: GetSmsSubmissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.submission !== undefined) {
      SmsSubmission.encode(message.submission, writer.uint32(10).fork()).join();
    }
    for (const v of message.deliveryAttempts) {
      SmsDeliveryAttempt.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSmsSubmissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSmsSubmissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.submission = SmsSubmission.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deliveryAttempts.push(SmsDeliveryAttempt.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSmsSubmissionResponse {
    return {
      submission: isSet(object.submission) ? SmsSubmission.fromJSON(object.submission) : undefined,
      deliveryAttempts: globalThis.Array.isArray(object?.deliveryAttempts)
        ? object.deliveryAttempts.map((e: any) => SmsDeliveryAttempt.fromJSON(e))
        : globalThis.Array.isArray(object?.delivery_attempts)
        ? object.delivery_attempts.map((e: any) => SmsDeliveryAttempt.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetSmsSubmissionResponse): unknown {
    const obj: any = {};
    if (message.submission !== undefined) {
      obj.submission = SmsSubmission.toJSON(message.submission);
    }
    if (message.deliveryAttempts?.length) {
      obj.deliveryAttempts = message.deliveryAttempts.map((e) => SmsDeliveryAttempt.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetSmsSubmissionResponse>): GetSmsSubmissionResponse {
    return GetSmsSubmissionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSmsSubmissionResponse>): GetSmsSubmissionResponse {
    const message = createBaseGetSmsSubmissionResponse();
    message.submission = (object.submission !== undefined && object.submission !== null)
      ? SmsSubmission.fromPartial(object.submission)
      : undefined;
    message.deliveryAttempts = object.deliveryAttempts?.map((e) => SmsDeliveryAttempt.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListSmsSubmissionsRequest(): ListSmsSubmissionsRequest {
  return {
    limit: undefined,
    offset: undefined,
    destinationNumber: undefined,
    state: undefined,
    destinationEsn: undefined,
    destinationImsi: undefined,
  };
}

export const ListSmsSubmissionsRequest: MessageFns<ListSmsSubmissionsRequest> = {
  encode(message: ListSmsSubmissionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.limit !== undefined) {
      writer.uint32(8).uint32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(16).uint32(message.offset);
    }
    if (message.destinationNumber !== undefined) {
      writer.uint32(26).string(message.destinationNumber);
    }
    if (message.state !== undefined) {
      writer.uint32(34).string(message.state);
    }
    if (message.destinationEsn !== undefined) {
      writer.uint32(40).uint64(message.destinationEsn);
    }
    if (message.destinationImsi !== undefined) {
      writer.uint32(50).string(message.destinationImsi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSmsSubmissionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSmsSubmissionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.limit = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.destinationNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.destinationEsn = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.destinationImsi = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSmsSubmissionsRequest {
    return {
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : undefined,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : undefined,
      destinationNumber: isSet(object.destinationNumber)
        ? globalThis.String(object.destinationNumber)
        : isSet(object.destination_number)
        ? globalThis.String(object.destination_number)
        : undefined,
      state: isSet(object.state) ? globalThis.String(object.state) : undefined,
      destinationEsn: isSet(object.destinationEsn)
        ? globalThis.Number(object.destinationEsn)
        : isSet(object.destination_esn)
        ? globalThis.Number(object.destination_esn)
        : undefined,
      destinationImsi: isSet(object.destinationImsi)
        ? globalThis.String(object.destinationImsi)
        : isSet(object.destination_imsi)
        ? globalThis.String(object.destination_imsi)
        : undefined,
    };
  },

  toJSON(message: ListSmsSubmissionsRequest): unknown {
    const obj: any = {};
    if (message.limit !== undefined) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== undefined) {
      obj.offset = Math.round(message.offset);
    }
    if (message.destinationNumber !== undefined) {
      obj.destinationNumber = message.destinationNumber;
    }
    if (message.state !== undefined) {
      obj.state = message.state;
    }
    if (message.destinationEsn !== undefined) {
      obj.destinationEsn = Math.round(message.destinationEsn);
    }
    if (message.destinationImsi !== undefined) {
      obj.destinationImsi = message.destinationImsi;
    }
    return obj;
  },

  create(base?: DeepPartial<ListSmsSubmissionsRequest>): ListSmsSubmissionsRequest {
    return ListSmsSubmissionsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListSmsSubmissionsRequest>): ListSmsSubmissionsRequest {
    const message = createBaseListSmsSubmissionsRequest();
    message.limit = object.limit ?? undefined;
    message.offset = object.offset ?? undefined;
    message.destinationNumber = object.destinationNumber ?? undefined;
    message.state = object.state ?? undefined;
    message.destinationEsn = object.destinationEsn ?? undefined;
    message.destinationImsi = object.destinationImsi ?? undefined;
    return message;
  },
};

function createBaseListSmsSubmissionsResponse(): ListSmsSubmissionsResponse {
  return { submissions: [], total: 0 };
}

export const ListSmsSubmissionsResponse: MessageFns<ListSmsSubmissionsResponse> = {
  encode(message: ListSmsSubmissionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.submissions) {
      SmsSubmission.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).uint32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSmsSubmissionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSmsSubmissionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.submissions.push(SmsSubmission.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSmsSubmissionsResponse {
    return {
      submissions: globalThis.Array.isArray(object?.submissions)
        ? object.submissions.map((e: any) => SmsSubmission.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: ListSmsSubmissionsResponse): unknown {
    const obj: any = {};
    if (message.submissions?.length) {
      obj.submissions = message.submissions.map((e) => SmsSubmission.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create(base?: DeepPartial<ListSmsSubmissionsResponse>): ListSmsSubmissionsResponse {
    return ListSmsSubmissionsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListSmsSubmissionsResponse>): ListSmsSubmissionsResponse {
    const message = createBaseListSmsSubmissionsResponse();
    message.submissions = object.submissions?.map((e) => SmsSubmission.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseCreateDeliveryAttemptRequest(): CreateDeliveryAttemptRequest {
  return { smsId: "", targetSubscriberId: undefined };
}

export const CreateDeliveryAttemptRequest: MessageFns<CreateDeliveryAttemptRequest> = {
  encode(message: CreateDeliveryAttemptRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smsId !== "") {
      writer.uint32(10).string(message.smsId);
    }
    if (message.targetSubscriberId !== undefined) {
      writer.uint32(18).string(message.targetSubscriberId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateDeliveryAttemptRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDeliveryAttemptRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smsId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.targetSubscriberId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateDeliveryAttemptRequest {
    return {
      smsId: isSet(object.smsId)
        ? globalThis.String(object.smsId)
        : isSet(object.sms_id)
        ? globalThis.String(object.sms_id)
        : "",
      targetSubscriberId: isSet(object.targetSubscriberId)
        ? globalThis.String(object.targetSubscriberId)
        : isSet(object.target_subscriber_id)
        ? globalThis.String(object.target_subscriber_id)
        : undefined,
    };
  },

  toJSON(message: CreateDeliveryAttemptRequest): unknown {
    const obj: any = {};
    if (message.smsId !== "") {
      obj.smsId = message.smsId;
    }
    if (message.targetSubscriberId !== undefined) {
      obj.targetSubscriberId = message.targetSubscriberId;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateDeliveryAttemptRequest>): CreateDeliveryAttemptRequest {
    return CreateDeliveryAttemptRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateDeliveryAttemptRequest>): CreateDeliveryAttemptRequest {
    const message = createBaseCreateDeliveryAttemptRequest();
    message.smsId = object.smsId ?? "";
    message.targetSubscriberId = object.targetSubscriberId ?? undefined;
    return message;
  },
};

function createBaseCreateDeliveryAttemptResponse(): CreateDeliveryAttemptResponse {
  return { attempt: undefined };
}

export const CreateDeliveryAttemptResponse: MessageFns<CreateDeliveryAttemptResponse> = {
  encode(message: CreateDeliveryAttemptResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attempt !== undefined) {
      SmsDeliveryAttempt.encode(message.attempt, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateDeliveryAttemptResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDeliveryAttemptResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attempt = SmsDeliveryAttempt.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateDeliveryAttemptResponse {
    return { attempt: isSet(object.attempt) ? SmsDeliveryAttempt.fromJSON(object.attempt) : undefined };
  },

  toJSON(message: CreateDeliveryAttemptResponse): unknown {
    const obj: any = {};
    if (message.attempt !== undefined) {
      obj.attempt = SmsDeliveryAttempt.toJSON(message.attempt);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateDeliveryAttemptResponse>): CreateDeliveryAttemptResponse {
    return CreateDeliveryAttemptResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateDeliveryAttemptResponse>): CreateDeliveryAttemptResponse {
    const message = createBaseCreateDeliveryAttemptResponse();
    message.attempt = (object.attempt !== undefined && object.attempt !== null)
      ? SmsDeliveryAttempt.fromPartial(object.attempt)
      : undefined;
    return message;
  },
};

function createBaseUpdateDeliveryAttemptStateRequest(): UpdateDeliveryAttemptStateRequest {
  return { smsDeliveryAttemptId: "", state: "", failureReason: undefined };
}

export const UpdateDeliveryAttemptStateRequest: MessageFns<UpdateDeliveryAttemptStateRequest> = {
  encode(message: UpdateDeliveryAttemptStateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smsDeliveryAttemptId !== "") {
      writer.uint32(10).string(message.smsDeliveryAttemptId);
    }
    if (message.state !== "") {
      writer.uint32(18).string(message.state);
    }
    if (message.failureReason !== undefined) {
      writer.uint32(26).string(message.failureReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateDeliveryAttemptStateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateDeliveryAttemptStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smsDeliveryAttemptId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.failureReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateDeliveryAttemptStateRequest {
    return {
      smsDeliveryAttemptId: isSet(object.smsDeliveryAttemptId)
        ? globalThis.String(object.smsDeliveryAttemptId)
        : isSet(object.sms_delivery_attempt_id)
        ? globalThis.String(object.sms_delivery_attempt_id)
        : "",
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      failureReason: isSet(object.failureReason)
        ? globalThis.String(object.failureReason)
        : isSet(object.failure_reason)
        ? globalThis.String(object.failure_reason)
        : undefined,
    };
  },

  toJSON(message: UpdateDeliveryAttemptStateRequest): unknown {
    const obj: any = {};
    if (message.smsDeliveryAttemptId !== "") {
      obj.smsDeliveryAttemptId = message.smsDeliveryAttemptId;
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.failureReason !== undefined) {
      obj.failureReason = message.failureReason;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateDeliveryAttemptStateRequest>): UpdateDeliveryAttemptStateRequest {
    return UpdateDeliveryAttemptStateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateDeliveryAttemptStateRequest>): UpdateDeliveryAttemptStateRequest {
    const message = createBaseUpdateDeliveryAttemptStateRequest();
    message.smsDeliveryAttemptId = object.smsDeliveryAttemptId ?? "";
    message.state = object.state ?? "";
    message.failureReason = object.failureReason ?? undefined;
    return message;
  },
};

function createBaseUpdateDeliveryAttemptStateResponse(): UpdateDeliveryAttemptStateResponse {
  return { attempt: undefined };
}

export const UpdateDeliveryAttemptStateResponse: MessageFns<UpdateDeliveryAttemptStateResponse> = {
  encode(message: UpdateDeliveryAttemptStateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attempt !== undefined) {
      SmsDeliveryAttempt.encode(message.attempt, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateDeliveryAttemptStateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateDeliveryAttemptStateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attempt = SmsDeliveryAttempt.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateDeliveryAttemptStateResponse {
    return { attempt: isSet(object.attempt) ? SmsDeliveryAttempt.fromJSON(object.attempt) : undefined };
  },

  toJSON(message: UpdateDeliveryAttemptStateResponse): unknown {
    const obj: any = {};
    if (message.attempt !== undefined) {
      obj.attempt = SmsDeliveryAttempt.toJSON(message.attempt);
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateDeliveryAttemptStateResponse>): UpdateDeliveryAttemptStateResponse {
    return UpdateDeliveryAttemptStateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateDeliveryAttemptStateResponse>): UpdateDeliveryAttemptStateResponse {
    const message = createBaseUpdateDeliveryAttemptStateResponse();
    message.attempt = (object.attempt !== undefined && object.attempt !== null)
      ? SmsDeliveryAttempt.fromPartial(object.attempt)
      : undefined;
    return message;
  },
};

function createBaseUpdateDestinationSubscriberRequest(): UpdateDestinationSubscriberRequest {
  return { smsId: "", destinationSubscriberId: "" };
}

export const UpdateDestinationSubscriberRequest: MessageFns<UpdateDestinationSubscriberRequest> = {
  encode(message: UpdateDestinationSubscriberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smsId !== "") {
      writer.uint32(10).string(message.smsId);
    }
    if (message.destinationSubscriberId !== "") {
      writer.uint32(18).string(message.destinationSubscriberId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateDestinationSubscriberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateDestinationSubscriberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smsId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.destinationSubscriberId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateDestinationSubscriberRequest {
    return {
      smsId: isSet(object.smsId)
        ? globalThis.String(object.smsId)
        : isSet(object.sms_id)
        ? globalThis.String(object.sms_id)
        : "",
      destinationSubscriberId: isSet(object.destinationSubscriberId)
        ? globalThis.String(object.destinationSubscriberId)
        : isSet(object.destination_subscriber_id)
        ? globalThis.String(object.destination_subscriber_id)
        : "",
    };
  },

  toJSON(message: UpdateDestinationSubscriberRequest): unknown {
    const obj: any = {};
    if (message.smsId !== "") {
      obj.smsId = message.smsId;
    }
    if (message.destinationSubscriberId !== "") {
      obj.destinationSubscriberId = message.destinationSubscriberId;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateDestinationSubscriberRequest>): UpdateDestinationSubscriberRequest {
    return UpdateDestinationSubscriberRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateDestinationSubscriberRequest>): UpdateDestinationSubscriberRequest {
    const message = createBaseUpdateDestinationSubscriberRequest();
    message.smsId = object.smsId ?? "";
    message.destinationSubscriberId = object.destinationSubscriberId ?? "";
    return message;
  },
};

/** SMSC service for storing SMS submissions and tracking delivery attempts. */
export type SmscServiceDefinition = typeof SmscServiceDefinition;
export const SmscServiceDefinition = {
  name: "SmscService",
  fullName: "smsc.v1.SmscService",
  methods: {
    /** Accepts a new SMS submission. */
    createSmsSubmission: {
      name: "CreateSmsSubmission",
      requestType: CreateSmsSubmissionRequest as typeof CreateSmsSubmissionRequest,
      requestStream: false,
      responseType: CreateSmsSubmissionResponse as typeof CreateSmsSubmissionResponse,
      responseStream: false,
      options: {},
    },
    /** Accepts an MO SMS submission with duplicate suppression. */
    createOrGetRecentMoSubmission: {
      name: "CreateOrGetRecentMoSubmission",
      requestType: CreateOrGetRecentMoSubmissionRequest as typeof CreateOrGetRecentMoSubmissionRequest,
      requestStream: false,
      responseType: CreateOrGetRecentMoSubmissionResponse as typeof CreateOrGetRecentMoSubmissionResponse,
      responseStream: false,
      options: {},
    },
    /** Updates high-level submission state. */
    updateSmsSubmissionState: {
      name: "UpdateSmsSubmissionState",
      requestType: UpdateSmsSubmissionStateRequest as typeof UpdateSmsSubmissionStateRequest,
      requestStream: false,
      responseType: UpdateSmsSubmissionStateResponse as typeof UpdateSmsSubmissionStateResponse,
      responseStream: false,
      options: {},
    },
    /** Returns one submission and its delivery attempts. */
    getSmsSubmission: {
      name: "GetSmsSubmission",
      requestType: GetSmsSubmissionRequest as typeof GetSmsSubmissionRequest,
      requestStream: false,
      responseType: GetSmsSubmissionResponse as typeof GetSmsSubmissionResponse,
      responseStream: false,
      options: {},
    },
    /** Lists submissions with optional filters. */
    listSmsSubmissions: {
      name: "ListSmsSubmissions",
      requestType: ListSmsSubmissionsRequest as typeof ListSmsSubmissionsRequest,
      requestStream: false,
      responseType: ListSmsSubmissionsResponse as typeof ListSmsSubmissionsResponse,
      responseStream: false,
      options: {},
    },
    /** Starts tracking a new delivery attempt for a submission. */
    createDeliveryAttempt: {
      name: "CreateDeliveryAttempt",
      requestType: CreateDeliveryAttemptRequest as typeof CreateDeliveryAttemptRequest,
      requestStream: false,
      responseType: CreateDeliveryAttemptResponse as typeof CreateDeliveryAttemptResponse,
      responseStream: false,
      options: {},
    },
    /** Updates delivery-attempt state. */
    updateDeliveryAttemptState: {
      name: "UpdateDeliveryAttemptState",
      requestType: UpdateDeliveryAttemptStateRequest as typeof UpdateDeliveryAttemptStateRequest,
      requestStream: false,
      responseType: UpdateDeliveryAttemptStateResponse as typeof UpdateDeliveryAttemptStateResponse,
      responseStream: false,
      options: {},
    },
    /** Assigns or updates the resolved destination subscriber. */
    updateDestinationSubscriber: {
      name: "UpdateDestinationSubscriber",
      requestType: UpdateDestinationSubscriberRequest as typeof UpdateDestinationSubscriberRequest,
      requestStream: false,
      responseType: Empty as typeof Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface SmscServiceImplementation<CallContextExt = {}> {
  /** Accepts a new SMS submission. */
  createSmsSubmission(
    request: CreateSmsSubmissionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CreateSmsSubmissionResponse>>;
  /** Accepts an MO SMS submission with duplicate suppression. */
  createOrGetRecentMoSubmission(
    request: CreateOrGetRecentMoSubmissionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CreateOrGetRecentMoSubmissionResponse>>;
  /** Updates high-level submission state. */
  updateSmsSubmissionState(
    request: UpdateSmsSubmissionStateRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<UpdateSmsSubmissionStateResponse>>;
  /** Returns one submission and its delivery attempts. */
  getSmsSubmission(
    request: GetSmsSubmissionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSmsSubmissionResponse>>;
  /** Lists submissions with optional filters. */
  listSmsSubmissions(
    request: ListSmsSubmissionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListSmsSubmissionsResponse>>;
  /** Starts tracking a new delivery attempt for a submission. */
  createDeliveryAttempt(
    request: CreateDeliveryAttemptRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CreateDeliveryAttemptResponse>>;
  /** Updates delivery-attempt state. */
  updateDeliveryAttemptState(
    request: UpdateDeliveryAttemptStateRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<UpdateDeliveryAttemptStateResponse>>;
  /** Assigns or updates the resolved destination subscriber. */
  updateDestinationSubscriber(
    request: UpdateDestinationSubscriberRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Empty>>;
}

export interface SmscServiceClient<CallOptionsExt = {}> {
  /** Accepts a new SMS submission. */
  createSmsSubmission(
    request: DeepPartial<CreateSmsSubmissionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CreateSmsSubmissionResponse>;
  /** Accepts an MO SMS submission with duplicate suppression. */
  createOrGetRecentMoSubmission(
    request: DeepPartial<CreateOrGetRecentMoSubmissionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CreateOrGetRecentMoSubmissionResponse>;
  /** Updates high-level submission state. */
  updateSmsSubmissionState(
    request: DeepPartial<UpdateSmsSubmissionStateRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<UpdateSmsSubmissionStateResponse>;
  /** Returns one submission and its delivery attempts. */
  getSmsSubmission(
    request: DeepPartial<GetSmsSubmissionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSmsSubmissionResponse>;
  /** Lists submissions with optional filters. */
  listSmsSubmissions(
    request: DeepPartial<ListSmsSubmissionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListSmsSubmissionsResponse>;
  /** Starts tracking a new delivery attempt for a submission. */
  createDeliveryAttempt(
    request: DeepPartial<CreateDeliveryAttemptRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CreateDeliveryAttemptResponse>;
  /** Updates delivery-attempt state. */
  updateDeliveryAttemptState(
    request: DeepPartial<UpdateDeliveryAttemptStateRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<UpdateDeliveryAttemptStateResponse>;
  /** Assigns or updates the resolved destination subscriber. */
  updateDestinationSubscriber(
    request: DeepPartial<UpdateDestinationSubscriberRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Empty>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
