// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: pcf_management/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { InitiateDataCallRequest, InitiateDataCallResponse } from "../../bsc/v1/service";
import { Empty } from "../../google/protobuf/empty";
import { GetSessionStatusResponse, PacketSessionInfo } from "../../packet/v1/service";

export const protobufPackage = "pcf_management.v1";

/** Packet sessions visible through the PCF management service. */
export interface PcfSessionList {
  /** Summary for each active or recently tracked packet session. */
  sessions: PacketSessionInfo[];
}

/** Selects a PCF packet session. */
export interface GetPcfSessionRequest {
  /** Packet session identifier allocated by packet-call setup. */
  sessionId: string;
}

function createBasePcfSessionList(): PcfSessionList {
  return { sessions: [] };
}

export const PcfSessionList: MessageFns<PcfSessionList> = {
  encode(message: PcfSessionList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sessions) {
      PacketSessionInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PcfSessionList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePcfSessionList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessions.push(PacketSessionInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PcfSessionList {
    return {
      sessions: globalThis.Array.isArray(object?.sessions)
        ? object.sessions.map((e: any) => PacketSessionInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PcfSessionList): unknown {
    const obj: any = {};
    if (message.sessions?.length) {
      obj.sessions = message.sessions.map((e) => PacketSessionInfo.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<PcfSessionList>): PcfSessionList {
    return PcfSessionList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PcfSessionList>): PcfSessionList {
    const message = createBasePcfSessionList();
    message.sessions = object.sessions?.map((e) => PacketSessionInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetPcfSessionRequest(): GetPcfSessionRequest {
  return { sessionId: "" };
}

export const GetPcfSessionRequest: MessageFns<GetPcfSessionRequest> = {
  encode(message: GetPcfSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPcfSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPcfSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPcfSessionRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: GetPcfSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetPcfSessionRequest>): GetPcfSessionRequest {
    return GetPcfSessionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetPcfSessionRequest>): GetPcfSessionRequest {
    const message = createBaseGetPcfSessionRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

/** PCF management API for packet-call initiation and packet session inspection. */
export type PcfManagementServiceDefinition = typeof PcfManagementServiceDefinition;
export const PcfManagementServiceDefinition = {
  name: "PcfManagementService",
  fullName: "pcf_management.v1.PcfManagementService",
  methods: {
    /** Initiates a data call by paging the mobile and requesting packet service. */
    initiateDataCall: {
      name: "InitiateDataCall",
      requestType: InitiateDataCallRequest as typeof InitiateDataCallRequest,
      requestStream: false,
      responseType: InitiateDataCallResponse as typeof InitiateDataCallResponse,
      responseStream: false,
      options: {},
    },
    /** Lists packet sessions known by the PCF. */
    listPcfSessions: {
      name: "ListPcfSessions",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: PcfSessionList as typeof PcfSessionList,
      responseStream: false,
      options: {},
    },
    /** Returns detailed status for one packet session. */
    getPcfSession: {
      name: "GetPcfSession",
      requestType: GetPcfSessionRequest as typeof GetPcfSessionRequest,
      requestStream: false,
      responseType: GetSessionStatusResponse as typeof GetSessionStatusResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface PcfManagementServiceImplementation<CallContextExt = {}> {
  /** Initiates a data call by paging the mobile and requesting packet service. */
  initiateDataCall(
    request: InitiateDataCallRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<InitiateDataCallResponse>>;
  /** Lists packet sessions known by the PCF. */
  listPcfSessions(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<PcfSessionList>>;
  /** Returns detailed status for one packet session. */
  getPcfSession(
    request: GetPcfSessionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionStatusResponse>>;
}

export interface PcfManagementServiceClient<CallOptionsExt = {}> {
  /** Initiates a data call by paging the mobile and requesting packet service. */
  initiateDataCall(
    request: DeepPartial<InitiateDataCallRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<InitiateDataCallResponse>;
  /** Lists packet sessions known by the PCF. */
  listPcfSessions(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<PcfSessionList>;
  /** Returns detailed status for one packet session. */
  getPcfSession(
    request: DeepPartial<GetPcfSessionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionStatusResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
