// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: packet/v1/service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "packet.v1";

/** Radio access technology for a packet session. */
export enum AccessTechnology {
  ACCESS_TECHNOLOGY_UNSPECIFIED = 0,
  ACCESS_TECHNOLOGY_CDMA_1X = 1,
  ACCESS_TECHNOLOGY_HRPD = 2,
  UNRECOGNIZED = -1,
}

export function accessTechnologyFromJSON(object: any): AccessTechnology {
  switch (object) {
    case 0:
    case "ACCESS_TECHNOLOGY_UNSPECIFIED":
      return AccessTechnology.ACCESS_TECHNOLOGY_UNSPECIFIED;
    case 1:
    case "ACCESS_TECHNOLOGY_CDMA_1X":
      return AccessTechnology.ACCESS_TECHNOLOGY_CDMA_1X;
    case 2:
    case "ACCESS_TECHNOLOGY_HRPD":
      return AccessTechnology.ACCESS_TECHNOLOGY_HRPD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AccessTechnology.UNRECOGNIZED;
  }
}

export function accessTechnologyToJSON(object: AccessTechnology): string {
  switch (object) {
    case AccessTechnology.ACCESS_TECHNOLOGY_UNSPECIFIED:
      return "ACCESS_TECHNOLOGY_UNSPECIFIED";
    case AccessTechnology.ACCESS_TECHNOLOGY_CDMA_1X:
      return "ACCESS_TECHNOLOGY_CDMA_1X";
    case AccessTechnology.ACCESS_TECHNOLOGY_HRPD:
      return "ACCESS_TECHNOLOGY_HRPD";
    case AccessTechnology.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Origin of the HRPD A11 MN ID used for bearer registration. */
export enum HrpdMnIdSource {
  HRPD_MN_ID_SOURCE_UNSPECIFIED = 0,
  HRPD_MN_ID_SOURCE_A11 = 1,
  HRPD_MN_ID_SOURCE_DERIVED_HARDWARE = 2,
  UNRECOGNIZED = -1,
}

export function hrpdMnIdSourceFromJSON(object: any): HrpdMnIdSource {
  switch (object) {
    case 0:
    case "HRPD_MN_ID_SOURCE_UNSPECIFIED":
      return HrpdMnIdSource.HRPD_MN_ID_SOURCE_UNSPECIFIED;
    case 1:
    case "HRPD_MN_ID_SOURCE_A11":
      return HrpdMnIdSource.HRPD_MN_ID_SOURCE_A11;
    case 2:
    case "HRPD_MN_ID_SOURCE_DERIVED_HARDWARE":
      return HrpdMnIdSource.HRPD_MN_ID_SOURCE_DERIVED_HARDWARE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HrpdMnIdSource.UNRECOGNIZED;
  }
}

export function hrpdMnIdSourceToJSON(object: HrpdMnIdSource): string {
  switch (object) {
    case HrpdMnIdSource.HRPD_MN_ID_SOURCE_UNSPECIFIED:
      return "HRPD_MN_ID_SOURCE_UNSPECIFIED";
    case HrpdMnIdSource.HRPD_MN_ID_SOURCE_A11:
      return "HRPD_MN_ID_SOURCE_A11";
    case HrpdMnIdSource.HRPD_MN_ID_SOURCE_DERIVED_HARDWARE:
      return "HRPD_MN_ID_SOURCE_DERIVED_HARDWARE";
    case HrpdMnIdSource.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** One RLP traffic frame moving between the radio stack and packet engine. */
export interface SessionFrame {
  /** Packet session identifier. */
  sessionId: string;
  /** Bit vector encoded as one byte per bit, value 0 or 1. */
  bits: Uint8Array;
  /** Number of valid bits in `bits`. */
  numBits: number;
  /** CDMA frame rate represented as payload bits per second. */
  rateBps: number;
}

/** Opens packet session state for one mobile packet-data call. */
export interface OpenSessionRequest {
  /** Packet session identifier allocated by call setup. */
  sessionId: string;
  /** CDMA service option, for example SO33 for high-rate packet data. */
  serviceOption: number;
  /** Mobile ESN when available. */
  esn: number;
  /** Full mobile IMSI when available. */
  imsi: string;
  /** Display/debug mobile address. */
  mobileAddress: string;
  /** HLR subscriber UUID when resolved. */
  subscriberId: string;
  /** Subscriber phone number when resolved. */
  phoneNumber: string;
  /** Assigned forward traffic-channel Walsh code. */
  trafficWalshCode: number;
  /** Mobile MEID when available as subscriber/equipment metadata. */
  meid: string;
  /**
   * HRPD A11 MN ID used for bearer registration. This may be an IMSI-format
   * value derived for A11 and must not be displayed as a subscriber IMSI.
   */
  hrpdMnId: string;
  /** Origin of hrpd_mn_id. */
  hrpdMnIdSource: HrpdMnIdSource;
  /** Authoritative subscriber IMSI when resolved by HLR/A12/roaming data. */
  subscriberImsi: string;
}

/** Response returned after packet session state is opened. */
export interface OpenSessionResponse {
  /** Packet session identifier that was opened. */
  sessionId: string;
}

/** Closes packet session state and transport resources. */
export interface CloseSessionRequest {
  /** Packet session identifier to close. */
  sessionId: string;
}

/** Empty response for a successful session close. */
export interface CloseSessionResponse {
}

/** Selects one packet session for status lookup. */
export interface GetSessionStatusRequest {
  /** Packet session identifier. */
  sessionId: string;
}

/** Detailed status lookup response for one packet session. */
export interface GetSessionStatusResponse {
  /** Session detail, omitted only if the implementation returns an error. */
  session: PacketSessionDetail | undefined;
}

/** Request to list packet sessions. */
export interface ListSessionsRequest {
}

/** Selects one packet session by its mobile-side IP address. */
export interface GetSessionByIpRequest {
  /** Mobile (peer) IP address as the engine reports it, e.g. "10.55.0.2". */
  peerIp: string;
}

/** Response carrying the matching session summary, if any. */
export interface GetSessionByIpResponse {
  /** Set when an active session matches `peer_ip`; unset on miss. */
  session: PacketSessionInfo | undefined;
}

/** List of packet session summaries. */
export interface ListSessionsResponse {
  /** Session summaries sorted by implementation-defined recency. */
  sessions: PacketSessionInfo[];
}

/** Enables or disables trace capture for one packet session. */
export interface SetSessionCaptureRequest {
  /** Packet session identifier. */
  sessionId: string;
  /** True to retain trace events, false to stop capture. */
  enabled: boolean;
}

/** Response after changing packet trace capture state. */
export interface SetSessionCaptureResponse {
  /** Updated session detail. */
  session: PacketSessionDetail | undefined;
}

/** Toggles F-SCH downlink frame generation on one packet session. */
export interface SetSchActiveRequest {
  /** Packet session identifier. */
  sessionId: string;
  /** True to enable RLP3 SCH frame generation, false to disable. */
  active: boolean;
  /** RC3 F-SCH rate in bps. Omitted/zero defaults to 19200 for compatibility. */
  rateBps: number;
}

/**
 * Empty response for a successful SCH-active toggle. The error case is
 * surfaced via gRPC status (NotFound when session_id is unknown, etc.).
 */
export interface SetSchActiveResponse {
}

/** Summary state for a packet data session. */
export interface PacketSessionInfo {
  /** Packet session identifier. */
  sessionId: string;
  /** Packet engine phase such as setup, active, or closing. */
  phase: string;
  /** CDMA service option used for the session. */
  serviceOption: number;
  /** Mobile-side IP address. */
  peerIp: string;
  /** Network-side IP address. */
  ourIp: string;
  /** TUN device name when the session uses TUN transport. */
  tunDevice: string;
  uplinkFrames: number;
  downlinkFrames: number;
  uplinkBytes: number;
  downlinkBytes: number;
  createdAtMs: number;
  lastPhaseChangeAtMs: number;
  lastUplinkAtMs: number;
  lastDownlinkAtMs: number;
  lastActivityAtMs: number;
  lastUplinkRateBps: number;
  lastDownlinkRateBps: number;
  mobileAddress: string;
  subscriberId: string;
  phoneNumber: string;
  trafficWalshCode: number;
  rlpState: string;
  lcpState: string;
  ipcpState: string;
  captureEnabled: boolean;
  /** Radio access technology for this packet session. */
  accessTechnology: AccessTechnology;
  /** IMSI associated with the packet session when known. */
  imsi: string;
  /** ESN associated with the packet session when known. */
  esn: number;
  /** Mobile MEID when available. */
  meid: string;
  /**
   * HRPD A11 MN ID used for bearer registration. This is not necessarily a
   * subscriber IMSI.
   */
  hrpdMnId: string;
  /** Origin of hrpd_mn_id. */
  hrpdMnIdSource: HrpdMnIdSource;
  /** Authoritative subscriber IMSI when resolved. */
  subscriberImsi: string;
}

/** One trace event emitted by PPP, RLP, IP transport, or capture code. */
export interface PacketTraceEvent {
  /** Unix timestamp in milliseconds. */
  timestampMs: number;
  /** Protocol layer that emitted the event. */
  layer: string;
  /** Direction such as uplink or downlink. */
  direction: string;
  /** Short event summary for list displays. */
  summary: string;
  /** Longer diagnostic text. */
  detail: string;
  /** Optional payload bytes rendered as hex. */
  payloadHex: string;
}

/** Detailed packet session status and recent trace events. */
export interface PacketSessionDetail {
  /** Basic session state and counters. */
  summary:
    | PacketSessionInfo
    | undefined;
  /** Most recent inbound control frame summary. */
  lastRxControl: string;
  /** Most recent outbound control frame summary. */
  lastTxControl: string;
  /** Repeat count for the most recent inbound control frame. */
  lastRxControlRepeats: number;
  /** Repeat count for the most recent outbound control frame. */
  lastTxControlRepeats: number;
  /** Recent PPP/RLP/IP events retained even when capture is disabled. */
  recentPppEvents: PacketTraceEvent[];
  /** Captured trace events retained while capture is enabled. */
  captureEvents: PacketTraceEvent[];
}

function createBaseSessionFrame(): SessionFrame {
  return { sessionId: "", bits: new Uint8Array(0), numBits: 0, rateBps: 0 };
}

export const SessionFrame: MessageFns<SessionFrame> = {
  encode(message: SessionFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.bits.length !== 0) {
      writer.uint32(18).bytes(message.bits);
    }
    if (message.numBits !== 0) {
      writer.uint32(24).uint32(message.numBits);
    }
    if (message.rateBps !== 0) {
      writer.uint32(32).uint32(message.rateBps);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bits = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.numBits = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.rateBps = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionFrame {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      bits: isSet(object.bits) ? bytesFromBase64(object.bits) : new Uint8Array(0),
      numBits: isSet(object.numBits)
        ? globalThis.Number(object.numBits)
        : isSet(object.num_bits)
        ? globalThis.Number(object.num_bits)
        : 0,
      rateBps: isSet(object.rateBps)
        ? globalThis.Number(object.rateBps)
        : isSet(object.rate_bps)
        ? globalThis.Number(object.rate_bps)
        : 0,
    };
  },

  toJSON(message: SessionFrame): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.bits.length !== 0) {
      obj.bits = base64FromBytes(message.bits);
    }
    if (message.numBits !== 0) {
      obj.numBits = Math.round(message.numBits);
    }
    if (message.rateBps !== 0) {
      obj.rateBps = Math.round(message.rateBps);
    }
    return obj;
  },

  create(base?: DeepPartial<SessionFrame>): SessionFrame {
    return SessionFrame.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SessionFrame>): SessionFrame {
    const message = createBaseSessionFrame();
    message.sessionId = object.sessionId ?? "";
    message.bits = object.bits ?? new Uint8Array(0);
    message.numBits = object.numBits ?? 0;
    message.rateBps = object.rateBps ?? 0;
    return message;
  },
};

function createBaseOpenSessionRequest(): OpenSessionRequest {
  return {
    sessionId: "",
    serviceOption: 0,
    esn: 0,
    imsi: "",
    mobileAddress: "",
    subscriberId: "",
    phoneNumber: "",
    trafficWalshCode: 0,
    meid: "",
    hrpdMnId: "",
    hrpdMnIdSource: 0,
    subscriberImsi: "",
  };
}

export const OpenSessionRequest: MessageFns<OpenSessionRequest> = {
  encode(message: OpenSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.serviceOption !== 0) {
      writer.uint32(16).uint32(message.serviceOption);
    }
    if (message.esn !== 0) {
      writer.uint32(24).uint32(message.esn);
    }
    if (message.imsi !== "") {
      writer.uint32(34).string(message.imsi);
    }
    if (message.mobileAddress !== "") {
      writer.uint32(42).string(message.mobileAddress);
    }
    if (message.subscriberId !== "") {
      writer.uint32(50).string(message.subscriberId);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(58).string(message.phoneNumber);
    }
    if (message.trafficWalshCode !== 0) {
      writer.uint32(64).uint32(message.trafficWalshCode);
    }
    if (message.meid !== "") {
      writer.uint32(74).string(message.meid);
    }
    if (message.hrpdMnId !== "") {
      writer.uint32(82).string(message.hrpdMnId);
    }
    if (message.hrpdMnIdSource !== 0) {
      writer.uint32(88).int32(message.hrpdMnIdSource);
    }
    if (message.subscriberImsi !== "") {
      writer.uint32(98).string(message.subscriberImsi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpenSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpenSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.serviceOption = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.esn = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.imsi = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.mobileAddress = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.subscriberId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.trafficWalshCode = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.meid = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.hrpdMnId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.hrpdMnIdSource = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.subscriberImsi = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OpenSessionRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      serviceOption: isSet(object.serviceOption)
        ? globalThis.Number(object.serviceOption)
        : isSet(object.service_option)
        ? globalThis.Number(object.service_option)
        : 0,
      esn: isSet(object.esn) ? globalThis.Number(object.esn) : 0,
      imsi: isSet(object.imsi) ? globalThis.String(object.imsi) : "",
      mobileAddress: isSet(object.mobileAddress)
        ? globalThis.String(object.mobileAddress)
        : isSet(object.mobile_address)
        ? globalThis.String(object.mobile_address)
        : "",
      subscriberId: isSet(object.subscriberId)
        ? globalThis.String(object.subscriberId)
        : isSet(object.subscriber_id)
        ? globalThis.String(object.subscriber_id)
        : "",
      phoneNumber: isSet(object.phoneNumber)
        ? globalThis.String(object.phoneNumber)
        : isSet(object.phone_number)
        ? globalThis.String(object.phone_number)
        : "",
      trafficWalshCode: isSet(object.trafficWalshCode)
        ? globalThis.Number(object.trafficWalshCode)
        : isSet(object.traffic_walsh_code)
        ? globalThis.Number(object.traffic_walsh_code)
        : 0,
      meid: isSet(object.meid) ? globalThis.String(object.meid) : "",
      hrpdMnId: isSet(object.hrpdMnId)
        ? globalThis.String(object.hrpdMnId)
        : isSet(object.hrpd_mn_id)
        ? globalThis.String(object.hrpd_mn_id)
        : "",
      hrpdMnIdSource: isSet(object.hrpdMnIdSource)
        ? hrpdMnIdSourceFromJSON(object.hrpdMnIdSource)
        : isSet(object.hrpd_mn_id_source)
        ? hrpdMnIdSourceFromJSON(object.hrpd_mn_id_source)
        : 0,
      subscriberImsi: isSet(object.subscriberImsi)
        ? globalThis.String(object.subscriberImsi)
        : isSet(object.subscriber_imsi)
        ? globalThis.String(object.subscriber_imsi)
        : "",
    };
  },

  toJSON(message: OpenSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.serviceOption !== 0) {
      obj.serviceOption = Math.round(message.serviceOption);
    }
    if (message.esn !== 0) {
      obj.esn = Math.round(message.esn);
    }
    if (message.imsi !== "") {
      obj.imsi = message.imsi;
    }
    if (message.mobileAddress !== "") {
      obj.mobileAddress = message.mobileAddress;
    }
    if (message.subscriberId !== "") {
      obj.subscriberId = message.subscriberId;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.trafficWalshCode !== 0) {
      obj.trafficWalshCode = Math.round(message.trafficWalshCode);
    }
    if (message.meid !== "") {
      obj.meid = message.meid;
    }
    if (message.hrpdMnId !== "") {
      obj.hrpdMnId = message.hrpdMnId;
    }
    if (message.hrpdMnIdSource !== 0) {
      obj.hrpdMnIdSource = hrpdMnIdSourceToJSON(message.hrpdMnIdSource);
    }
    if (message.subscriberImsi !== "") {
      obj.subscriberImsi = message.subscriberImsi;
    }
    return obj;
  },

  create(base?: DeepPartial<OpenSessionRequest>): OpenSessionRequest {
    return OpenSessionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OpenSessionRequest>): OpenSessionRequest {
    const message = createBaseOpenSessionRequest();
    message.sessionId = object.sessionId ?? "";
    message.serviceOption = object.serviceOption ?? 0;
    message.esn = object.esn ?? 0;
    message.imsi = object.imsi ?? "";
    message.mobileAddress = object.mobileAddress ?? "";
    message.subscriberId = object.subscriberId ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.trafficWalshCode = object.trafficWalshCode ?? 0;
    message.meid = object.meid ?? "";
    message.hrpdMnId = object.hrpdMnId ?? "";
    message.hrpdMnIdSource = object.hrpdMnIdSource ?? 0;
    message.subscriberImsi = object.subscriberImsi ?? "";
    return message;
  },
};

function createBaseOpenSessionResponse(): OpenSessionResponse {
  return { sessionId: "" };
}

export const OpenSessionResponse: MessageFns<OpenSessionResponse> = {
  encode(message: OpenSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpenSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpenSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OpenSessionResponse {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: OpenSessionResponse): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create(base?: DeepPartial<OpenSessionResponse>): OpenSessionResponse {
    return OpenSessionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OpenSessionResponse>): OpenSessionResponse {
    const message = createBaseOpenSessionResponse();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseCloseSessionRequest(): CloseSessionRequest {
  return { sessionId: "" };
}

export const CloseSessionRequest: MessageFns<CloseSessionRequest> = {
  encode(message: CloseSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CloseSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloseSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CloseSessionRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: CloseSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create(base?: DeepPartial<CloseSessionRequest>): CloseSessionRequest {
    return CloseSessionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CloseSessionRequest>): CloseSessionRequest {
    const message = createBaseCloseSessionRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseCloseSessionResponse(): CloseSessionResponse {
  return {};
}

export const CloseSessionResponse: MessageFns<CloseSessionResponse> = {
  encode(_: CloseSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CloseSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloseSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CloseSessionResponse {
    return {};
  },

  toJSON(_: CloseSessionResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<CloseSessionResponse>): CloseSessionResponse {
    return CloseSessionResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<CloseSessionResponse>): CloseSessionResponse {
    const message = createBaseCloseSessionResponse();
    return message;
  },
};

function createBaseGetSessionStatusRequest(): GetSessionStatusRequest {
  return { sessionId: "" };
}

export const GetSessionStatusRequest: MessageFns<GetSessionStatusRequest> = {
  encode(message: GetSessionStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionStatusRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: GetSessionStatusRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetSessionStatusRequest>): GetSessionStatusRequest {
    return GetSessionStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSessionStatusRequest>): GetSessionStatusRequest {
    const message = createBaseGetSessionStatusRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseGetSessionStatusResponse(): GetSessionStatusResponse {
  return { session: undefined };
}

export const GetSessionStatusResponse: MessageFns<GetSessionStatusResponse> = {
  encode(message: GetSessionStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      PacketSessionDetail.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = PacketSessionDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionStatusResponse {
    return { session: isSet(object.session) ? PacketSessionDetail.fromJSON(object.session) : undefined };
  },

  toJSON(message: GetSessionStatusResponse): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = PacketSessionDetail.toJSON(message.session);
    }
    return obj;
  },

  create(base?: DeepPartial<GetSessionStatusResponse>): GetSessionStatusResponse {
    return GetSessionStatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSessionStatusResponse>): GetSessionStatusResponse {
    const message = createBaseGetSessionStatusResponse();
    message.session = (object.session !== undefined && object.session !== null)
      ? PacketSessionDetail.fromPartial(object.session)
      : undefined;
    return message;
  },
};

function createBaseListSessionsRequest(): ListSessionsRequest {
  return {};
}

export const ListSessionsRequest: MessageFns<ListSessionsRequest> = {
  encode(_: ListSessionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSessionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSessionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListSessionsRequest {
    return {};
  },

  toJSON(_: ListSessionsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<ListSessionsRequest>): ListSessionsRequest {
    return ListSessionsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListSessionsRequest>): ListSessionsRequest {
    const message = createBaseListSessionsRequest();
    return message;
  },
};

function createBaseGetSessionByIpRequest(): GetSessionByIpRequest {
  return { peerIp: "" };
}

export const GetSessionByIpRequest: MessageFns<GetSessionByIpRequest> = {
  encode(message: GetSessionByIpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.peerIp !== "") {
      writer.uint32(10).string(message.peerIp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionByIpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionByIpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.peerIp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionByIpRequest {
    return {
      peerIp: isSet(object.peerIp)
        ? globalThis.String(object.peerIp)
        : isSet(object.peer_ip)
        ? globalThis.String(object.peer_ip)
        : "",
    };
  },

  toJSON(message: GetSessionByIpRequest): unknown {
    const obj: any = {};
    if (message.peerIp !== "") {
      obj.peerIp = message.peerIp;
    }
    return obj;
  },

  create(base?: DeepPartial<GetSessionByIpRequest>): GetSessionByIpRequest {
    return GetSessionByIpRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSessionByIpRequest>): GetSessionByIpRequest {
    const message = createBaseGetSessionByIpRequest();
    message.peerIp = object.peerIp ?? "";
    return message;
  },
};

function createBaseGetSessionByIpResponse(): GetSessionByIpResponse {
  return { session: undefined };
}

export const GetSessionByIpResponse: MessageFns<GetSessionByIpResponse> = {
  encode(message: GetSessionByIpResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      PacketSessionInfo.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionByIpResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionByIpResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = PacketSessionInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionByIpResponse {
    return { session: isSet(object.session) ? PacketSessionInfo.fromJSON(object.session) : undefined };
  },

  toJSON(message: GetSessionByIpResponse): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = PacketSessionInfo.toJSON(message.session);
    }
    return obj;
  },

  create(base?: DeepPartial<GetSessionByIpResponse>): GetSessionByIpResponse {
    return GetSessionByIpResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSessionByIpResponse>): GetSessionByIpResponse {
    const message = createBaseGetSessionByIpResponse();
    message.session = (object.session !== undefined && object.session !== null)
      ? PacketSessionInfo.fromPartial(object.session)
      : undefined;
    return message;
  },
};

function createBaseListSessionsResponse(): ListSessionsResponse {
  return { sessions: [] };
}

export const ListSessionsResponse: MessageFns<ListSessionsResponse> = {
  encode(message: ListSessionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sessions) {
      PacketSessionInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSessionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSessionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessions.push(PacketSessionInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSessionsResponse {
    return {
      sessions: globalThis.Array.isArray(object?.sessions)
        ? object.sessions.map((e: any) => PacketSessionInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListSessionsResponse): unknown {
    const obj: any = {};
    if (message.sessions?.length) {
      obj.sessions = message.sessions.map((e) => PacketSessionInfo.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListSessionsResponse>): ListSessionsResponse {
    return ListSessionsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListSessionsResponse>): ListSessionsResponse {
    const message = createBaseListSessionsResponse();
    message.sessions = object.sessions?.map((e) => PacketSessionInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSetSessionCaptureRequest(): SetSessionCaptureRequest {
  return { sessionId: "", enabled: false };
}

export const SetSessionCaptureRequest: MessageFns<SetSessionCaptureRequest> = {
  encode(message: SetSessionCaptureRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.enabled !== false) {
      writer.uint32(16).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSessionCaptureRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSessionCaptureRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetSessionCaptureRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
    };
  },

  toJSON(message: SetSessionCaptureRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create(base?: DeepPartial<SetSessionCaptureRequest>): SetSessionCaptureRequest {
    return SetSessionCaptureRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetSessionCaptureRequest>): SetSessionCaptureRequest {
    const message = createBaseSetSessionCaptureRequest();
    message.sessionId = object.sessionId ?? "";
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseSetSessionCaptureResponse(): SetSessionCaptureResponse {
  return { session: undefined };
}

export const SetSessionCaptureResponse: MessageFns<SetSessionCaptureResponse> = {
  encode(message: SetSessionCaptureResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      PacketSessionDetail.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSessionCaptureResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSessionCaptureResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = PacketSessionDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetSessionCaptureResponse {
    return { session: isSet(object.session) ? PacketSessionDetail.fromJSON(object.session) : undefined };
  },

  toJSON(message: SetSessionCaptureResponse): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = PacketSessionDetail.toJSON(message.session);
    }
    return obj;
  },

  create(base?: DeepPartial<SetSessionCaptureResponse>): SetSessionCaptureResponse {
    return SetSessionCaptureResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetSessionCaptureResponse>): SetSessionCaptureResponse {
    const message = createBaseSetSessionCaptureResponse();
    message.session = (object.session !== undefined && object.session !== null)
      ? PacketSessionDetail.fromPartial(object.session)
      : undefined;
    return message;
  },
};

function createBaseSetSchActiveRequest(): SetSchActiveRequest {
  return { sessionId: "", active: false, rateBps: 0 };
}

export const SetSchActiveRequest: MessageFns<SetSchActiveRequest> = {
  encode(message: SetSchActiveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.active !== false) {
      writer.uint32(16).bool(message.active);
    }
    if (message.rateBps !== 0) {
      writer.uint32(24).uint32(message.rateBps);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSchActiveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSchActiveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rateBps = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetSchActiveRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      rateBps: isSet(object.rateBps)
        ? globalThis.Number(object.rateBps)
        : isSet(object.rate_bps)
        ? globalThis.Number(object.rate_bps)
        : 0,
    };
  },

  toJSON(message: SetSchActiveRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.rateBps !== 0) {
      obj.rateBps = Math.round(message.rateBps);
    }
    return obj;
  },

  create(base?: DeepPartial<SetSchActiveRequest>): SetSchActiveRequest {
    return SetSchActiveRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetSchActiveRequest>): SetSchActiveRequest {
    const message = createBaseSetSchActiveRequest();
    message.sessionId = object.sessionId ?? "";
    message.active = object.active ?? false;
    message.rateBps = object.rateBps ?? 0;
    return message;
  },
};

function createBaseSetSchActiveResponse(): SetSchActiveResponse {
  return {};
}

export const SetSchActiveResponse: MessageFns<SetSchActiveResponse> = {
  encode(_: SetSchActiveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSchActiveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSchActiveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetSchActiveResponse {
    return {};
  },

  toJSON(_: SetSchActiveResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<SetSchActiveResponse>): SetSchActiveResponse {
    return SetSchActiveResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetSchActiveResponse>): SetSchActiveResponse {
    const message = createBaseSetSchActiveResponse();
    return message;
  },
};

function createBasePacketSessionInfo(): PacketSessionInfo {
  return {
    sessionId: "",
    phase: "",
    serviceOption: 0,
    peerIp: "",
    ourIp: "",
    tunDevice: "",
    uplinkFrames: 0,
    downlinkFrames: 0,
    uplinkBytes: 0,
    downlinkBytes: 0,
    createdAtMs: 0,
    lastPhaseChangeAtMs: 0,
    lastUplinkAtMs: 0,
    lastDownlinkAtMs: 0,
    lastActivityAtMs: 0,
    lastUplinkRateBps: 0,
    lastDownlinkRateBps: 0,
    mobileAddress: "",
    subscriberId: "",
    phoneNumber: "",
    trafficWalshCode: 0,
    rlpState: "",
    lcpState: "",
    ipcpState: "",
    captureEnabled: false,
    accessTechnology: 0,
    imsi: "",
    esn: 0,
    meid: "",
    hrpdMnId: "",
    hrpdMnIdSource: 0,
    subscriberImsi: "",
  };
}

export const PacketSessionInfo: MessageFns<PacketSessionInfo> = {
  encode(message: PacketSessionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.phase !== "") {
      writer.uint32(18).string(message.phase);
    }
    if (message.serviceOption !== 0) {
      writer.uint32(24).uint32(message.serviceOption);
    }
    if (message.peerIp !== "") {
      writer.uint32(34).string(message.peerIp);
    }
    if (message.ourIp !== "") {
      writer.uint32(42).string(message.ourIp);
    }
    if (message.tunDevice !== "") {
      writer.uint32(50).string(message.tunDevice);
    }
    if (message.uplinkFrames !== 0) {
      writer.uint32(80).uint64(message.uplinkFrames);
    }
    if (message.downlinkFrames !== 0) {
      writer.uint32(88).uint64(message.downlinkFrames);
    }
    if (message.uplinkBytes !== 0) {
      writer.uint32(96).uint64(message.uplinkBytes);
    }
    if (message.downlinkBytes !== 0) {
      writer.uint32(104).uint64(message.downlinkBytes);
    }
    if (message.createdAtMs !== 0) {
      writer.uint32(112).uint64(message.createdAtMs);
    }
    if (message.lastPhaseChangeAtMs !== 0) {
      writer.uint32(120).uint64(message.lastPhaseChangeAtMs);
    }
    if (message.lastUplinkAtMs !== 0) {
      writer.uint32(128).uint64(message.lastUplinkAtMs);
    }
    if (message.lastDownlinkAtMs !== 0) {
      writer.uint32(136).uint64(message.lastDownlinkAtMs);
    }
    if (message.lastActivityAtMs !== 0) {
      writer.uint32(144).uint64(message.lastActivityAtMs);
    }
    if (message.lastUplinkRateBps !== 0) {
      writer.uint32(152).uint32(message.lastUplinkRateBps);
    }
    if (message.lastDownlinkRateBps !== 0) {
      writer.uint32(160).uint32(message.lastDownlinkRateBps);
    }
    if (message.mobileAddress !== "") {
      writer.uint32(170).string(message.mobileAddress);
    }
    if (message.subscriberId !== "") {
      writer.uint32(178).string(message.subscriberId);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(186).string(message.phoneNumber);
    }
    if (message.trafficWalshCode !== 0) {
      writer.uint32(192).uint32(message.trafficWalshCode);
    }
    if (message.rlpState !== "") {
      writer.uint32(202).string(message.rlpState);
    }
    if (message.lcpState !== "") {
      writer.uint32(210).string(message.lcpState);
    }
    if (message.ipcpState !== "") {
      writer.uint32(218).string(message.ipcpState);
    }
    if (message.captureEnabled !== false) {
      writer.uint32(224).bool(message.captureEnabled);
    }
    if (message.accessTechnology !== 0) {
      writer.uint32(232).int32(message.accessTechnology);
    }
    if (message.imsi !== "") {
      writer.uint32(242).string(message.imsi);
    }
    if (message.esn !== 0) {
      writer.uint32(248).uint32(message.esn);
    }
    if (message.meid !== "") {
      writer.uint32(258).string(message.meid);
    }
    if (message.hrpdMnId !== "") {
      writer.uint32(266).string(message.hrpdMnId);
    }
    if (message.hrpdMnIdSource !== 0) {
      writer.uint32(272).int32(message.hrpdMnIdSource);
    }
    if (message.subscriberImsi !== "") {
      writer.uint32(282).string(message.subscriberImsi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketSessionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketSessionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.serviceOption = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.peerIp = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ourIp = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.tunDevice = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.uplinkFrames = longToNumber(reader.uint64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.downlinkFrames = longToNumber(reader.uint64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.uplinkBytes = longToNumber(reader.uint64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.downlinkBytes = longToNumber(reader.uint64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.createdAtMs = longToNumber(reader.uint64());
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.lastPhaseChangeAtMs = longToNumber(reader.uint64());
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.lastUplinkAtMs = longToNumber(reader.uint64());
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.lastDownlinkAtMs = longToNumber(reader.uint64());
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.lastActivityAtMs = longToNumber(reader.uint64());
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.lastUplinkRateBps = reader.uint32();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.lastDownlinkRateBps = reader.uint32();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.mobileAddress = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.subscriberId = reader.string();
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 192) {
            break;
          }

          message.trafficWalshCode = reader.uint32();
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.rlpState = reader.string();
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.lcpState = reader.string();
          continue;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.ipcpState = reader.string();
          continue;
        }
        case 28: {
          if (tag !== 224) {
            break;
          }

          message.captureEnabled = reader.bool();
          continue;
        }
        case 29: {
          if (tag !== 232) {
            break;
          }

          message.accessTechnology = reader.int32() as any;
          continue;
        }
        case 30: {
          if (tag !== 242) {
            break;
          }

          message.imsi = reader.string();
          continue;
        }
        case 31: {
          if (tag !== 248) {
            break;
          }

          message.esn = reader.uint32();
          continue;
        }
        case 32: {
          if (tag !== 258) {
            break;
          }

          message.meid = reader.string();
          continue;
        }
        case 33: {
          if (tag !== 266) {
            break;
          }

          message.hrpdMnId = reader.string();
          continue;
        }
        case 34: {
          if (tag !== 272) {
            break;
          }

          message.hrpdMnIdSource = reader.int32() as any;
          continue;
        }
        case 35: {
          if (tag !== 282) {
            break;
          }

          message.subscriberImsi = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketSessionInfo {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      phase: isSet(object.phase) ? globalThis.String(object.phase) : "",
      serviceOption: isSet(object.serviceOption)
        ? globalThis.Number(object.serviceOption)
        : isSet(object.service_option)
        ? globalThis.Number(object.service_option)
        : 0,
      peerIp: isSet(object.peerIp)
        ? globalThis.String(object.peerIp)
        : isSet(object.peer_ip)
        ? globalThis.String(object.peer_ip)
        : "",
      ourIp: isSet(object.ourIp)
        ? globalThis.String(object.ourIp)
        : isSet(object.our_ip)
        ? globalThis.String(object.our_ip)
        : "",
      tunDevice: isSet(object.tunDevice)
        ? globalThis.String(object.tunDevice)
        : isSet(object.tun_device)
        ? globalThis.String(object.tun_device)
        : "",
      uplinkFrames: isSet(object.uplinkFrames)
        ? globalThis.Number(object.uplinkFrames)
        : isSet(object.uplink_frames)
        ? globalThis.Number(object.uplink_frames)
        : 0,
      downlinkFrames: isSet(object.downlinkFrames)
        ? globalThis.Number(object.downlinkFrames)
        : isSet(object.downlink_frames)
        ? globalThis.Number(object.downlink_frames)
        : 0,
      uplinkBytes: isSet(object.uplinkBytes)
        ? globalThis.Number(object.uplinkBytes)
        : isSet(object.uplink_bytes)
        ? globalThis.Number(object.uplink_bytes)
        : 0,
      downlinkBytes: isSet(object.downlinkBytes)
        ? globalThis.Number(object.downlinkBytes)
        : isSet(object.downlink_bytes)
        ? globalThis.Number(object.downlink_bytes)
        : 0,
      createdAtMs: isSet(object.createdAtMs)
        ? globalThis.Number(object.createdAtMs)
        : isSet(object.created_at_ms)
        ? globalThis.Number(object.created_at_ms)
        : 0,
      lastPhaseChangeAtMs: isSet(object.lastPhaseChangeAtMs)
        ? globalThis.Number(object.lastPhaseChangeAtMs)
        : isSet(object.last_phase_change_at_ms)
        ? globalThis.Number(object.last_phase_change_at_ms)
        : 0,
      lastUplinkAtMs: isSet(object.lastUplinkAtMs)
        ? globalThis.Number(object.lastUplinkAtMs)
        : isSet(object.last_uplink_at_ms)
        ? globalThis.Number(object.last_uplink_at_ms)
        : 0,
      lastDownlinkAtMs: isSet(object.lastDownlinkAtMs)
        ? globalThis.Number(object.lastDownlinkAtMs)
        : isSet(object.last_downlink_at_ms)
        ? globalThis.Number(object.last_downlink_at_ms)
        : 0,
      lastActivityAtMs: isSet(object.lastActivityAtMs)
        ? globalThis.Number(object.lastActivityAtMs)
        : isSet(object.last_activity_at_ms)
        ? globalThis.Number(object.last_activity_at_ms)
        : 0,
      lastUplinkRateBps: isSet(object.lastUplinkRateBps)
        ? globalThis.Number(object.lastUplinkRateBps)
        : isSet(object.last_uplink_rate_bps)
        ? globalThis.Number(object.last_uplink_rate_bps)
        : 0,
      lastDownlinkRateBps: isSet(object.lastDownlinkRateBps)
        ? globalThis.Number(object.lastDownlinkRateBps)
        : isSet(object.last_downlink_rate_bps)
        ? globalThis.Number(object.last_downlink_rate_bps)
        : 0,
      mobileAddress: isSet(object.mobileAddress)
        ? globalThis.String(object.mobileAddress)
        : isSet(object.mobile_address)
        ? globalThis.String(object.mobile_address)
        : "",
      subscriberId: isSet(object.subscriberId)
        ? globalThis.String(object.subscriberId)
        : isSet(object.subscriber_id)
        ? globalThis.String(object.subscriber_id)
        : "",
      phoneNumber: isSet(object.phoneNumber)
        ? globalThis.String(object.phoneNumber)
        : isSet(object.phone_number)
        ? globalThis.String(object.phone_number)
        : "",
      trafficWalshCode: isSet(object.trafficWalshCode)
        ? globalThis.Number(object.trafficWalshCode)
        : isSet(object.traffic_walsh_code)
        ? globalThis.Number(object.traffic_walsh_code)
        : 0,
      rlpState: isSet(object.rlpState)
        ? globalThis.String(object.rlpState)
        : isSet(object.rlp_state)
        ? globalThis.String(object.rlp_state)
        : "",
      lcpState: isSet(object.lcpState)
        ? globalThis.String(object.lcpState)
        : isSet(object.lcp_state)
        ? globalThis.String(object.lcp_state)
        : "",
      ipcpState: isSet(object.ipcpState)
        ? globalThis.String(object.ipcpState)
        : isSet(object.ipcp_state)
        ? globalThis.String(object.ipcp_state)
        : "",
      captureEnabled: isSet(object.captureEnabled)
        ? globalThis.Boolean(object.captureEnabled)
        : isSet(object.capture_enabled)
        ? globalThis.Boolean(object.capture_enabled)
        : false,
      accessTechnology: isSet(object.accessTechnology)
        ? accessTechnologyFromJSON(object.accessTechnology)
        : isSet(object.access_technology)
        ? accessTechnologyFromJSON(object.access_technology)
        : 0,
      imsi: isSet(object.imsi) ? globalThis.String(object.imsi) : "",
      esn: isSet(object.esn) ? globalThis.Number(object.esn) : 0,
      meid: isSet(object.meid) ? globalThis.String(object.meid) : "",
      hrpdMnId: isSet(object.hrpdMnId)
        ? globalThis.String(object.hrpdMnId)
        : isSet(object.hrpd_mn_id)
        ? globalThis.String(object.hrpd_mn_id)
        : "",
      hrpdMnIdSource: isSet(object.hrpdMnIdSource)
        ? hrpdMnIdSourceFromJSON(object.hrpdMnIdSource)
        : isSet(object.hrpd_mn_id_source)
        ? hrpdMnIdSourceFromJSON(object.hrpd_mn_id_source)
        : 0,
      subscriberImsi: isSet(object.subscriberImsi)
        ? globalThis.String(object.subscriberImsi)
        : isSet(object.subscriber_imsi)
        ? globalThis.String(object.subscriber_imsi)
        : "",
    };
  },

  toJSON(message: PacketSessionInfo): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.phase !== "") {
      obj.phase = message.phase;
    }
    if (message.serviceOption !== 0) {
      obj.serviceOption = Math.round(message.serviceOption);
    }
    if (message.peerIp !== "") {
      obj.peerIp = message.peerIp;
    }
    if (message.ourIp !== "") {
      obj.ourIp = message.ourIp;
    }
    if (message.tunDevice !== "") {
      obj.tunDevice = message.tunDevice;
    }
    if (message.uplinkFrames !== 0) {
      obj.uplinkFrames = Math.round(message.uplinkFrames);
    }
    if (message.downlinkFrames !== 0) {
      obj.downlinkFrames = Math.round(message.downlinkFrames);
    }
    if (message.uplinkBytes !== 0) {
      obj.uplinkBytes = Math.round(message.uplinkBytes);
    }
    if (message.downlinkBytes !== 0) {
      obj.downlinkBytes = Math.round(message.downlinkBytes);
    }
    if (message.createdAtMs !== 0) {
      obj.createdAtMs = Math.round(message.createdAtMs);
    }
    if (message.lastPhaseChangeAtMs !== 0) {
      obj.lastPhaseChangeAtMs = Math.round(message.lastPhaseChangeAtMs);
    }
    if (message.lastUplinkAtMs !== 0) {
      obj.lastUplinkAtMs = Math.round(message.lastUplinkAtMs);
    }
    if (message.lastDownlinkAtMs !== 0) {
      obj.lastDownlinkAtMs = Math.round(message.lastDownlinkAtMs);
    }
    if (message.lastActivityAtMs !== 0) {
      obj.lastActivityAtMs = Math.round(message.lastActivityAtMs);
    }
    if (message.lastUplinkRateBps !== 0) {
      obj.lastUplinkRateBps = Math.round(message.lastUplinkRateBps);
    }
    if (message.lastDownlinkRateBps !== 0) {
      obj.lastDownlinkRateBps = Math.round(message.lastDownlinkRateBps);
    }
    if (message.mobileAddress !== "") {
      obj.mobileAddress = message.mobileAddress;
    }
    if (message.subscriberId !== "") {
      obj.subscriberId = message.subscriberId;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.trafficWalshCode !== 0) {
      obj.trafficWalshCode = Math.round(message.trafficWalshCode);
    }
    if (message.rlpState !== "") {
      obj.rlpState = message.rlpState;
    }
    if (message.lcpState !== "") {
      obj.lcpState = message.lcpState;
    }
    if (message.ipcpState !== "") {
      obj.ipcpState = message.ipcpState;
    }
    if (message.captureEnabled !== false) {
      obj.captureEnabled = message.captureEnabled;
    }
    if (message.accessTechnology !== 0) {
      obj.accessTechnology = accessTechnologyToJSON(message.accessTechnology);
    }
    if (message.imsi !== "") {
      obj.imsi = message.imsi;
    }
    if (message.esn !== 0) {
      obj.esn = Math.round(message.esn);
    }
    if (message.meid !== "") {
      obj.meid = message.meid;
    }
    if (message.hrpdMnId !== "") {
      obj.hrpdMnId = message.hrpdMnId;
    }
    if (message.hrpdMnIdSource !== 0) {
      obj.hrpdMnIdSource = hrpdMnIdSourceToJSON(message.hrpdMnIdSource);
    }
    if (message.subscriberImsi !== "") {
      obj.subscriberImsi = message.subscriberImsi;
    }
    return obj;
  },

  create(base?: DeepPartial<PacketSessionInfo>): PacketSessionInfo {
    return PacketSessionInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PacketSessionInfo>): PacketSessionInfo {
    const message = createBasePacketSessionInfo();
    message.sessionId = object.sessionId ?? "";
    message.phase = object.phase ?? "";
    message.serviceOption = object.serviceOption ?? 0;
    message.peerIp = object.peerIp ?? "";
    message.ourIp = object.ourIp ?? "";
    message.tunDevice = object.tunDevice ?? "";
    message.uplinkFrames = object.uplinkFrames ?? 0;
    message.downlinkFrames = object.downlinkFrames ?? 0;
    message.uplinkBytes = object.uplinkBytes ?? 0;
    message.downlinkBytes = object.downlinkBytes ?? 0;
    message.createdAtMs = object.createdAtMs ?? 0;
    message.lastPhaseChangeAtMs = object.lastPhaseChangeAtMs ?? 0;
    message.lastUplinkAtMs = object.lastUplinkAtMs ?? 0;
    message.lastDownlinkAtMs = object.lastDownlinkAtMs ?? 0;
    message.lastActivityAtMs = object.lastActivityAtMs ?? 0;
    message.lastUplinkRateBps = object.lastUplinkRateBps ?? 0;
    message.lastDownlinkRateBps = object.lastDownlinkRateBps ?? 0;
    message.mobileAddress = object.mobileAddress ?? "";
    message.subscriberId = object.subscriberId ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.trafficWalshCode = object.trafficWalshCode ?? 0;
    message.rlpState = object.rlpState ?? "";
    message.lcpState = object.lcpState ?? "";
    message.ipcpState = object.ipcpState ?? "";
    message.captureEnabled = object.captureEnabled ?? false;
    message.accessTechnology = object.accessTechnology ?? 0;
    message.imsi = object.imsi ?? "";
    message.esn = object.esn ?? 0;
    message.meid = object.meid ?? "";
    message.hrpdMnId = object.hrpdMnId ?? "";
    message.hrpdMnIdSource = object.hrpdMnIdSource ?? 0;
    message.subscriberImsi = object.subscriberImsi ?? "";
    return message;
  },
};

function createBasePacketTraceEvent(): PacketTraceEvent {
  return { timestampMs: 0, layer: "", direction: "", summary: "", detail: "", payloadHex: "" };
}

export const PacketTraceEvent: MessageFns<PacketTraceEvent> = {
  encode(message: PacketTraceEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestampMs !== 0) {
      writer.uint32(8).uint64(message.timestampMs);
    }
    if (message.layer !== "") {
      writer.uint32(18).string(message.layer);
    }
    if (message.direction !== "") {
      writer.uint32(26).string(message.direction);
    }
    if (message.summary !== "") {
      writer.uint32(34).string(message.summary);
    }
    if (message.detail !== "") {
      writer.uint32(42).string(message.detail);
    }
    if (message.payloadHex !== "") {
      writer.uint32(50).string(message.payloadHex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketTraceEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketTraceEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestampMs = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.layer = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.direction = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.detail = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.payloadHex = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketTraceEvent {
    return {
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
        ? globalThis.Number(object.timestamp_ms)
        : 0,
      layer: isSet(object.layer) ? globalThis.String(object.layer) : "",
      direction: isSet(object.direction) ? globalThis.String(object.direction) : "",
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
      payloadHex: isSet(object.payloadHex)
        ? globalThis.String(object.payloadHex)
        : isSet(object.payload_hex)
        ? globalThis.String(object.payload_hex)
        : "",
    };
  },

  toJSON(message: PacketTraceEvent): unknown {
    const obj: any = {};
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.layer !== "") {
      obj.layer = message.layer;
    }
    if (message.direction !== "") {
      obj.direction = message.direction;
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    if (message.payloadHex !== "") {
      obj.payloadHex = message.payloadHex;
    }
    return obj;
  },

  create(base?: DeepPartial<PacketTraceEvent>): PacketTraceEvent {
    return PacketTraceEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PacketTraceEvent>): PacketTraceEvent {
    const message = createBasePacketTraceEvent();
    message.timestampMs = object.timestampMs ?? 0;
    message.layer = object.layer ?? "";
    message.direction = object.direction ?? "";
    message.summary = object.summary ?? "";
    message.detail = object.detail ?? "";
    message.payloadHex = object.payloadHex ?? "";
    return message;
  },
};

function createBasePacketSessionDetail(): PacketSessionDetail {
  return {
    summary: undefined,
    lastRxControl: "",
    lastTxControl: "",
    lastRxControlRepeats: 0,
    lastTxControlRepeats: 0,
    recentPppEvents: [],
    captureEvents: [],
  };
}

export const PacketSessionDetail: MessageFns<PacketSessionDetail> = {
  encode(message: PacketSessionDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.summary !== undefined) {
      PacketSessionInfo.encode(message.summary, writer.uint32(10).fork()).join();
    }
    if (message.lastRxControl !== "") {
      writer.uint32(18).string(message.lastRxControl);
    }
    if (message.lastTxControl !== "") {
      writer.uint32(26).string(message.lastTxControl);
    }
    if (message.lastRxControlRepeats !== 0) {
      writer.uint32(32).uint64(message.lastRxControlRepeats);
    }
    if (message.lastTxControlRepeats !== 0) {
      writer.uint32(40).uint64(message.lastTxControlRepeats);
    }
    for (const v of message.recentPppEvents) {
      PacketTraceEvent.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.captureEvents) {
      PacketTraceEvent.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketSessionDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketSessionDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.summary = PacketSessionInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastRxControl = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastTxControl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lastRxControlRepeats = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lastTxControlRepeats = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.recentPppEvents.push(PacketTraceEvent.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.captureEvents.push(PacketTraceEvent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketSessionDetail {
    return {
      summary: isSet(object.summary) ? PacketSessionInfo.fromJSON(object.summary) : undefined,
      lastRxControl: isSet(object.lastRxControl)
        ? globalThis.String(object.lastRxControl)
        : isSet(object.last_rx_control)
        ? globalThis.String(object.last_rx_control)
        : "",
      lastTxControl: isSet(object.lastTxControl)
        ? globalThis.String(object.lastTxControl)
        : isSet(object.last_tx_control)
        ? globalThis.String(object.last_tx_control)
        : "",
      lastRxControlRepeats: isSet(object.lastRxControlRepeats)
        ? globalThis.Number(object.lastRxControlRepeats)
        : isSet(object.last_rx_control_repeats)
        ? globalThis.Number(object.last_rx_control_repeats)
        : 0,
      lastTxControlRepeats: isSet(object.lastTxControlRepeats)
        ? globalThis.Number(object.lastTxControlRepeats)
        : isSet(object.last_tx_control_repeats)
        ? globalThis.Number(object.last_tx_control_repeats)
        : 0,
      recentPppEvents: globalThis.Array.isArray(object?.recentPppEvents)
        ? object.recentPppEvents.map((e: any) => PacketTraceEvent.fromJSON(e))
        : globalThis.Array.isArray(object?.recent_ppp_events)
        ? object.recent_ppp_events.map((e: any) => PacketTraceEvent.fromJSON(e))
        : [],
      captureEvents: globalThis.Array.isArray(object?.captureEvents)
        ? object.captureEvents.map((e: any) => PacketTraceEvent.fromJSON(e))
        : globalThis.Array.isArray(object?.capture_events)
        ? object.capture_events.map((e: any) => PacketTraceEvent.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PacketSessionDetail): unknown {
    const obj: any = {};
    if (message.summary !== undefined) {
      obj.summary = PacketSessionInfo.toJSON(message.summary);
    }
    if (message.lastRxControl !== "") {
      obj.lastRxControl = message.lastRxControl;
    }
    if (message.lastTxControl !== "") {
      obj.lastTxControl = message.lastTxControl;
    }
    if (message.lastRxControlRepeats !== 0) {
      obj.lastRxControlRepeats = Math.round(message.lastRxControlRepeats);
    }
    if (message.lastTxControlRepeats !== 0) {
      obj.lastTxControlRepeats = Math.round(message.lastTxControlRepeats);
    }
    if (message.recentPppEvents?.length) {
      obj.recentPppEvents = message.recentPppEvents.map((e) => PacketTraceEvent.toJSON(e));
    }
    if (message.captureEvents?.length) {
      obj.captureEvents = message.captureEvents.map((e) => PacketTraceEvent.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<PacketSessionDetail>): PacketSessionDetail {
    return PacketSessionDetail.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PacketSessionDetail>): PacketSessionDetail {
    const message = createBasePacketSessionDetail();
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? PacketSessionInfo.fromPartial(object.summary)
      : undefined;
    message.lastRxControl = object.lastRxControl ?? "";
    message.lastTxControl = object.lastTxControl ?? "";
    message.lastRxControlRepeats = object.lastRxControlRepeats ?? 0;
    message.lastTxControlRepeats = object.lastTxControlRepeats ?? 0;
    message.recentPppEvents = object.recentPppEvents?.map((e) => PacketTraceEvent.fromPartial(e)) || [];
    message.captureEvents = object.captureEvents?.map((e) => PacketTraceEvent.fromPartial(e)) || [];
    return message;
  },
};

/** Packet data service used by the PCF/PDSN edge to manage RLP/PPP/IP sessions. */
export type PacketServiceDefinition = typeof PacketServiceDefinition;
export const PacketServiceDefinition = {
  name: "PacketService",
  fullName: "packet.v1.PacketService",
  methods: {
    /** Opens or replaces packet session state for one mobile data call. */
    openSession: {
      name: "OpenSession",
      requestType: OpenSessionRequest as typeof OpenSessionRequest,
      requestStream: false,
      responseType: OpenSessionResponse as typeof OpenSessionResponse,
      responseStream: false,
      options: {},
    },
    /** Closes one packet session and releases associated transport resources. */
    closeSession: {
      name: "CloseSession",
      requestType: CloseSessionRequest as typeof CloseSessionRequest,
      requestStream: false,
      responseType: CloseSessionResponse as typeof CloseSessionResponse,
      responseStream: false,
      options: {},
    },
    /** Exchanges reverse and forward RLP frame payloads for a packet session. */
    streamSession: {
      name: "StreamSession",
      requestType: SessionFrame as typeof SessionFrame,
      requestStream: true,
      responseType: SessionFrame as typeof SessionFrame,
      responseStream: true,
      options: {},
    },
    /** Returns detailed RLP/PPP/IP state for one packet session. */
    getSessionStatus: {
      name: "GetSessionStatus",
      requestType: GetSessionStatusRequest as typeof GetSessionStatusRequest,
      requestStream: false,
      responseType: GetSessionStatusResponse as typeof GetSessionStatusResponse,
      responseStream: false,
      options: {},
    },
    /** Lists known packet sessions. */
    listSessions: {
      name: "ListSessions",
      requestType: ListSessionsRequest as typeof ListSessionsRequest,
      requestStream: false,
      responseType: ListSessionsResponse as typeof ListSessionsResponse,
      responseStream: false,
      options: {},
    },
    /**
     * Looks up one active packet session by its assigned mobile (peer) IP, for
     * attributing inbound traffic to a subscriber. Returns the session summary,
     * or an unset `session` field when no active session has that peer_ip.
     */
    getSessionByIp: {
      name: "GetSessionByIp",
      requestType: GetSessionByIpRequest as typeof GetSessionByIpRequest,
      requestStream: false,
      responseType: GetSessionByIpResponse as typeof GetSessionByIpResponse,
      responseStream: false,
      options: {},
    },
    /** Enables or disables per-session packet trace capture. */
    setSessionCapture: {
      name: "SetSessionCapture",
      requestType: SetSessionCaptureRequest as typeof SetSessionCaptureRequest,
      requestStream: false,
      responseType: SetSessionCaptureResponse as typeof SetSessionCaptureResponse,
      responseStream: false,
      options: {},
    },
    /**
     * Enables or disables F-SCH downlink frame generation on a running session.
     * Set active=true after an F-SCH allocation and active=false during
     * teardown / SCH release.
     */
    setSchActive: {
      name: "SetSchActive",
      requestType: SetSchActiveRequest as typeof SetSchActiveRequest,
      requestStream: false,
      responseType: SetSchActiveResponse as typeof SetSchActiveResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface PacketServiceImplementation<CallContextExt = {}> {
  /** Opens or replaces packet session state for one mobile data call. */
  openSession(
    request: OpenSessionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<OpenSessionResponse>>;
  /** Closes one packet session and releases associated transport resources. */
  closeSession(
    request: CloseSessionRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CloseSessionResponse>>;
  /** Exchanges reverse and forward RLP frame payloads for a packet session. */
  streamSession(
    request: AsyncIterable<SessionFrame>,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<SessionFrame>>;
  /** Returns detailed RLP/PPP/IP state for one packet session. */
  getSessionStatus(
    request: GetSessionStatusRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionStatusResponse>>;
  /** Lists known packet sessions. */
  listSessions(
    request: ListSessionsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListSessionsResponse>>;
  /**
   * Looks up one active packet session by its assigned mobile (peer) IP, for
   * attributing inbound traffic to a subscriber. Returns the session summary,
   * or an unset `session` field when no active session has that peer_ip.
   */
  getSessionByIp(
    request: GetSessionByIpRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetSessionByIpResponse>>;
  /** Enables or disables per-session packet trace capture. */
  setSessionCapture(
    request: SetSessionCaptureRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetSessionCaptureResponse>>;
  /**
   * Enables or disables F-SCH downlink frame generation on a running session.
   * Set active=true after an F-SCH allocation and active=false during
   * teardown / SCH release.
   */
  setSchActive(
    request: SetSchActiveRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetSchActiveResponse>>;
}

export interface PacketServiceClient<CallOptionsExt = {}> {
  /** Opens or replaces packet session state for one mobile data call. */
  openSession(
    request: DeepPartial<OpenSessionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<OpenSessionResponse>;
  /** Closes one packet session and releases associated transport resources. */
  closeSession(
    request: DeepPartial<CloseSessionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CloseSessionResponse>;
  /** Exchanges reverse and forward RLP frame payloads for a packet session. */
  streamSession(
    request: AsyncIterable<DeepPartial<SessionFrame>>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<SessionFrame>;
  /** Returns detailed RLP/PPP/IP state for one packet session. */
  getSessionStatus(
    request: DeepPartial<GetSessionStatusRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionStatusResponse>;
  /** Lists known packet sessions. */
  listSessions(
    request: DeepPartial<ListSessionsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListSessionsResponse>;
  /**
   * Looks up one active packet session by its assigned mobile (peer) IP, for
   * attributing inbound traffic to a subscriber. Returns the session summary,
   * or an unset `session` field when no active session has that peer_ip.
   */
  getSessionByIp(
    request: DeepPartial<GetSessionByIpRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetSessionByIpResponse>;
  /** Enables or disables per-session packet trace capture. */
  setSessionCapture(
    request: DeepPartial<SetSessionCaptureRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetSessionCaptureResponse>;
  /**
   * Enables or disables F-SCH downlink frame generation on a running session.
   * Set active=true after an F-SCH allocation and active=false during
   * teardown / SCH release.
   */
  setSchActive(
    request: DeepPartial<SetSchActiveRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetSchActiveResponse>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
