// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.4
// source: bsc_management/v1/service.proto

/* eslint-disable */
import type { CallContext, CallOptions } from "nice-grpc-common";
import {
  AccessEvent,
  ChannelList,
  MobileList,
  PagingEvent,
  SetTrafficChannelPowerOverrideRequest,
  SetTrafficChannelPowerOverrideResponse,
  SystemStatus,
  TrafficEvent,
} from "../../bsc/v1/service";
import { Empty } from "../../google/protobuf/empty";

export const protobufPackage = "bsc_management.v1";

/** BSC management API for radio-access state, events, and operator controls. */
export type BscManagementServiceDefinition = typeof BscManagementServiceDefinition;
export const BscManagementServiceDefinition = {
  name: "BscManagementService",
  fullName: "bsc_management.v1.BscManagementService",
  methods: {
    /** Returns current BSC/BTS serving status. */
    getBscStatus: {
      name: "GetBscStatus",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: SystemStatus as typeof SystemStatus,
      responseStream: false,
      options: {},
    },
    /** Lists mobiles known to the BSC mobility table. */
    listMobiles: {
      name: "ListMobiles",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: MobileList as typeof MobileList,
      responseStream: false,
      options: {},
    },
    /** Lists configured and allocated radio channels. */
    listChannels: {
      name: "ListChannels",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: ChannelList as typeof ChannelList,
      responseStream: false,
      options: {},
    },
    /** Streams decoded reverse access-channel events. */
    streamAccessEvents: {
      name: "StreamAccessEvents",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: AccessEvent as typeof AccessEvent,
      responseStream: true,
      options: {},
    },
    /** Streams forward paging-channel transmissions. */
    streamPagingEvents: {
      name: "StreamPagingEvents",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: PagingEvent as typeof PagingEvent,
      responseStream: true,
      options: {},
    },
    /** Streams forward dedicated traffic-channel transmissions. */
    streamTrafficEvents: {
      name: "StreamTrafficEvents",
      requestType: Empty as typeof Empty,
      requestStream: false,
      responseType: TrafficEvent as typeof TrafficEvent,
      responseStream: true,
      options: {},
    },
    /** Applies or clears a manual reverse power-control target override. */
    setTrafficChannelPowerOverride: {
      name: "SetTrafficChannelPowerOverride",
      requestType: SetTrafficChannelPowerOverrideRequest as typeof SetTrafficChannelPowerOverrideRequest,
      requestStream: false,
      responseType: SetTrafficChannelPowerOverrideResponse as typeof SetTrafficChannelPowerOverrideResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface BscManagementServiceImplementation<CallContextExt = {}> {
  /** Returns current BSC/BTS serving status. */
  getBscStatus(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<SystemStatus>>;
  /** Lists mobiles known to the BSC mobility table. */
  listMobiles(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<MobileList>>;
  /** Lists configured and allocated radio channels. */
  listChannels(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<ChannelList>>;
  /** Streams decoded reverse access-channel events. */
  streamAccessEvents(
    request: Empty,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<AccessEvent>>;
  /** Streams forward paging-channel transmissions. */
  streamPagingEvents(
    request: Empty,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<PagingEvent>>;
  /** Streams forward dedicated traffic-channel transmissions. */
  streamTrafficEvents(
    request: Empty,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<TrafficEvent>>;
  /** Applies or clears a manual reverse power-control target override. */
  setTrafficChannelPowerOverride(
    request: SetTrafficChannelPowerOverrideRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SetTrafficChannelPowerOverrideResponse>>;
}

export interface BscManagementServiceClient<CallOptionsExt = {}> {
  /** Returns current BSC/BTS serving status. */
  getBscStatus(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<SystemStatus>;
  /** Lists mobiles known to the BSC mobility table. */
  listMobiles(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<MobileList>;
  /** Lists configured and allocated radio channels. */
  listChannels(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<ChannelList>;
  /** Streams decoded reverse access-channel events. */
  streamAccessEvents(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): AsyncIterable<AccessEvent>;
  /** Streams forward paging-channel transmissions. */
  streamPagingEvents(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): AsyncIterable<PagingEvent>;
  /** Streams forward dedicated traffic-channel transmissions. */
  streamTrafficEvents(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): AsyncIterable<TrafficEvent>;
  /** Applies or clears a manual reverse power-control target override. */
  setTrafficChannelPowerOverride(
    request: DeepPartial<SetTrafficChannelPowerOverrideRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SetTrafficChannelPowerOverrideResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };
