fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .compile_protos(
            &[
                "../../proto/events/v1/service.proto",
                "../../proto/events/v1/pdsn.proto",
                "../../proto/events/v1/bsc.proto",
                "../../proto/events/v1/msc.proto",
                "../../proto/events/v1/pcf.proto",
                "../../proto/events/v1/hlr.proto",
                "../../proto/events/v1/smsc.proto",
                "../../proto/events/v1/bts.proto",
            ],
            &["../../proto"],
        )?;
    Ok(())
}
